- .github/workflows/build.yml
- .gitmodules
Swapped **name** and **shortName**, now folder name and in-game display is short **BARb**.
Switched submodule branch from **barb3** to **barbarian**
> Update BARb submodule

- rts/Map/ReadMap.cpp
Addressed issue with full loss of usable map on first structure build.
> Fixed issue with end cycle sweep on ReadMap Height Maps.

- .gitmodules
CircuitAI: replaced reference from spring to rlcevg repo as there will be changes with AI API.
BARb: update to talest version.
> Update CircuitAI and BARb submodules

- rts/Lua/LuaParser.cpp
… conform to math:random() spec
> Bar fix https://github.com/beyond-all-reason/spring/issues/45

- .github/workflows/build.yml
Be careful with switch '-a' in `git commit -a -m "text"`, as it may affect submodules.
Add changed files manually
```
git add <file>
git add <file>
git commit -m "text"
```
Fixing downgraded CircuitAI submodule.
> Update BARb and CircuitAI. Remove external BARb profiles

- rts/Game/Game.cpp
> Fix native AI init order

- rts/lib/assimp/code/fast_atof.h
Doubles are the work of the devil.
> Fix assimp atof sync.

- rts/Game/UI/HwMouseCursor.cpp
Fix #199 crash until proper support is available
> HwMouseCursor: Disable when SDL driver is wayland

- cont/base/springcontent/LuaGadgets/setupdefs.lua
There is no `weapontype` field in WeaponDefs, the previous was kosher all along though.
thx [BoS]nixtux!
> Revert 980dda9bf26d3d2ac2b1212eefe7f748a6231184

- rts/Game/UI/SelectionKeyHandler.cpp
Selects the one unit from the selection that is closest to the mouse position.
> [SelectionKeyHandler] Add new selector `SelectOneNearestMouse'

- rts/Game/UI/SelectionKeyHandler.cpp
Filters for front of command queue == CMD_GUARD.
> [SelectionKeyHandler] Add new Filter `Guarding'.

- rts/Game/UI/GuiHandler.cpp
- rts/Game/UI/GuiHandler.h
int actionOffset was accidentially reused to go through actionList and actionList_SC
> Fix reuse of actionOffset

- rts/Game/SelectedUnitsHandler.cpp
- rts/Game/UnsyncedGameCommands.cpp
- rts/System/StringUtil.h
Given my last two pull requests, I'm just going through the executor's code and trying to cleaning them up and uniforming the way they parse arguments and so on.
I'm trying to keep each commit to each class so hopefully it's easier to review and fix/cherrypick/etc if needed. A couple commits sneaked in about another couple things, but I can remove them/move them to another PR if preferred.
I'm trying very hard to keep behavior intact, but obviously we should probably test these. I'm wondering if there's anything setup already for this.
I'm still not finished but I thought I'd open the PR anyway to let people see what I'm doing, if it makes any sense, or maybe I should just stop :)
This is currently based on #259 (since that's where I started making the fixes), but does not depend on it …
> Unsynced game commands cleanup (and others)

- doc/changelog.txt
- rts/Game/UI/IKeys.cpp
- rts/Game/UI/IKeys.h
- rts/Game/UI/KeyCodes.cpp
- rts/Game/UI/KeyCodes.h
- rts/Game/UI/KeySet.cpp
- rts/Game/UI/ScanCodes.cpp
- rts/Game/UI/ScanCodes.h
Fix: https://github.com/beyond-all-reason/spring/issues/309
> KeyBindings: Allow sc_0x<hexvalue> keysets

- rts/Net/GameParticipant.cpp
- rts/Net/GameParticipant.h
- rts/Net/GameServer.cpp
Tested on test server between two client machines on my part. No pauses detected. Resolves: https://github.com/beyond-all-reason/spring/issues/296
> Bar105 client disconnect lag fix

- rts/Sim/Misc/GlobalSynced.cpp
- rts/Sim/Misc/GlobalSynced.h
- rts/Sim/Misc/QuadField.cpp
- rts/Sim/Misc/QuadField.h
- rts/Sim/MoveTypes/GroundMoveType.cpp
- rts/Sim/MoveTypes/GroundMoveType.h
- rts/Sim/MoveTypes/MoveType.h
- rts/Sim/Objects/WorldObject.cpp
- rts/Sim/Objects/WorldObject.h
- rts/Sim/Units/UnitHandler.cpp
Multi-threads the collision avoidance code in GroundMoveType. Sync Tested.
> Bar105 collision avoidance mt

- rts/Rendering/GL/RenderBuffers.h
- rts/System/ScopedResource.h
- rts/lib/lru/LruClockCache.h
I don't get why gcc is fine with those mistakes...
> Fix various small compile errors

- rts/Game/GameHelper.cpp
Fixed building a floater via a builder (like ZK Athena) getting blocked by underwater slopes:
> Floating mobiles can be built over seafloor slopes

- rts/Rendering/OGLDBInfo.cpp
Fix usage after https://github.com/beyond-all-reason/pr-downloader/pull/13 get's merged and pr-downloader reference updated
> Fix usage of prd CurlWrapper

- rts/Sim/Misc/QuadField.cpp
- rts/Sim/Misc/QuadField.h
- rts/Sim/MoveTypes/GroundMoveType.cpp
- rts/Sim/MoveTypes/GroundMoveType.h
- rts/Sim/MoveTypes/MoveDefHandler.h
- rts/Sim/MoveTypes/MoveType.h
- rts/Sim/Units/UnitHandler.cpp
Resolves https://github.com/beyond-all-reason/spring/issues/231
Resolves https://github.com/beyond-all-reason/spring/issues/15
Collision detection is now multi-threaded.
Collision impulse is limited in length to the unit's max speed.
Tested on BAR.
Tested on ZK.
> Multi-threaded collision handling system

- rts/Game/UI/HwMouseCursor.cpp
- rts/Game/UI/HwMouseCursor.h
- rts/Game/UI/MouseCursor.cpp
- rts/Game/UI/MouseCursor.h
- rts/Game/UI/MouseHandler.cpp
fixes #253 
Is resizing to next power of 2 required? It seems to be in the right size for me.
> implement animated wayland hw cursor

- doc/changelog.txt
- rts/Lua/LuaIntro.cpp
- rts/Lua/LuaMenu.cpp
- rts/Lua/LuaUnsyncedRead.cpp
- rts/Lua/LuaUnsyncedRead.h
- rts/System/Input/KeyInput.cpp
- rts/System/Input/KeyInput.h
- rts/System/SpringApp.cpp
Similar output to GetPressedKeys but with ScanCodes
> Callouts: Add GetPressedScans()

- rts/Sim/MoveTypes/GroundMoveType.cpp
- rts/Sim/MoveTypes/GroundMoveType.h
Fixes https://github.com/beyond-all-reason/spring/issues/232
> fix issue with sliding units

- rts/Game/Game.cpp
- rts/Sim/Misc/ModInfo.cpp
- rts/Sim/Misc/ModInfo.h
- rts/Sim/MoveTypes/MoveMath/MoveMath.cpp
- rts/Sim/MoveTypes/MoveMath/MoveMath.h
- rts/Sim/MoveTypes/MoveType.cpp
- rts/Sim/MoveTypes/MoveType.h
- rts/Sim/Path/TKPFS/IPathFinder.cpp
- rts/Sim/Path/TKPFS/PathFinder.cpp
- rts/Sim/Path/TKPFS/PathFinder.h
- rts/Sim/Path/TKPFS/PathGlobal.h
- rts/Sim/Path/TKPFS/PathManager.cpp
- rts/Sim/Path/TKPFS/PathingState.cpp
- rts/Sim/Units/UnitHandler.cpp
Things I've wanted to sort out for a while.
> Bar105 path finding improvements

- doc/changelog.txt
- rts/Game/SelectedUnitsHandler.cpp
- rts/Game/SelectedUnitsHandler.h
- rts/Game/UI/Groups/GroupHandler.cpp
- rts/Game/UnsyncedGameCommands.cpp
Fixes https://github.com/beyond-all-reason/spring/issues/409
> UActions: Add group unset action

- doc/changelog.txt
- rts/Lua/LuaUnsyncedCtrl.cpp
> Spring.Marker functions: drop numerical onlyLocal

- doc/changelog.txt
- rts/Game/UI/MiniMap.cpp
- rts/Game/UI/MiniMap.h
- rts/Lua/LuaUnsyncedRead.cpp
- rts/Lua/LuaUnsyncedRead.h
- rts/Rendering/Units/UnitDrawer.cpp
Also adds `rotX, rotY, rotZ = Spring.GetCameraRotation()`
> Minimap: Flip according to camera rotation

- rts/Game/Camera/OverheadController.cpp
- rts/Game/Camera/SpringController.cpp
- rts/Game/UI/MouseHandler.cpp
- rts/Game/UI/MouseHandler.h
Also listen to `InvertMouse` setting changes
> Camera: Respect invertMouse speed on MMB move

- README.markdown
So we make sure developers don't get confused with the fork base and our repo
> Simple update for BAR

- doc/changelog.txt
Put them in a fatass section at the front + add instructions on how to get old behviour.
> Changelog: be clearer about backward compatibility

- rts/Game/Camera.cpp
- rts/Game/UI/MiniMap.cpp
- rts/Lua/LuaConstPlatform.cpp
- rts/Lua/LuaUnsyncedCtrl.cpp
- rts/Lua/LuaUnsyncedRead.cpp
- rts/Lua/LuaUnsyncedRead.h
- rts/Rendering/Env/BumpWater.cpp
- rts/Rendering/Env/Decals/DecalsDrawerGL4.cpp
- rts/Rendering/Env/DynWater.cpp
- rts/Rendering/Env/GrassDrawer.cpp
- rts/Rendering/Env/Particles/ProjectileDrawer.cpp
- rts/Rendering/Env/RefractWater.cpp
- rts/Rendering/GlobalRendering.cpp
- rts/Rendering/Map/InfoTexture/Modern/AirLos.cpp
- rts/Rendering/Map/InfoTexture/Modern/Combiner.cpp
- rts/Rendering/Map/InfoTexture/Modern/Height.cpp
- rts/Rendering/Map/InfoTexture/Modern/Los.cpp
- rts/Rendering/Map/InfoTexture/Modern/MetalExtraction.cpp
- rts/Rendering/Map/InfoTexture/Modern/Path.cpp
- rts/Rendering/Map/InfoTexture/Modern/Radar.cpp
- Fix viewPosY for remaining components
- Add Platform.numDisplays and Spring.GetNumDisplays()
- Listen to DualScreenMode and DualScreenModeMiniMapOnLeft
> DualScreen: General adjustments

- rts/Game/Game.cpp
- rts/Game/LoadScreen.cpp
- rts/Game/LoadScreen.h
- rts/Lua/LuaHandleSynced.cpp
- rts/Map/SMF/SMFGroundDrawer.cpp
- rts/Map/SMF/SMFReadMap.cpp
- rts/Rendering/GlobalRendering.cpp
- rts/Rendering/GlobalRendering.h
- rts/Rendering/Models/IModelParser.cpp
- rts/System/CMakeLists.txt
- rts/System/GameLoadThread.cpp
- rts/System/GameLoadThread.h
- rts/System/Input/MouseInput.cpp
- rts/System/LoadLock.h
- rts/System/OffscreenGLContext.cpp
- rts/System/Platform/WindowManagerHelper.cpp
- rts/System/QueueToMain.h
- rts/System/SpringApp.cpp
- rts/System/TemplateUtils.hpp
- rts/System/Threading/ThreadPool.cpp
This is very very raw for now.
> Bar105 MultiThreaded Loading

- rts/Lua/LuaVFS.cpp
Says the vfs mode and interprets the "file missing" status
> `VFS.Include` gives better hints

- rts/Sim/Path/Default/PathFinderDef.cpp
- rts/Sim/Path/Default/PathFinderDef.h
- rts/Sim/Path/TKPFS/IPathFinder.cpp
- rts/Sim/Path/TKPFS/IPathFinder.h
- rts/Sim/Path/TKPFS/PathEstimator.cpp
- rts/Sim/Path/TKPFS/PathEstimator.h
- rts/Sim/Path/TKPFS/PathFinder.cpp
- rts/Sim/Path/TKPFS/PathManager.cpp
Checks that the current block's reference point is reachable before pathing from there. (Resolves #600)
> Address pathfinding issues

- rts/Game/SelectedUnitsAI.cpp
- rts/Game/SelectedUnitsAI.h
Tested and ready to go. We have a feature freeze at the moment, so this will have to wait until after the upcoming engine release.
> Improved unit formation move command.

- doc/changelog.txt
- doc/site/migrating-from-spring.markdown
- rts/Lua/LuaUnsyncedRead.cpp
Fixes https://github.com/beyond-all-reason/spring/issues/669
> feat: Remove n from SelectedUnitsCounts{,Sorted}

- rts/Game/PreGame.cpp
- rts/Lua/LuaHandle.cpp
- rts/Map/SMF/SMFGroundDrawer.cpp
- rts/Net/GameServer.cpp
- rts/Rendering/Env/CubeMapHandler.cpp
- rts/Rendering/Env/Decals/GroundDecalHandler.cpp
- rts/Rendering/LuaObjectDrawer.cpp
- rts/Rendering/Map/InfoTexture/Modern/Combiner.cpp
- rts/Rendering/Textures/TextureAtlas.cpp
- rts/System/GlobalConfig.cpp
Added what I knew off the top of my head
> Update config variable docs

- rts/Sim/Units/Scripts/CobThread.cpp
- rts/Sim/Units/Scripts/CobThread.h
This is partly reverting 9da2251805ed7eb373dc0ee1676fff79449cc341
Savings on my test case with 500 janus firing:
- Sim::Unit::Weapon 5%
- TickRunningThreads 35%
- AddQueuedThreads 18%
The primarily savings are from the thread creation/moving etc, as it's way less data to copy around.
I assume I've not noticed negative impact because the size of CobThread from head to those fields is still > cache line size (accessing stacks requires fetching new block of memory), I've not really noticed any negative impacts caused by this additional memory indirection. Or maybe it's just negligible.
I did notice negative impact when creation of vectors involved memory allocation, so I'm pooling them.
> Switch to holding stacks from array to memory pooled vectors

- rts/Lua/LuaHandle.cpp
- rts/Lua/LuaHandle.h
- rts/Lua/LuaUtils.cpp
- rts/Lua/LuaUtils.h
Hopefully it doesn't leak more data than it should
> Implement https://github.com/beyond-all-reason/spring/issues/391

- rts/lib/luasocket/src/select.cpp
In lua then we have what was the cause for issue, not only "error".
> Improve error message returned from global_select

- doc/site/articles/team-terminology.markdown
Well whaddya know, there actually is native support for factions
> Fix a mistake in the team article

- rts/ExternalAI/AICallback.cpp
- rts/Rendering/Common/ModelDrawer.h
- rts/Rendering/Env/IGroundDecalDrawer.h
- rts/Rendering/Models/IModelParser.h
- rts/Rendering/Units/UnitDrawer.cpp
- rts/Rendering/Units/UnitDrawerData.cpp
- rts/Rendering/Units/UnitDrawerData.h
- rts/Sim/Units/Unit.h
- rts/System/LoadSave/CregLoadSaveHandler.cpp
Fixes:
https://github.com/beyond-all-reason/spring/issues/677
https://github.com/beyond-all-reason/spring/issues/640
> Save live,dead ghost buildings, don't leak unit status with iconsasui

- rts/Game/Camera.cpp
- rts/Game/Camera.h
- rts/Map/SMF/Basic/BasicMeshDrawer.cpp
- rts/Map/SMF/ROAM/Patch.cpp
- rts/Map/SMF/ROAM/RoamMeshDrawer.cpp
- rts/System/AABB.cpp
- rts/System/AABB.hpp
- rts/System/CMakeLists.txt
I think I traced origins of this error back to the beginnings of git history. Another eternal bug.
> BAR105 Fix invalid culling of terrain mesh patches happening with some cameras at oblique angles

- doc/changelog.txt
- rts/Game/Camera.cpp
- rts/Game/Camera.h
- rts/System/SpringMath.cpp
- rts/System/SpringMath.h
Fixes issues with orthogonal normals to xz-plane
> fix(Camera): Simplify frustumlines codebase

- rts/Rendering/Common/ModelDrawer.h
- rts/Rendering/Common/ModelDrawerHelpers.cpp
- rts/Rendering/Common/ModelDrawerHelpers.h
- rts/Rendering/Env/Particles/Classes/FlyingPiece.cpp
- rts/Rendering/Models/3DModel.h
https://github.com/beyond-all-reason/spring/issues/755
> Fix 3do shattered pieces rendering (no texture)

- rts/Game/Game.cpp
Lua states can leak GL state leading to changing colours
> Make `/clock` colour consistent

- README.markdown
I sort of did them blind, if you'd like to reword anything, shoot :)
> Minor readme compilation instruction fixes

- rts/Sim/Projectiles/ProjectileHandler.cpp
any chance this code was intentionally not measured ? but it doesn't sound right to ignore it.
> fix Projectile timer scope

- rts/System/FileSystem/Archives/BufferedArchive.cpp
- rts/System/FileSystem/Archives/BufferedArchive.h
(most files are only accessed once)
> CBufferedArchive will only buffer files starting from second access 

- doc/changelog.txt
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaSyncedRead.h
Spring.GetUnitWorkerTask(unitID) -> cmdID, targetID
Similar to GetUnitCurrentCommand, but shows what the unit is actually doing, so will differ when the unit is guarding or out of range.
> Add `Spring.GetUnitWorkerTask`

- doc/changelog.txt
- doc/site/_data/weapondefs.json
- rts/Game/GameHelper.cpp
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Sim/Misc/DamageArray.cpp
- rts/Sim/Units/Unit.cpp
- rts/Sim/Weapons/PlasmaRepulser.cpp
- rts/Sim/Weapons/WeaponDef.cpp
* allow arbitrary armor modifier and damage (incl. 0 and negative)
* allow edgeEffectiveness == 1 (previously capped at 0.999)
* fix direct hits sometimes not doing full damage due to fall-off
* fix some Lua interfaces being able to set edgeEffectiveness above 1
> Fix various damage edge cases

- doc/StartScriptFormat.txt
This .txt file is just documentation, there is no code change.
> Startscript reference: remove `ScriptName`

- doc/changelog.txt
- rts/Lua/LuaUnitDefs.cpp
- rts/Sim/Units/UnitDef.cpp
Additionally, add some commentary in the source code
> Defs keys design pass. See #801

- doc/changelog.txt
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaSyncedRead.h
Also fix the docs for `Spring.GetUnitIsStunned`.
> Add `Spring.GetUnitIsBeingBuilt`

- cont/base/springcontent/LuaGadgets/Gadgets/unit_script.lua
- cont/base/springcontent/gamedata/VFSUtils.lua
- cont/base/springcontent/gamedata/explosions.lua
- cont/base/springcontent/gamedata/featuredefs.lua
- cont/base/springcontent/gamedata/unitdefs.lua
- cont/base/springcontent/gamedata/weapondefs.lua
- doc/changelog.txt
- rts/Lua/LuaParser.cpp
- rts/Lua/LuaVFS.cpp
- rts/Lua/LuaZip.cpp
- rts/System/FileSystem/DataDirsAccess.cpp
- rts/System/FileSystem/FileHandler.cpp
- rts/System/FileSystem/FileHandler.h
- rts/System/FileSystem/VFSHandler.cpp
- rts/System/FileSystem/VFSHandler.h
- tools/unitsync/unitsync.cpp
`VFS.DirList` and `VFS.SubDirs` now accept a 4th bool parameter that makes them perform their respective searches recursively.
> Add recursive searching to Lua VFS API

- doc/site/articles/ceg-operators.markdown
> Add a CEG operators article

- doc/site/_data/non_coder_contributors.yml
- doc/site/index.markdown
> fix(site): Fix release links, add non coder and shuffle contributors list

- cont/base/springcontent/LuaGadgets/gadgets.lua
- doc/changelog.txt
- rts/Lua/LuaHandleSynced.cpp
- rts/Lua/LuaHandleSynced.h
- rts/Sim/Units/CommandAI/BuilderCAI.cpp
- rts/Sim/Units/UnitTypes/Factory.cpp
- rts/System/EventClient.h
- rts/System/EventHandler.cpp
- rts/System/EventHandler.h
> AllowUnitCreation specifies whether to drop order

- doc/site/guides/choose-recoil.markdown
The question crops up from time to time, would be nice to have a linkable comprehensive FAQ.
This is a draft though because:
* being a platform is, to some extent, a lie. Many of the "platform" things are not actually Recoil but Spring (for example a forum or a "common" server where random "picasso" style mods aren't 2nd class citizens like they are on ZK and BAR servers) and some "community content" is not really something you'd use (for example BAR maps rely on proprietary models that can no longer be legally obtained, most non-BAR models kinda suck, etc)
* sc2 arcade actually has far better modding in many areas (asset pool, missions, editor, built-in GUI...) and some that aren't even considered modding over there and taken for granted (like having decent melee unit support). Maybe …
> Add a "why choose Recoil" guide

- rts/System/creg/STL_Variant.h
* subtype serialisation is read/write agnostic
* the set function now actually responsible for setting
> Slightly more elegant variadic template bullshit

- rts/Rml/Backends/RmlUi_Backend.cpp
- rts/Rml/Backends/RmlUi_Backend.h
- rts/Rml/Backends/RmlUi_Platform_SDL.cpp
- rts/Rml/Backends/RmlUi_Platform_SDL.h
- rts/Rml/RmlInputReceiver.h
- rts/lib/RmlSolLua/src/RmlSolLua.cpp
- rts/lib/RmlSolLua/src/RmlSolLua.h
- rts/lib/RmlSolLua/src/TranslationTable.h
- rts/lib/RmlSolLua/src/bind/Context.cpp
- rts/lib/RmlSolLua/src/bind/DataModel.cpp
- rts/lib/RmlSolLua/src/bind/Element.cpp
- rts/lib/RmlSolLua/src/bind/Global.cpp
- rts/lib/RmlSolLua/src/bind/bind.h
- rts/lib/RmlSolLua/src/plugin/SolLuaDataModel.cpp
- rts/lib/RmlSolLua/src/plugin/SolLuaDocument.h
- rts/lib/RmlSolLua/src/plugin/SolLuaPlugin.h
fix for chobby mouse events
better lua datamodel binding
translation table
logging integration
correct cursor image changing
Still need to fix sdl_key* event handling
Also data model binding is only 1 level deep, need to add recursion
> more Rmlui

- rts/Game/Game.cpp
- rts/Map/SMF/SMFRenderState.cpp
- rts/Rendering/ShadowHandler.cpp
- rts/Rendering/WorldDrawer.cpp
Likely to fix https://github.com/beyond-all-reason/spring/issues/1145
> Keep shadows textures always on.

- rts/Game/UI/MiniMap.cpp
- rts/Rendering/Env/BumpWater.cpp
- rts/Rendering/Env/Particles/ProjectileDrawer.cpp
- rts/Rendering/ShadowHandler.cpp
- rts/Rendering/WorldDrawer.cpp
- rts/Sim/Misc/LosHandler.cpp
- rts/Sim/Projectiles/ProjectileHandler.cpp
- rts/Sim/Units/Scripts/UnitScriptEngine.cpp
- rts/Sim/Units/UnitHandler.cpp
To help get a better picture of sim and draw loads. 
Note that these additions dont spam zones, usually only marked only once per sim or draw frame.
> Add tracy zones to previously unmarked areas

- rts/Rendering/DebugColVolDrawer.cpp
> Add selection volumes to `/debugcolvol`

- rts/Rendering/Env/Particles/ProjectileDrawer.cpp
- rts/Rendering/Env/Particles/ProjectileDrawer.h
Partial fix for https://github.com/beyond-all-reason/spring/issues/1202
> MT check if a modelless projectiles should be drawn. 

- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaSyncedRead.h
> Add `Spring.GetTeamMaxUnits()`

- rts/lib/lua/include/lua.h
Standard way to let people discover the actual version on their own.
> Make Lua `_VERSION` more specific

- rts/builds/dedicated/CMakeLists.txt
- rts/lib/headlessStubs/CMakeLists.txt
- tools/DemoTool/CMakeLists.txt
- tools/dirchange/CMakeLists.txt
> Fix missing file extensions that modern cmake expect from source files.

- rts/Sim/Units/Scripts/UnitScript.cpp
Fixes most of the issues seen in https://github.com/beyond-all-reason/spring/issues/1269
> Add some robustness into SFX_FIRE_WEAPON targetting implementation. 

- rts/Sim/Units/Scripts/UnitScript.cpp
- rts/Sim/Units/Scripts/UnitScript.h
- rts/Sim/Units/Scripts/UnitScriptEngine.cpp
- rts/Sim/Units/Scripts/UnitScriptEngine.h
Still undecided if not setting `currentScript` during the `ImplTickMT()` is not critical.
> Small cleaning pass

- rts/Lua/LuaSyncedRead.cpp
> `Spring.GetUnitWorkerTask` works on factories

- rts/System/FileSystem/ArchiveScanner.cpp
- rts/System/FileSystem/DataDirLocater.cpp
- rts/System/FileSystem/DataDirLocater.h
It may be useful to have an option for multiple additional data folders
(I needed a few myself to organize my stuff better)
> Multiple SpringDataRoot

- rts/Lua/LuaSyncedCtrl.cpp
Follow up of https://discord.com/channels/278805140708786177/911790552687730689/1216600830254383164 .
> Fix Incorrect SetUnitSensorRadius Documentation

- rts/Rml/Backends/RmlUi_Backend.cpp
- rts/Rml/Backends/RmlUi_Backend.h
- rts/Rml/SolLua/bind/Global.cpp
> Rmlui/multi context handling improvements + debugger hook

- rts/Sim/Weapons/WeaponDef.cpp
> Weapondef docs

- rts/Sim/MoveTypes/GroundMoveType.cpp
Fixes https://github.com/beyond-all-reason/spring/issues/1469
> New path means we are not necessarily at the end of the path anymore.

- rts/Game/Game.cpp
- rts/Sim/Ecs/SaveLoadUtils.cpp
- rts/Sim/MoveTypes/Systems/UnitTrapCheckSystem.cpp
- rts/System/Ecs/EcsMain.h
- rts/System/creg/SerializeLuaState.cpp
- rts/lib/lua/src/lapi.cpp
- rts/lib/lua/src/lauxlib.cpp
- rts/lib/lua/src/lcode.cpp
- rts/lib/lua/src/ldebug.h
- rts/lib/lua/src/ldo.cpp
- rts/lib/lua/src/lfunc.cpp
- rts/lib/lua/src/lfunc.h
- rts/lib/lua/src/lgc.cpp
- rts/lib/lua/src/lgc.h
- rts/lib/lua/src/llex.cpp
- rts/lib/lua/src/llex.h
- rts/lib/lua/src/llimits.h
- rts/lib/lua/src/lmem.h
- rts/lib/lua/src/loadlib.cpp
- rts/lib/lua/src/lobject.cpp
- rts/lib/lua/src/lobject.h
- rts/lib/lua/src/lopcodes.h
- rts/lib/lua/src/lparser.cpp
- rts/lib/lua/src/lstate.cpp
- rts/lib/lua/src/lstate.h
- rts/lib/lua/src/lstring.cpp
- rts/lib/lua/src/ltable.cpp
- rts/lib/lua/src/lzio.h
Fixes https://github.com/beyond-all-reason/spring/issues/1425
lua overally generic macros renamed to avoid clashes with EnTT and possibly clashes in future. The registry and cast macros were causing a huge problem with building.
> Fix game loading crash

- rts/Game/Game.cpp
Fixes https://github.com/beyond-all-reason/spring/issues/1406
> ensure timed-out client is disconnected so they can't cause desyncs.

- rts/Sim/Units/CommandAI/BuilderCAI.cpp
Fixes https://github.com/beyond-all-reason/spring/issues/1428
> Fix bugger off check when placing long buildings

- rts/System/Log/ConsoleSink.cpp
- rts/System/Log/ConsoleSink.h
- rts/System/SpringApp.h
Fixes https://github.com/beyond-all-reason/spring/issues/683
> delay console print sink to avoid unwanted messages sent to console.

- rts/Sim/MoveTypes/GroundMoveType.cpp
Fixes: https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2799
> Stop override of units last move goal position.

- doc/site/articles/wupget-best-practices.markdown
> Add a basic article on wupget best practices

- rts/Sim/Path/HAPFS/PathManager.cpp
- rts/Sim/Path/HAPFS/PathManager.h
... to avoid game-impacting route disagreements.
> Avoid HAPFS mixing med and low paths 

- rts/Game/Game.cpp
- rts/Sim/Misc/ModInfo.cpp
- rts/Sim/Misc/ModInfo.h
Add mod rules to allow smooth mesh to be configured.
> Add mod rules to allow smooth mesh parameters to be changed.

- test/CMakeLists.txt
- test/engine/Sim/Misc/testQuadField.cpp
- test/engine/System/Misc/RectangleOverlapHandler.cpp
Not sure if I'm missing something, but it looks like several tests don't build.
A couple look like they have outright compile errors. (Like the engine code was updated, but the tests were not).
Another couple look to be missing dependencies on smmalloc.
I built on Linux using
```
mkdir build
cd build
cmake 	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O3 -g -DNDEBUG -fdiagnostics-color=always" \
-DCMAKE_C_FLAGS_RELWITHDEBINFO="-O3 -g -DNDEBUG -fdiagnostics-color=always" \
-DCMAKE_BUILD_TYPE=RELWITHDEBINFO \
-DAI_TYPES=NATIVE \
-DINSTALL_PORTABLE=ON \
-DCMAKE_USE_RELATIVE_PATHS:BOOL=1 \
-DBINDIR:PATH=./ \
-DLIBDIR:PATH=./ \
-DDATADIR:PATH=./ \
-DCMAKE_INSTALL_PREFIX="$(pwd)/install" \
-G Ninja \
..
cd ..
ninja -C build tests
ninja -C build test
```
> Fix some broken tests.

- rts/Game/UI/EndGameBox.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Sim/Features/Feature.cpp
- rts/Sim/Misc/Team.cpp
- rts/Sim/Misc/Team.h
- rts/Sim/Misc/TeamStatistics.cpp
- rts/Sim/Misc/TeamStatistics.h
- rts/Sim/Units/Unit.cpp
- rts/Sim/Units/Unit.h
- tools/DemoTool/DemoTool.cpp
- tools/DemoTool/StringSerializer.h
Track reclaim data and expose it in GetTeamStatsHistory().
> Add reclaim data to TeamStatistics

- rts/Game/UI/EndGameBox.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Sim/Features/Feature.cpp
- rts/Sim/Misc/Team.cpp
- rts/Sim/Misc/Team.h
- rts/Sim/Misc/TeamStatistics.cpp
- rts/Sim/Misc/TeamStatistics.h
- rts/Sim/Units/Unit.cpp
- rts/Sim/Units/Unit.h
- tools/DemoTool/DemoTool.cpp
- tools/DemoTool/StringSerializer.h
Reverts beyond-all-reason/spring#1312
> Revert "Add reclaim data to TeamStatistics"

- doc/changelog.txt
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedCtrl.h
- rts/Sim/Misc/SmoothHeightMesh.h
Fixes https://github.com/beyond-all-reason/spring/issues/635
> Allow games to trigger an immediate full rebuild of the smooth mesh.

- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaSyncedRead.h
> Added GetUnitCosts

- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaSyncedRead.h
> Add Spring.GetTeamDamageStats

- rts/Rml/Backends/RmlUi_Renderer_GL3_Recoil.cpp
- rts/Rml/Backends/RmlUi_Renderer_GL3_Recoil.h
with the official release of 6.0- it's time to update to that tag
also some porting/copying/blahing of some updates made to the RmlUi GL3 backend files to our modified versions of those
> Rmlui integration 6.0 released

- doc/site/changelogs/running-changelog.markdown
- rts/Lua/LuaConstEngine.cpp
1) requires #1668
2) there are some FIXMEs for the rmlUI part. @ChrisFloofyKitsune and/or @loveridge feel free to amend
> BAR105 changelog++

- rts/Rendering/Env/Decals/GroundDecalHandler.cpp
10s means 10s, not 10s times some arbitrary springsettings mult
> Fix scar TTL tags

- rts/Game/UI/KeySet.cpp
- rts/Rendering/Models/AssParser.cpp
- rts/System/Platform/Linux/CrashHandler.cpp
Self-documenting and more optimal.
> `string::find == 0` → `starts_with`

- doc/site/articles/ceg-operators.markdown
I've discovered the amazing hidden power of the `m` and `k` operators.
Also miscellaneous improvements to the article while I'm at it.
> Expand the CEG operators article

- cont/base/springcontent/LuaGadgets/gadgets.lua
- rts/ExternalAI/EngineOutHandler.cpp
- rts/ExternalAI/EngineOutHandler.h
- rts/ExternalAI/Interface/AISEvents.h
- rts/ExternalAI/SkirmishAIWrapper.cpp
- rts/ExternalAI/SkirmishAIWrapper.h
- rts/Game/SyncedGameCommands.cpp
- rts/Lua/LuaConstGame.cpp
- rts/Lua/LuaHandle.cpp
- rts/Lua/LuaHandle.h
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Sim/Misc/LosHandler.cpp
- rts/Sim/Misc/LosHandler.h
- rts/Sim/MoveTypes/HoverAirMoveType.cpp
- rts/Sim/MoveTypes/StrafeAirMoveType.cpp
- rts/Sim/MoveTypes/Systems/GeneralMoveSystem.cpp
- rts/Sim/MoveTypes/Systems/GroundMoveSystem.cpp
- rts/Sim/Objects/SolidObject.h
- rts/Sim/Units/Scripts/UnitScript.cpp
- rts/Sim/Units/Unit.cpp
- rts/Sim/Units/Unit.h
- rts/Sim/Units/UnitTypes/Factory.cpp
- rts/Sim/Units/UnitTypes/Factory.h
- rts/System/EventClient.h
- rts/System/EventHandler.h
> Add reclaimer to unitdestroyed

- rts/Lua/LuaMathExtra.cpp
- rts/Lua/LuaMathExtra.h
Trying to implement #1628 for @sprunk
> Implement Normalize_Vector

- rts/Game/Game.cpp
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Map/MapInfo.cpp
- rts/Net/GameServer.cpp
- rts/Net/Protocol/NetProtocol.cpp
- rts/Sim/Misc/GlobalConstants.h
- rts/Sim/Units/Unit.cpp
- rts/Sim/Units/UnitDef.cpp
- rts/Sim/Units/UnitTypes/Builder.cpp
- rts/Sim/Weapons/PlasmaRepulser.cpp
- rts/Sim/Weapons/WeaponDef.cpp
It's commonly used, but slightly tricky because it requires a cast to float.
> Add a named constant for 1/GAME_SPEED

- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaWeaponDefs.cpp
- rts/Sim/Weapons/Weapon.cpp
- rts/Sim/Weapons/Weapon.h
- rts/Sim/Weapons/WeaponDef.cpp
- rts/Sim/Weapons/WeaponDef.h
- rts/Sim/Weapons/WeaponLoader.cpp
Delay before the firing and the first projectile
> Add weapon def tag, `windup`

- doc/changelog.txt
- rts/Lua/LuaHandle.cpp
- rts/Lua/LuaHandle.h
- rts/Rendering/Env/Particles/ProjectileDrawer.cpp
- rts/System/EventClient.h
- rts/System/EventHandler.cpp
- rts/System/EventHandler.h
https://github.com/beyond-all-reason/spring/issues/1547
> Add booleans for the different phases of DrawWorldPreParticles callin

- rts/Lua/LuaWeaponDefs.cpp
One of those two PRs should ideally have been updated after the other was merged but things happened too fast.
> Apply the #1595 change to code from #1581

- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaUtils.h
Attempting to fix #1530 
CC @sprunk Let me know if I did something wrong in this PR
> Adding name constants for LuaSyncedCtrl.cpp and LuaSyncedRead.cpp

- rts/Game/TraceRay.cpp
- rts/Map/Ground.cpp
- rts/Map/Ground.h
- rts/Rendering/CommandDrawer.cpp
- rts/Sim/MoveTypes/HoverAirMoveType.cpp
- rts/Sim/MoveTypes/MoveMath/MoveMath.cpp
- rts/Sim/MoveTypes/StrafeAirMoveType.cpp
- rts/Sim/Objects/SolidObject.cpp
- rts/Sim/Projectiles/ProjectileHandler.cpp
- rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.cpp
The goal of this PR is to contribute somewhat to #1445. I only spent a couple hours on this (and a good bit of that just getting a dev environment set up to compile and test the changes).
I'm not familiar enough with the project to be anywhere near confident I got all the places I needed, so my goal isn't to be 100% comprehensive here. However, if there's any spots reviews know of that this change is needed that I missed I'd be more than happy to add those in here too.
None yet, but it does compile 😅
If anyone has any ideas on good ways to test these things, I'm all ears. I was thinking of setting the constant to something else that would create a noticeable change in the game. It might be hard to tell if a broken thing is broken from something I added but shouldn't have, or a place I …
> Look up water level instead of hard coding 0

- rts/Sim/Misc/ModInfo.cpp
Everything now uses the pattern where the default is set in Reset, and then the current value is passed as a fallback default.
No actual logic change.
> Modrule reading: set defaults consistently internally

- .gitignore
- docker-build/build.cmd
> Add Windows build script

- rts/lib/CMakeLists.txt
> force RMLUI_TRACY_CONFIGURATION to fix generate issues with tracy

- rts/System/FileSystem/Archives/SevenZipArchive.cpp
- rts/System/FileSystem/FileSystemAbstraction.cpp
- rts/System/Platform/Misc.cpp
- rts/System/Platform/Misc.h
fixes https://github.com/beyond-all-reason/spring/issues/725
> Switch over to WinAPI to get the date of file modification.

- rts/Game/GameHelper.cpp
- rts/Game/UI/MiniMap.cpp
- rts/Rendering/Env/Particles/ProjectileDrawer.cpp
- rts/Sim/Projectiles/ProjectileHandler.cpp
- rts/Sim/Units/UnitHandler.cpp
Fixed the previous PR where I incorrectely pushed to an already merged branch. https://github.com/beyond-all-reason/spring/pull/1172
> Tracy zones2 Add further once-per-frame zones, colorize top-level zones consistently

- rts/ExternalAI/SSkirmishAICallbackImpl.cpp
Also makes it handle more resources in the future.
> Reduce copy-paste in skirmish AI resource interface implementation

- cont/LuaUI/widgets.lua
> Fix `widgetHandler:FontsChanged`

- rts/Game/GameVersion.cpp
- rts/System/FileSystem/ArchiveScanner.cpp
- rts/System/FileSystem/ArchiveScanner.h
- rts/System/FileSystem/FileSystem.cpp
- rts/System/FileSystem/FileSystem.h
- rts/System/VersionGenerated.h.template
- rts/build/cmake/UtilVersion.cmake
Enables desired MAJ.MIN.PATCH scheme, also removes annoying content re-caching on various version/branch changes.
> Preparation for the release

- rts/Sim/Objects/SolidObject.cpp
also update UpdateDirVectors, making it a tad faster (hopefully)
> Improve SetHeadingFromDirection for units traveling steep slopes

- rts/Game/Game.cpp
- rts/Game/GameHelper.cpp
- rts/Lua/LuaConstGame.cpp
- rts/Sim/Misc/GlobalConstants.h
And expose build grid resolution to Lua.
> Document some build square assumptions

- doc/site/index.markdown
> Updating website mentions of recoil users

- .github/workflows/bar-cdn-publish.yml
GitHub actions are annoying to test...
> Fix BAR release publish flow

- docker-build/scripts/02_configure.sh
Fixes #1922
I have no idea why this worked before lol
> Add  -fuse-ld=gold linker flags to v1 build

- rts/Sim/MoveTypes/HoverAirMoveType.cpp
-Fixes https://github.com/beyond-all-reason/spring/issues/1237
> Fix landed aircraft starting to fly after being EMP

- rts/Rendering/CMakeLists.txt
- rts/Rendering/Common/UpdateList.cpp
- rts/Rendering/Common/UpdateList.h
- rts/Rendering/Env/Decals/GroundDecalHandler.cpp
- rts/Rendering/Env/Decals/GroundDecalHandler.h
useful to keep track of what items got updated
> Another piece of valueable scrap from BAR-quat: UpdateList

- rts/Sim/Path/QTPFS/Node.cpp
- rts/Sim/Path/QTPFS/NodeLayer.cpp
- rts/Sim/Path/QTPFS/PathDefines.h
- rts/Sim/Path/QTPFS/PathManager.cpp
- rts/Sim/Path/QTPFS/PathThreads.h
Second attempt. First attempt was accepted, but we since found a bug. The bug has been fixed and now this change is put forward for remerging.
Fixes https://github.com/beyond-all-reason/spring/issues/1934
> Bar105 reduce qtpfs memory usage

- rts/Sim/MoveTypes/Components/MoveTypesComponents.h
- rts/Sim/MoveTypes/GroundMoveType.cpp
- rts/Sim/MoveTypes/Systems/GeneralMoveSystem.cpp
- rts/Sim/MoveTypes/Systems/GroundMoveSystem.cpp
Tidy up the ECS system save/load.
Fixes https://github.com/beyond-all-reason/spring/issues/1928
> ECS save/load system corrections

- rts/Game/GameSetup.cpp
- rts/Game/GameSetup.h
- rts/System/SpringApp.cpp
Maybe a solution for https://github.com/beyond-all-reason/spring/issues/965 needs further testing
> Add only-local command line option to force not opening a listening UDP socket

- rts/Lua/LuaFBOs.cpp
- rts/Lua/LuaFBOs.h
- rts/lib/headlessStubs/gladstub.cpp
Mostly so I can close https://github.com/beyond-all-reason/spring/pull/1807
> Implement gl.ClearAttachmentFBO() in a cleaner way

- .github/workflows/generate-lua-library.yml
- .github/workflows/publish-site.yml
- doc/site/lua-api.md
Tested on my fork, seems good.
> Include links to .cpp source in lua library and API docs

- rts/Lua/LuaSyncedCtrl.cpp
Note, this doesn't go into `master` but into #1864.
> Document an important caveat.

- rts/Lua/LuaSyncedCtrl.cpp
Fixes LDoc annotations introduced in #1864.
> LDoc -> LLS: Spring.SetUnitHealth

- rts/Lua/LuaConstEngine.cpp
- rts/Lua/LuaConstGame.cpp
- rts/Lua/library/Types.lua
> Add gameSpeed and textColorCodes to Engine

- rts/Sim/Path/QTPFS/Node.cpp
Fixes issue @6AKU66 found where several explosions in large flat metal maps tank performance.
> reduce map update costs in QTPFS

- rts/Rendering/Units/UnitDrawer.cpp
- rts/Rendering/Units/UnitDrawer.h
- rts/Rendering/Units/UnitDrawerData.cpp
- rts/Rendering/Units/UnitDrawerData.h
- Fix dead unit ghosts not drawing an icon
- https://github.com/beyond-all-reason/spring/issues/783
- https://github.com/beyond-all-reason/spring/issues/640
- Fixes leaking information about dead units with ghosts
- Split from https://github.com/beyond-all-reason/spring/pull/1831
> Add dead ghost icons

- rts/Lua/LuaFBOs.cpp
- rts/Lua/LuaFonts.cpp
- rts/Lua/LuaHandle.cpp
- rts/Lua/LuaHandleSynced.cpp
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaUnsyncedCtrl.cpp
- rts/Lua/LuaUnsyncedRead.cpp
- rts/Lua/LuaVBO.cpp
- rts/Lua/LuaVBOImpl.cpp
Just tidying and fixing a bunch of lua doc stuff.
> Lua docs: Various cleanup

- rts/Lua/LuaVFS.cpp
> Lua VFS cleanup

- rts/Lua/LuaVFS.cpp
More followup from https://github.com/beyond-all-reason/spring/pull/2063
Should probably add some CI checks for this 😅
> More VFS doc fixes

- rts/System/FileSystem/Archives/CMakeLists.txt
- rts/System/FileSystem/Archives/PoolArchive.cpp
- rts/lib/minizip/CMakeLists.txt
Fixes issues with sdz archives on Linux (the real root cause is yet to be found)
> Don't include rts/lib and minizip as consequence

- rts/Lua/LuaHandle.cpp
- rts/Lua/LuaUtils.cpp
- rts/Lua/library/Script.lua
> Document `Script`

- README.markdown
Folks try to find it looking into the readme and can't
> Improve engine site discoverability

- rts/Lua/LuaHandleSynced.cpp
- rts/Lua/LuaSyncedTable.cpp
> Document lua globals

- rts/Lua/LuaFBOs.cpp
- rts/Lua/LuaOpenGL.cpp
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaUnsyncedCtrl.cpp
> Fix various Lua types

- rts/Lua/LuaFBOs.cpp
> Fix FBO types some more

- doc/site/changelogs/changelog-2025-01-6.markdown
- doc/site/changelogs/changelog-2025-03.markdown
- doc/site/changelogs/running-changelog.markdown
There's two FIXMEs from @Beherith 's #1930 that I was unable to figure out.
https://github.com/beyond-all-reason/spring/blob/6229d37753aa987260a6d65a2939ceaa4faffeb6/doc/site/changelogs/changelog-2025-03.markdown#L96-L97
> Changelogs

- docker-build-v2/build.sh
I've been using Docker V2 scripts to compile Recoil on a laptop with only 8GB of RAM, and the compiler goes out of memory about halfway through due to using all cores (nproc).
Findings:
- manually reducing the number of used cores significantly alleviates memory usage
- there exists `CMAKE_BUILD_PARALLEL_LEVEL` which can be used to control this without having to pass native toolchain flags
- it's not a CMake flag, but an environment variable, so it needs to be set before invoking `cmake --build`
- introduce `-j | --jobs` parameter to `build.sh`, which allow user to specify number of concurrent processes when building
- value checked with regex for some semblance of type safety
- parameter sets `CMAKE_BUILD_PARALLEL_LEVEL` environment variable in the docker container
- not a breaking …
> Add jobs parameter to Docker Build V2

- rts/Lua/LuaMetalMap.cpp
- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedMoveCtrl.cpp
- rts/Lua/LuaVBOImpl.cpp
I didn't add much description because I don't really know what everything does, but the types are complete.
Closes #2093 
Closes #2107
> Document `LuaSyncedMoveCtrl` and `LuaMetalMap.cpp`

- rts/Lua/LuaOpenGL.cpp
- rts/Lua/LuaOpenGL.h
Closes #2077
Compiled and tested locally.
> Remove `LuaOpenGL::*GL4` methods

- rts/Rendering/Textures/Bitmap.cpp
https://github.com/beyond-all-reason/spring/issues/2100
> Partially fix excessive font outlines

- rts/Rml/Backends/RmlUi_Backend.cpp
- rts/Rml/CMakeLists.txt
- rts/Rml/SVG/ElementSVG.cpp
- rts/Rml/SVG/ElementSVG.h
- rts/Rml/SVG/SVGPlugin.cpp
- rts/Rml/SVG/SVGPlugin.h
- rts/lib/CMakeLists.txt
The plugin was expecting to be on the heap instead of static. I also renamed the namespace and class to distinguish the custom plugin from the official one
> Custom svg plugin - round 2

- rts/System/FileSystem/ArchiveScanner.cpp
- rts/System/FileSystem/Archives/BufferedArchive.cpp
- rts/System/FileSystem/Archives/DirArchive.cpp
- rts/System/FileSystem/Archives/IArchive.cpp
- rts/System/FileSystem/Archives/IArchive.h
- rts/System/FileSystem/Archives/PoolArchive.cpp
- rts/System/FileSystem/Archives/SevenZipArchive.cpp
- rts/System/FileSystem/Archives/SevenZipArchive.h
- rts/System/FileSystem/Archives/VirtualArchive.cpp
- rts/System/FileSystem/Archives/VirtualArchive.h
- rts/System/FileSystem/Archives/ZipArchive.cpp
- rts/System/FileSystem/Archives/ZipArchive.h
- rts/System/ScopedResource.h
- rts/System/Threading/AtomicFirstIndex.hpp
Fixes https://github.com/beyond-all-reason/spring/issues/2116
> Fix 7zip archive performance regression, optimize some other aspects of zip/7z archives multithreaded access

- doc/site/_authors/flozi.markdown
- doc/site/guides/Tools.markdown
A very rudimentary start to a Tools page for the guides section of the site
> Tools Guide for site

- rts/Lua/LuaSyncedRead.cpp
General cleanup and remove misleading description.
> Improve side spec lua docs

- rts/System/Platform/CpuTopology.h
- rts/System/Platform/Linux/CpuTopology.cpp
- rts/System/Platform/Win/CpuTopology.cpp
- rts/System/Threading/ThreadPool.cpp
Addresses the problem on Linux with BAR on the new CPU pinning.
> Bar105 new linux threading policy

- rts/Lua/LuaSyncedRead.cpp
- Fixes negative indexing at GetUnitCurrentCommand
- Fixes https://github.com/beyond-all-reason/spring/issues/2206
> Fix GetUnitCurrentCommand negative indexing.

- doc/site/articles/select-command.markdown
See https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2595
> Fix docs for the select command

- .github/workflows/publish-site.yml
Try to fix https://github.com/beyond-all-reason/RecoilEngine/actions/runs/14940110310/job/41975763861
> Bump emmylua_doc_cli to 0.7.2

- rts/Lua/LuaSyncedCtrl.cpp
> Fix lua docs for `*HeightMap`, `*OriginalHeightMap` and `*SmoothMap`

- CMakeLists.txt
- rts/CMakeLists.txt
Extract the fix here
https://github.com/beyond-all-reason/RecoilEngine/pull/2142
Lets remove the old behavior before we update cmake to 4.0.0 
https://github.com/beyond-all-reason/RecoilEngine/issues/405
> Fix issue #405

- rts/Net/AutohostInterface.cpp
-warnings in Net/AutohostInterface.cpp
> Warnings cleanup

- rts/Lua/LuaConstCMD.cpp
- Documented the wait commands
- These commands are quite obscure, but I think at least I got the base descriptions and accepted params right.
- Some seem to be mostly for unsynced execution, since they go through selectionHandler, maybe that should be documented somehow but not sure what to say there.
- Documentation can later be improved but at least its a start.
> Document the wait commands.

- rts/lib/lua/README_SPRING
- rts/lib/lua/src/ldo.cpp
- Remove bytecode loader
- Fixes: https://github.com/beyond-all-reason/RecoilEngine/issues/1575
> Lua loadstring: only accept normal code

- rts/Sim/Path/QTPFS/PathSearch.cpp
Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2129
> Fix bad goal performance spike

- cont/base/springcontent/LuaHandler/Utilities/actions.lua
Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2392
> fix(basecontent): Broken textaction

- rts/Lua/LuaConstGL.cpp
- rts/Lua/LuaOpenGL.cpp
Relates to https://github.com/beyond-all-reason/RecoilEngine/issues/2378
> docs(opengl): Note discrepancy between GL and gl

- cont/base/springcontent/LuaHandler/Utilities/actions.lua
- rts/Lua/LuaOpenGL.cpp
https://github.com/beyond-all-reason/RecoilEngine/issues/2378
Format is non optional so I removed all of the `?`
> Document gl.BindImageTexture parameters

- rts/Lua/LuaSyncedCtrl.cpp
Before merging, check if this is going to affect the site/docs rework PRs.
> Fix some docs.

- rts/Lua/LuaShaders.cpp
> Fix shaderparams docs

- rts/Rendering/Map/InfoTexture/Modern/AirLos.cpp
- rts/Rendering/Map/InfoTexture/Modern/AirLos.h
- rts/Rendering/Map/InfoTexture/Modern/Height.cpp
- rts/Rendering/Map/InfoTexture/Modern/Height.h
- rts/Rendering/Map/InfoTexture/Modern/Los.cpp
- rts/Rendering/Map/InfoTexture/Modern/Los.h
- rts/Rendering/Map/InfoTexture/Modern/Radar.cpp
- rts/Rendering/Map/InfoTexture/Modern/Radar.h
* Deprecate CModernInfoTexture::UpdateCPU, that was broken enough to question the need for repair vs just throwing it away
* Fix a typo that led to https://github.com/beyond-all-reason/RecoilEngine/issues/2462
> Infotex fixes

- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedCtrl.h
- rts/Lua/LuaSyncedRead.cpp
- rts/Lua/LuaSyncedRead.h
- Adds getters: Spring.GetFeatureFireTime and Spring.GetFeatureSmokeTime
- Adds setters: Spring.SetFeatureFireTime and Spring.SetFeatureSmokeTime
- Made these in seconds, but I think it also makes some things about behaviour a bit awkward to describe, since internally works in frames and its always going to return "frame time quants".
- Related to https://github.com/beyond-all-reason/RecoilEngine/pull/2435
> Lua methods to get/set fireTime/smokeTime for a feature.

- rts/Lua/LuaSyncedCtrl.cpp
- rts/Lua/LuaSyncedRead.cpp
The return value text was not being documented, missing type specs.
> docs: Adjust {Get,Set}UnitLosState docs

- rts/System/Sound/OpenAL/Sound.cpp
- Close the sdl sound before openal device
- Also remove check for device at RenderSDLSamples
- Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2382
- My hypothesis is this crashes because we're closing the openal device, but sdl can still be calling RenderSDLSamples from some thread, so it currently has a race condition where ALCdevice can be already closed, but pointer wasn't set to null yet.
- Closing the sdl device first should ensure its flushed and we get no more RenderSDLSamples calls.
- Unsure yet this is the good way to do it, but seems like it might be.
- Could be its better to close sdl device, then openal device, then close sdl sound completely
- Also could be its still better to leave the `dev != null` test there, since `RenderSDLSamples` also gets "registered" …
> Close SDL sound before openal.

- doc/site/content/docs/guides/rendering/making-shaders.md
Fix some inaccuracies.
@lhog : Please review this, because some stuff may still be missing/inaccurate.
> Fix shader docs

- rts/Sim/Weapons/BeamLaser.cpp
- rts/Sim/Weapons/LightningCannon.cpp
> Expose projectile ID in case of beam laser and lightning cannon

- rts/Lua/LuaSyncedCtrl.cpp
Fixes #2470
Merge when possible
> Making SetProjectileTarget error out on incorrect signature call

- rts/Game/UI/Groups/GroupHandler.cpp
- rts/Game/UI/Groups/GroupHandler.h
- rts/Game/UnsyncedGameCommands.cpp
- rts/System/StringUtil.h
Trying to implement the feature described in https://github.com/beyond-all-reason/RecoilEngine/issues/2580
> Add optional group focus action time argument
