beyond-all-reason/RecoilEngine

rts/Game/Game.cpp, rts/Game/UnsyncedGameCommands.cpp, rts/Rendering/UnitDrawer.cpp, rts/Rendering/UnitDrawer.h, rts/Rendering/WorldDrawer.cpp
Transition from solid unit to icon is much more smooth and fluent now. Different stages of the transition are all configurable.
There are 3 new configuration entries: UnitIconScale, UnitIconFadeStart and UnitIconFadeVanish, with handling "/setting x" commands.
=> New strategic icons behavior

rts/Rendering/UnitDrawer.cpp, rts/Rendering/UnitDrawer.h
- UnitIconsHideWithUI defaults to False;
- Always render unit models when icons are hidden;
- Show icons for ghosted buildings (scouted but no radar);
- Don't hide unit's model until icon is fully opaque;
- Some optimizations.
=> Some minor changes to icons

rts/Rendering/Env/Particles/ProjectileDrawer.cpp, rts/Rendering/GlobalRendering.cpp
Apparently 24-bit depth is the magic value for amdgpu.
https://github.com/beyond-all-reason/spring/issues/8
=> Fix amdHack that was broken by 149ea5c9476dc78cc6d05fafc5d3527c0e59997a

rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
Feature::GetResurrectDef() returns UnitDef if feature is resurrectable and nullptr otherwise.
Also added Feature::GetBuildingFacing() that returns facing, to provide similar functionality of LuaSyncedRead::GetFeatureResurrect.
=> [AI] Add Feature::GetResurrectDef()

rts/Game/UI/KeyBindings.cpp
This change allows for commands on a same keyset to fallback when different arguments are present, e.g.:
```
bind Shift+z enqueueunit armck 5
bind Shift+z enqueueunit corck 5
```
Currently the engine deduplicates by command instead.
=> Allow fallback for commands with different args

rts/Map/ReadMap.cpp, rts/Map/ReadMap.h
The problem was that building a structure could trigger a mid-cycle limits sweep of the height map which could miss the true high/low points on a map. This change checks for map changes at the start of a limit sweep to ensure that the whole map is checked for high/low points and not just a part of the map. This change will also detect if the map changes during a sweep and issue a following sweep, just in case the height map change occurred in a part of the map we had already checked in the current sweep.
=> Fixed intermittent issue with building at high places

doc/changelog.txt, rts/Game/UI/KeyBindings.cpp, rts/Game/UI/KeyBindings.h, rts/Lua/LuaIntro.cpp, rts/Lua/LuaMenu.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
With optional command prefix matcher argument
Before, the only way lua could read keybindings with full action data
was via GetKeyBindings, that requires a keyset argument.
This exposes all keybindings with full action data with an optional
argument to match on command prefix.
=> Add Spring.GetAllKeyBindings

doc/changelog.txt, rts/Game/UI/KeyBindings.cpp, rts/Game/UI/KeyBindings.h, rts/Lua/LuaIntro.cpp, rts/Lua/LuaMenu.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
Keep the API concise, the prefix matching is not essential for perf for
the use cases it would use anyways. Keybinding check would be done at
sparse callins or initialization
=> Allow empty argument to GetKeyBindings instead

rts/Sim/CMakeLists.txt, rts/Sim/MoveTypes/GroundMoveType.cpp, rts/Sim/MoveTypes/GroundMoveType.h, rts/Sim/MoveTypes/MoveType.h, rts/Sim/Path/TKPFS/PathEstimator.cpp, rts/Sim/Path/TKPFS/PathManager.cpp, rts/Sim/Path/TKPFS/PathManager.h, rts/Sim/Path/TKPFS/PathingState.cpp, rts/Sim/Path/TKPFS/PathingState.h, rts/Sim/Units/UnitHandler.cpp
Corrected temp checksum calculation so that it doesn't create a false negative at match start.
User and AI commands to units may result in pathing request that have to be processed immediately (not by SlowUpdate) - I have updated the MT Reqs to support this.
Improved utilization of workthreads for pathing requests, which significantly improves their performance.
Note: work has begun on splitting out code/data shared between Estimators in a PathingState class. This is ongoing effort.
=> Tarnished knight mt path requests

rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.cpp
…Prevents everliving zombie bouncy projectiles (Torpedoes at the very least)
Fixes https://github.com/beyond-all-reason/spring/issues/75
=> Fix to https://github.com/beyond-all-reason/spring/issues/75

rts/Sim/Projectiles/WeaponProjectiles/BeamLaserProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/EmgProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/ExplosiveProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/FireBallProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/FlameProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/LargeBeamLaserProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/LaserProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/LightningProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/MissileProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/StarburstProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/TorpedoProjectile.cpp
Added owner() instead of nullptr in most explGenHandler.GenExplosion calls, such that CEGs inherit teamID of calling projectile and therefore are visible as allied
Partially fixes https://github.com/beyond-all-reason/spring/issues/74
=> Fix to https://github.com/beyond-all-reason/spring/issues/74

rts/Game/GameHelper.cpp
This is about placing standalone units, like from ZK strider hub.
See ZK Athena for an example of current broken behaviour (has `floater` but is not buildable on water).
ZeroK-RTS/Zero-K#4014
Before the patch:
* neither `canSubmerge` nor `floater`: NOT buildable on water
* just `canSubmerge`, but not `floater`: buildable on water
* just `floater`, but not `canSubmerge`: NOT buildable on water
* both `floater` and `canSubmerge`: NOT buildable on water
After the patch:
* neither `canSubmerge` nor `floater`: NOT buildable on water
* just `canSubmerge`, but not `floater`: buildable on water
* just `floater`, but not `canSubmerge`: buildable on water
* both `floater` and `canSubmerge`: buildable on water
=> Fix depth check for non-fac seaplane buildability

rts/Sim/Units/CommandAI/BuilderCAI.cpp
BuildTest and Build positions are different.
This may cause stuck constructor:
```
-- known geo spot on Supreme Crossing V1
local bposx = 1100.000000
local bposz = 5860.000000
Spring.GiveOrderToUnit(unitID, -buildingDefID, { bposx, bposy, bposz, 0 }, {})
```
<= code will result in pictures above if geo spot position is not snapped to grid first.
PS. Frankly i'm not sure snapping at this place required at all: TestUnitBuildSquare is doing own snapping and Pos2BuildPos has own.
Hence `#if 1` => `#if 0` could be better
=> Fix build-position snapping

.gitmodules
There is no reference of AAI in **.gitmodules** so i couldn't update CircuitAI (or any other suubmod) without removing AAI (that is empty?)
=> Switch submodule spring/CircuitAI:master => rlcevg/CircuitAI:zk

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
Max depth controlled by MAX_CMD_RECURSION_DEPTH
=> Replace recursion flag from boolean to int

rts/Game/UnsyncedGameCommands.cpp
Added `setspeed` command to allow directly changing the game speed, rather than having to repeatedly send `speedup` and `slowdown` commands.
Chose `setspeed` because the other commands refer to "speed" and not "gamespeed": `setminspeed`, `setmaxspeed`.
`/setspeed n` where n is ignored if negative, zero, or not a number (`atof` coerces invalid values to 0.0), and is clamped to minimum and maximum game speeds.
=> setspeed command to set game speed directly

rts/Game/Game.cpp, rts/Map/ReadMap.cpp, rts/Map/ReadMap.h
Also fix height bounds changing if CalcHeightmapChecksum is called.
Note that this is a behaviour change - original height will now be the
height of the map in the file, and not the height in the beginning of the
game.
=> Move Preload event after lua is initialized.

rts/Game/Game.cpp, rts/Game/Game.h, rts/Game/UnsyncedGameCommands.cpp, rts/System/LoadSave/CregLoadSaveHandler.cpp, rts/System/LoadSave/CregLoadSaveHandler.h, rts/System/LoadSave/LoadSaveHandler.h, rts/System/LoadSave/LuaLoadSaveHandler.cpp, rts/System/LoadSave/LuaLoadSaveHandler.h, rts/System/creg/Serializer.cpp, rts/System/creg/Serializer.h
Geo spot is a Feature.
Features are loaded on `CGame::LoadLua(false, <any>)` that happens after EVENT_LOAD for AI, thus AI can't see crucial economy places on savegame load. Though it's technically possible to delay AI routines till 1st executed frame and lag it, i don't see why should it.
=> 'AI above all' load order

rts/Rendering/Textures/TexturesSet.h
I am using gcc 11.1 on arch linux. This file complained that it doesn't know ``size_t``, but only ``std::size_t``
=> fix compilation error in TexturesSet.h

rts/Game/UI/MouseHandler.cpp
Currently there are two instances of mouse centering on start, this PR removes both.
=> Remove mouse centering

doc/changelog.txt, rts/Sim/Weapons/WeaponDef.cpp
See #153 (tldr: the value is mistakenly capped at 10000%, so high we might as well not have a cap).
This is the alternative that just removes the limit. I slightly dislike it because I think it is cleaner for Lua gadgets to make their own customparam, which they can populate with the firestarter tag in unitdefs_post before it gets capped if they want to tie the two values together, but maybe somebody likes the lazy approach.
=> [ALT 2] Remove inconsequential firestarter weapondef tag limit

doc/changelog.txt, rts/System/FileSystem/ArchiveScanner.cpp
Dedicated server often doesn't have the content,
but this is fine since it just relays messages.
=> Archives: don't warn for empty server checksum

rts/Sim/Units/CommandAI/BuilderCAI.cpp
The CTRL modifier used to make area-reclaim eat up wrecks being rezzed.
But it is also (still) used to eat wrecks that aren't autoreclaimed in general.
Ideally these two would not be tied, but the META and META+CTRL modifiers
are already in use for other stuff. Rez seems usually preferable in major games
so maybe not leaving the option to absent-mindedly create a conflict is good.
You can still reclaim a wreck being rezzed by consciously giving a single-target command.
=> Area-reclaim: always ignore wrecks being rezzed

rts/Map/SMF/ROAM/Patch.cpp
Rotate the triangles in a square if their hypotenuse becomes shorter.
Fixes or lessens the issues with stretched triangles at sharp edges.
=> Updated map triangulation

rts/ExternalAI/EngineOutHandler.cpp, rts/ExternalAI/EngineOutHandler.h, rts/ExternalAI/Interface/AISEvents.h, rts/ExternalAI/SkirmishAIHandler.cpp, rts/ExternalAI/SkirmishAIHandler.h, rts/ExternalAI/SkirmishAIWrapper.cpp, rts/ExternalAI/SkirmishAIWrapper.h, rts/Game/Game.cpp, rts/Net/NetCommands.cpp
Draft. Requires BARb update.
Actions on savegame load.
* Original:
1) For each AI:
1.1) CreateAI, EVENT_INIT for specific AI.
1.2) SendUnitEvents (UnitFinished, and for enemies: UnitEnteredLos/Radar) to AI.
2) Load AI data, EVENT_LOAD for each AI.
* Proposed:
1) CreateAIs, EVENT_INIT for each AI.
2) Load AI data, EVENT_LOAD for each AI.
3) SendUnitEvents to AI if loadSupported != "yes".
* Alternative:
1) For each AI:
1.1) CreateAI, EVENT_INIT for specific AI.
1.2) Load AI data, EVENT_LOAD for specific AI.
1.3) SendUnitEvents to specific AI if loadSupported != "yes".
But "alternative" requires modification of AI save procedure and understanding why it saves GetAllSkirmishAIs() instead of only local AIs (for possible future multiplayer save/load?).
=> [AI] Savegame: aiInst.PostLoad() after load event

rts/Game/UnsyncedGameCommands.cpp, rts/Rendering/Screenshot.cpp, rts/Rendering/Screenshot.h, rts/Rendering/Textures/Bitmap.cpp, rts/Rendering/Textures/Bitmap.h
Given the possibility of artifacts in large JPEG screenshots, I thought the most obvious thing to do was to enable to manually tune the quality setting of the screenshot itself.
This patch simply adds a new (optional) parameter to the "\screenshot" in-game command: quality. This is supposed to be an integer in the range 1-99 (because that's what the DevIL library wants, otherwise it is ignored). Note that the quality setting does not affect png screenshots (you can still pass it but it won't do anything).
This patch additionally disables compression for the screenshots. I didn't feel it necessary to add a separate parameter for that.
Do note that there are similar calls to DevIL to save greyscale screenshots; I did not change those, as I'm unsure who calls them and why.
=> Enable manually setting JPEG screenshot quality

rts/Lua/LuaOpenGLUtils.cpp, rts/Lua/LuaOpenGLUtils.h, rts/Rendering/Textures/NamedTextures.cpp, rts/Rendering/Textures/NamedTextures.h
My only question being:
// do not enable cubemap samplers here (not
// needed for shaders, not wanted otherwise)
Why? It didnt break anything for me...
=> Enable 3D and cubemaps for luatextures

rts/Game/UI/Groups/GroupHandler.cpp, rts/Game/UnsyncedGameCommands.cpp
This is a fairly simple fix that adds an optional string parameter to be specified before the group number. This allows rebinding of the selection/deselection/toggle group commands.
It ideally fixes #246.
=> Extend the group command to accept an optional string parameter.

rts/Menu/LuaMenuController.cpp, rts/Menu/LuaMenuController.h
KeyPressedSC executes luaInputReceiver->KeyPressedSC, which will try normal execute of KeyPress and KeyPressSC for lua functions
=> Replace KeyPressed in LuaMenuController by KeyPressedSC

rts/Game/UnsyncedGameCommands.cpp
This commit replaces the trivially detectable undefined behavior of
dereferencing a nullptr to cause a crash with `std::abort()`.
The change is not exact, as `std::abort()` triggers a SIGABRT, while the
original behavior was to trigger a SIGSEGV. This was done for
simplicity.
Note that the final result doesn't change: a crash is still triggered,
and `CrashHandler` is called regardless, as it registers with all
possible signals in all platforms. Thus, the `CrashActionExecutor`'s
objective is achieved anyway: to cause a crash which logs the stack
trace.
=> Replace unportable UB dereference of nullptr with std::abort

rts/Game/Game.cpp, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h, rts/Map/ReadMap.cpp, rts/Map/ReadMap.h
Updated readmap to work correctly when Lua code changes the heightmap before the match starts.
Tested on Quicksilver with map_waterlevel set to 200 - restore command doesn't build a pillar to the sky as it has done in the past, the correct height maintained by restore command now.
Made map changes on the same setup by spawning and self-d coms. Made some restores to land - parts restored went to the expected height level. Left plenty of crater. Saved game and loaded to show that the map is reloaded with correct waterlevel and the terrain deformation is restored correctly. Also tried a restore command and the it worked as expected - as per prior to save/load cycle.
Test on Zero-K with a random map. Save/load, the map looked indentical without additional warping or changes. Any prior …
=> Fix for when pre-match heightmap is updated by Lua code

doc/changelog.txt, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
Perf/convenience so that I don't have to do `Set(Get() + deltaXP)`.
Possibly Add should be made available for other common functions that abuse the Set+Get pattern (in particular SetUnitHealth) but that is outside the scope of this patch.
=> Add `Spring.AddUnitExperience(unitID, deltaXP)`

CMakeLists.txt
It was added when c++11 was introduced 9 years ago but now without it it compiles fine. I'm using <random> in https://github.com/beyond-all-reason/pr-downloader/pull/9 and with that define set, compilation fails with
```
[ 46%] Linking CXX executable pr-downloader
/usr/include/c++/10/bits/random.h:192: error: undefined reference to 'double std::generate_canonical<double, 53ul, std::linear_congruential_engine<unsigned long, 16807ul, 0ul, 2147483647ul> >(std::linear_congruential_engine<unsigned long, 16807ul, 0ul, 2147483647ul>&)'
/usr/include/c++/10/bits/random.h:294: error: undefined reference to 'std::linear_congruential_engine<unsigned long, 16807ul, 0ul, 2147483647ul>::seed(unsigned long)'
/usr/include/c++/10/bits/random.h:294: error: undefined reference to …
```
=> Allow using <random> from c++ standard library.

doc/changelog.txt
=> Fix SDL TextInput documentation link in changelog

doc/changelog.txt, rts/Game/UI/KeyCodes.cpp, rts/Game/UI/ScanCodes.cpp
These values aren't available to Lua, since SDL1 only supports up to F15. Also it appears that due to a bug in SDL2, F13+ will only work with scancodes and not keycodes at this time. 
Keycode pairs have been added for bindings anyway, for when the SDL-internal fix is released.
=> F16-F24 scancode keybind support

rts/Rendering/GL/FixedPipelineState.h, rts/Rendering/GL/VertexArrayTypes.cpp
See the individual commits.
Overall there is also plenty of very interesting warning messages that seem (IMHO) very useful from clang, that are not present from gcc, like `spring/rts/Rendering/GL/FixedPipelineState.h:72:11: warning: binding reference member 'func' to stack allocated parameter 'func_' [-Wdangling-field]`.
=> Fix compilation under clang

rts/System/FileSystem/RapidHandler.cpp
There can be multiple domains from which the packages are being
downloaded, for example when additonal mirrors are used. This adds
support for picking from which domain version.gz files should be
used first.
=> Add option for rapid tag resolution domain preference order

rts/Game/Camera/SpringController.cpp
spring camera gets choppy when smoothing from gui_options widget is
activated as widget is continously calling CameraTransition from
SetCameraTarget function. as long as SpringCameraController does not
change the position of camera directly the animation remains smooth.
the camera will be updated by camera handler in the game loop instead.
=> fix choppy spring camera

rts/lib/headlessStubs/sdlstub.c
rect become const in 2.24 with commit [b085c18251bc0298b1a78a621025978702ca07f7](https://github.com/libsdl-org/SDL/commit/b085c18251bc0298b1a78a621025978702ca07f7) in the SDL repository.
=> Fix SDL stubs for version >=2.24

rts/Sim/MoveTypes/GroundMoveType.cpp, rts/Sim/MoveTypes/GroundMoveType.h, rts/Sim/MoveTypes/HoverAirMoveType.cpp, rts/Sim/MoveTypes/HoverAirMoveType.h, rts/Sim/MoveTypes/ScriptMoveType.cpp, rts/Sim/MoveTypes/ScriptMoveType.h, rts/Sim/MoveTypes/StaticMoveType.cpp, rts/Sim/MoveTypes/StaticMoveType.h, rts/Sim/MoveTypes/StrafeAirMoveType.cpp, rts/Sim/MoveTypes/StrafeAirMoveType.h, rts/Sim/Units/CommandAI/AirCAI.cpp, rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/CommandAI/CommandAI.cpp, rts/Sim/Units/CommandAI/CommandAI.h, rts/Sim/Units/CommandAI/FactoryCAI.cpp, rts/Sim/Units/CommandAI/MobileCAI.cpp, rts/Sim/Units/Scripts/CobInstance.cpp, rts/Sim/Units/Scripts/LuaUnitScript.cpp, rts/System/creg/Serializer.cpp, rts/System/creg/creg.cpp, rts/System/creg/creg.h, rts/System/creg/creg_cond.h
Checking alternative approach: feels like developing interface for containers that does placement-new (acts like factory) could be more intuitive thing for understanding and future re-use. Unless it adds additional overhead during main game loop, then it's no go.
=> Placement-new serialization of objects with container reference

rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.cpp, rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.h, rts/Rendering/Env/Particles/Classes/DirtProjectile.cpp, rts/Rendering/Env/Particles/Classes/DirtProjectile.h, rts/Rendering/Env/Particles/Classes/GenericParticleProjectile.cpp, rts/Rendering/Env/Particles/Classes/GenericParticleProjectile.h, rts/Rendering/Env/Particles/Classes/HeatCloudProjectile.cpp, rts/Rendering/Env/Particles/Classes/HeatCloudProjectile.h, rts/Rendering/Env/Particles/Classes/SimpleParticleSystem.cpp, rts/Rendering/Env/Particles/Classes/SimpleParticleSystem.h, rts/Rendering/Env/Particles/Classes/SmokeTrailProjectile.cpp, rts/Rendering/Env/Particles/Classes/SmokeTrailProjectile.h, rts/Rendering/GroundFlash.cpp, rts/Rendering/GroundFlash.h, rts/Rendering/Textures/TextureAtlas.cpp, rts/Rendering/Textures/TextureAtlas.h
Needs remake, can't initialize texture with `&CTextureAtlas::dummy`, so either have to add `PostLoad` to such classes, or convert pointer to embedded and save it - that requires special combination of x,y,z,w to consider it non-initialized.
Or consider serialization of CTextureAtlas - lifecycle container of AtlasedTexture.
=> Serialize AtlasedTexture* members

rts/Game/UI/KeyBindings.cpp, rts/Game/UI/KeyBindings.h
Ensure binding order is preserved when returning hotkeys filtered by action, this is helpful for game developers to know the order precedence.
=> GetActionHotkeys: Sort results by binding order

rts/Game/UI/KeyCodes.cpp, rts/Lua/LuaIntro.cpp, rts/Lua/LuaMenu.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
Retrieves the key on the user keyboard layout for a given scan symbol.
e.g.: Spring.GetKeyFromScanSymbol('sc_z') == 'y' // qwertz keylayout
=> Add GetKeyFromScanSymbol callout

doc/changelog.txt, rts/Game/UI/KeyCodes.cpp, rts/Lua/LuaIntro.cpp, rts/Lua/LuaMenu.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
Returns the keysymbol correspondent to the keycode received by the game when the scanCode represented by the scanSymbol is received. In other terms: receives the position on the keyboard and returns the key in spring keycode format (uikeys).
For example, on a qwertz keyboard (see https://kbdlayout.info/kbdgr for reference):
Spring.GetKeyFromScanSymbol('sc_z') => 'y'
Spring.GetKeyFromScanSymbol('sc_[') => 'ü'
=> Callouts: Add GetKeyFromScanSymbol(scanSymbol)

rts/Game/Camera/SpringController.cpp
bug present only when CamSpringLockCardinalDirections was enabled. to get actual horizontal camera rotation use GetAzimuth() which takes under consideration rotation snap to cardinal directions
also fixes #347
=> fix spring camera moving sideways when changing pitch

CMakeLists.txt
I don't consider this a proper fix, more like a patch until we find root cause.
=> Add -rdynamic back to linking as BARb AI shared library doesn't work properly without it.

rts/Game/Camera.cpp, rts/Game/Camera.h, rts/Game/UI/CursorIcons.cpp, rts/Game/UI/GuiHandler.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Rendering/Units/UnitDrawer.cpp, rts/Rendering/Units/UnitDrawerData.cpp
Translation has already been taken care of by glViewPort so when a viewPos offset is present it returns an inaccurate value
=> Camera: Fix wrong windowcoords when offset present, rename to viewportcoords

doc/changelog.txt, rts/Game/Camera.h, rts/Game/Camera/OverheadController.cpp, rts/Game/Camera/SpringController.cpp, rts/Game/UI/KeyBindings.cpp, rts/Game/UnsyncedGameCommands.cpp
Add movetilt and movereset for the previous hardcoded ctrl and alt bindings.
Fix movefast and moveslow not being respected for certain camera states (relying on hardcoded bindings instead)
=> Camera: Fix hardcoded reset and tilt bindings

doc/changelog.txt, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h, rts/Lua/LuaConstGame.cpp, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h, rts/Sim/Units/Unit.cpp
Whether reclaiming drains health.
For the "wireframe reverse build" unit reclaim method (since the "classic" method relies on health drain).
=> Add `reclaim.unitDrainHealth` modrule

rts/Lua/LuaSyncedCtrl.cpp
Just because there are at least 4 args doesn't mean that the 4th arg isn't nil, and ParseUnit errors if it is.
=> Fix #243 (nil attacker in `Spring.DestroyUnit`)

rts/System/Config/ConfigSource.cpp
Without that, when the config is:
```
KeyToBedeleted = 1
KeyZ = 1
```
when you read you get:
`comments = {'KeyToBedeleted': '# comment'}`
after you delete `KeyToBedeleted` and read file again *without* clearing `comments` variable, you end up with
`comments = {'KeyToBedeleted': '# comment', 'KeyZ': '# comment'}`
and when you write with this state, you duplicate comment.
=> Clear comments when reading setting to prevent duplicating comments

doc/changelog.txt, rts/Game/InMapDraw.cpp, rts/Game/UI/MiniMap.cpp, rts/Game/UI/MiniMap.h, rts/Game/UnsyncedGameCommands.cpp
Allows drawlabel events and adds a MiniMapCanDraw spring setting for allowing drawing/erasing lines with cursor over minimap
=> MiniMap: Allow drawable events over minimap

rts/System/Sound/ISound.cpp, rts/System/Sound/OpenAL/Sound.cpp
Fix wrong logic in alcIsExtensionPresent; fix audio device reconnect
What did not work before this patch:
* have a USB headset attached and start a game
* then unplugged it and replugged it
* a result was: the sound was gone forever
* also logging was not good, did not know if it was using UseSDLAudio or
not
FIX in this patch:
* using alcIsExtensionPresent we can now correctly identify that the
ALC_SOFT_loopback is available
* the sdlDeviceID is initialized with 0 instead of -1 so we don't
segfault. therefore we can make use of SDL audio as an intermediate
buffer to render audio to
* with UseSDLAudio = 1 (default) and the fixes above the audio devices
can now be reconnected and audio resumes **awesome**
* headless defaults to 0 for SDLAudio usage:
CONFIG(bool, UseSDLAudio).defaultValue( …
=> Fix wrong logic in alcIsExtensionPresent; fix audio device reconnect

rts/ExternalAI/AICallback.cpp
Currently under some un-investigated (or forgotten) conditions AI API functions may return array with -1 unit IDs. That forces AI-side to make redundant check, and it messes up number of actually returned units.
Affected functions:
```
skirmishAiCallback_getEnemyUnits,
skirmishAiCallback_getEnemyUnitsInRadarAndLos,
skirmishAiCallback_getEnemyUnitsIn,
skirmishAiCallback_getFriendlyUnits,
skirmishAiCallback_getFriendlyUnitsIn,
skirmishAiCallback_getNeutralUnits,
skirmishAiCallback_getNeutralUnitsIn
```
NB: Features doesn't suffer from same issue AFAIK.
And i don't know if `skirmishAiCallback_getTeamUnits` is affected, as usually it's not used, and current fix doesn't change its behaviour.
=> [AI] Filter out -1 unitIDs

rts/Game/UI/IKeys.h, rts/Game/UI/KeyBindings.cpp, rts/Game/UI/KeyCodes.cpp, rts/Game/UI/KeyCodes.h, rts/Game/UI/KeySet.cpp, rts/Game/UI/KeySet.h, rts/Game/UI/ScanCodes.cpp, rts/Game/UI/ScanCodes.h
Fix: #460 
Output looks like this now:
```
[KeyBindings] GetActions: codeChain="Ctrl+z" scanChain="Ctrl+sc_z" keyCode="0x07A" scanCode="sc_0x01D":
[KeyBindings] Action List:
[KeyBindings]    1.  action="select"  rawline="select AllMap+_InPrevSel+_ClearSelection_SelectAll+"  shortcut="Ctrl+sc_z"  index="165"
[KeyBindings]    2.  action="selectbox_same"  rawline="selectbox_same"  shortcut="Any+sc_z"  index="11"
[KeyBindings]    3.  action="gridmenu_key"  rawline="gridmenu_key 1 1"  shortcut="Any+sc_z"  index="27"
```
=> KeyBindings: Fix KeyDebug and IKeys inheritance

rts/Game/Camera/CameraController.h, rts/Game/Camera/DummyController.h, rts/Game/Camera/FPSController.cpp, rts/Game/Camera/FPSController.h, rts/Game/Camera/FreeController.h, rts/Game/Camera/OverheadController.cpp, rts/Game/Camera/OverheadController.h, rts/Game/Camera/OverviewController.h, rts/Game/Camera/RotOverheadController.h, rts/Game/Camera/SpringController.cpp, rts/Game/Camera/SpringController.h, rts/Game/UI/MiniMap.cpp, rts/Game/UI/MiniMap.h, rts/Game/UI/MouseHandler.cpp, rts/Game/UI/MouseHandler.h
When cursor in minimap refers to a point outside current camera view, move to it. Otherwise perform identical mousewheel at referred point for current camera.
=> MiniMap: Respond to mousewheel events

cont/LuaUI/actions.lua, cont/LuaUI/main.lua, cont/LuaUI/widgets.lua, cont/base/springcontent/LuaHandler/Utilities/actions.lua, cont/base/springcontent/LuaHandler/Utilities/specialCallinHandlers.lua, doc/changelog.txt, rts/Game/Game.cpp, rts/Game/Game.h, rts/Game/UI/GuiHandler.cpp, rts/Lua/LuaHandle.cpp
This change:
- Avoids rebuilding actionList 3 times per keypress on the worst scenarios
- Fixes KeyChains for all engine-defined actions
- Allows games to handle KeyChains in lua actions
=> Avoid rebuilding actionlists, fix keychains

AI/Interfaces/C/src/Interface.cpp, AI/Interfaces/Java/bin/jni_wrappCallback.awk, AI/Interfaces/Java/src/main/native/InterfaceExport.c, AI/Interfaces/Java/src/main/native/JavaBridge.c, AI/Skirmish/NullJavaAI/src/nulljavaai/NullJavaAI.java, AI/Skirmish/NullOOJavaAI/src/main/java/nulloojavaai/NullOOJavaAI.java, AI/Wrappers/CUtils/bin/common.awk, AI/Wrappers/Cpp/CMakeLists.txt, AI/Wrappers/JavaOO/CMakeLists.txt, AI/Wrappers/LegacyCpp/AIAICallback.cpp, rts/ExternalAI/AILegacySupport.h, rts/ExternalAI/Interface/AISCommands.h, rts/ExternalAI/Interface/SAIInterfaceCallback.h, rts/ExternalAI/Interface/SSkirmishAICallback.h, rts/ExternalAI/SAIInterfaceCallbackImpl.cpp, rts/ExternalAI/SAIInterfaceCallbackImpl.h, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/ExternalAI/SSkirmishAICallbackImpl.h
Delete dangling declarations:
```
EXPORT(const char*      ) skirmishAiCallback_FeatureDef_getDeathFeature(int skirmishAIId, int featureDefId);
EXPORT(bool             ) skirmishAiCallback_UnitDef_isSquareResourceExtractor(int skirmishAIId, int unitDefId, int resourceId);
EXPORT(const char*      ) skirmishAiCallback_UnitDef_getType(int skirmishAIId, int unitDefId);
EXPORT(float            ) skirmishAiCallback_UnitDef_getDrag(int skirmishAIId, int unitDefId);
EXPORT(int              ) skirmishAiCallback_UnitDef_getBuildAngle(int skirmishAIId, int unitDefId);
EXPORT(bool             ) skirmishAiCallback_UnitDef_isLeaveTracks(int skirmishAIId, int unitDefId);
EXPORT(float            ) skirmishAiCallback_UnitDef_getTrackWidth(int skirmishAIId, int unitDefId);
EXPORT(float            ) …
```
=> [AI] API: Remove dead code, duplicates and memory leaks

doc/changelog.txt, rts/Sim/Units/UnitTypes/Builder.cpp
Currently the 5% overrides whatever gets set in UnitCreated, requiring any changes to get queued until the next frame. It's also arbitrary.
Games can easily replicate the old behaviour:
```lua
function gadget:UnitCreated(unitID, unitDefID, teamID, builderID)
if builderID and Spring.GetUnitCurrentCommand(builderID) == CMD.RESURRECT then
Spring.SetUnitHealth(unitID, Spring.GetUnitHealth(unitID) * 0.05)
end
end
```
=> Resurrect: don't set health to 5%

rts/Game/Camera.cpp, rts/Game/UI/InputReceiver.h, rts/Game/UI/MiniMap.cpp, rts/Game/UI/MiniMap.h, rts/Game/UI/MouseHandler.cpp, rts/Game/UI/MouseHandler.h, rts/Lua/LuaUnsyncedRead.cpp, rts/Rendering/GlobalRendering.cpp, rts/Rendering/GlobalRendering.h, rts/Rendering/Screenshot.cpp, rts/Rendering/UniformConstants.cpp, rts/System/Input/MouseInput.cpp, rts/System/SpringApp.cpp, rts/lib/headlessStubs/sdlstub.c
When viewport geometry is updated:
- Run through all displays currently connected
- Intersect their screen rectangles with the application windows
rectangle
- Sort the intersections left to right and make positions relative to
each other
- If DualScreenModeMiniMapOnLeft is enabled use the leftmost
intersection as the dualView, otherwise use the rightmost one. Use the
other screens as the main view
- Extract PosX, PosY, SizeX, SizeY and WindowOffsetY for dual and view from
the intersections in the form of: viewPosX, dualViewPosX, ..., and so on
If view is offset from bottom of window it has a positive
PosY, same if offset from left of window for PosX.
If view is offset from top of the window it has a positive
WindowOffsetY.
For GL coordinates:
Origin starts at bottom left of main view and …
=> DualScreenMode: Use separate display for dual view

doc/changelog.txt, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Convenience functions for getting the allyTeamID. Interfaces to get these values already existed, but were bad. Compare:
```lua
-- ugly
local _, _, _, _, _, allyTeamID = Spring.GetTeamInfo(teamID)
foo(allyTeamID)
-- less performant, somewhat magic
foo(select(6, Spring.GetTeamInfo(teamID)))
-- nice new possibility
foo(Spring.GetTeamAllyTeamID(teamID))
```
Similar for projectiles (you could get the teamID from `Spring.GetProjectileTeamID` and then do the above).
=> Add `Spring.Get{Team,Projectile}AllyTeamID`

doc/changelog.txt, rts/Game/Game.cpp, rts/Game/UI/KeyBindings.cpp, rts/Game/UI/KeyBindings.h
Accept arguments and allow keyload/keyreload commands in uikeys. This allows players and games to use base uikeys files and keep changes minimal and scoped.
=> KeyBindings: Allow key{,re}load commands in uikeys

rts/Game/Camera.cpp, rts/Game/Camera.h, rts/Game/UI/MiniMap.cpp, rts/Game/UI/MiniMap.h, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h, rts/Map/SMF/SMFGroundDrawer.cpp, rts/Rendering/Env/AdvWater.cpp, rts/Rendering/Env/BumpWater.cpp, rts/Rendering/Env/CubeMapHandler.cpp, rts/Rendering/Env/DynWater.cpp, rts/Rendering/Env/GrassDrawer.cpp, rts/Rendering/Env/Particles/ProjectileDrawer.cpp, rts/Rendering/GL/GeometryBuffer.cpp, rts/Rendering/GL/GeometryBuffer.h, rts/Rendering/GlobalRendering.cpp, rts/Rendering/GlobalRendering.h, rts/Rendering/LuaObjectDrawer.cpp, rts/Rendering/Map/InfoTexture/Modern/AirLos.cpp, rts/Rendering/Map/InfoTexture/Modern/Combiner.cpp, rts/Rendering/Map/InfoTexture/Modern/Height.cpp, rts/Rendering/Map/InfoTexture/Modern/Los.cpp, rts/Rendering/Map/InfoTexture/Modern/MetalExtraction.cpp, rts/Rendering/Map/InfoTexture/Modern/Path.cpp, rts/Rendering/Map/InfoTexture/Modern/Radar.cpp, rts/Rendering/ShadowHandler.cpp, rts/Rendering/WorldDrawer.cpp
- Listen to and adjust internal state on DualScreenMode and DualScreenMiniMapOnLeft changes
- Add DualScreenMiniMapAspectRatio = [1]|0 to keep the map aspect ratio instead of stretching along the dual view
- Add `vsx, vsy, vpx, vpy = Spring.GetDualViewGeometry()`
- Perform fixes for proper viewport on:
- GroundDrawer
- BumpWater
- ProjectileDrawer softening (copy source texture with proper geometry)
- LuaObjectDrawer (deferred pass on models)
=> DualScreenMode: Final adjustments

rts/Lua/LuaConstPlatform.cpp
So they dont have to be read-back from infolog.txt
=> Add physical and logical cpu core count to constplatform.

rts/Game/Game.cpp, rts/Game/UI/GuiHandler.cpp, rts/Game/UI/MouseHandler.cpp, rts/Game/UI/MouseHandler.h
Previously it was only updated during mouse events and on DrawSelectionBox.
On https://github.com/beyond-all-reason/spring/commit/c4027a21885537a00ad9fac5763b2c954e60200e we stopped updating cursor dir in DrawSelectionBox unless we wanted to draw it.
This PR makes sure mousedir is synced _before_ places in guihandler that need it (`GuiHandler::SetCursorIcon`/`EventClient::Update` listeners)  and after camera transitions are updated.
This PR includes a commit to further simplify `DrawSelectionBox`.
=> MouseHandler: Update mouse cursor dir

doc/changelog.txt, rts/ExternalAI/SSkirmishAICallbackImpl.cpp, rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaSyncedCtrl.cpp, rts/Rendering/Env/Particles/ProjectileDrawer.cpp, rts/Sim/Features/FeatureDefHandler.cpp, rts/Sim/Units/Scripts/CobInstance.cpp, rts/Sim/Units/UnitDefHandler.cpp, rts/Sim/Weapons/WeaponDefHandler.cpp, rts/Sim/Weapons/WeaponDefHandler.h
Too often game developers are unaware of this tricky behavior, as in Unit and Feature defs can be iterated via `for 1, #tablesize` while that's not the case with WeaponDefs.
=> WeaponDefs: Refactor indexing from 0 to 1-index

rts/Sim/Units/Unit.h, rts/Sim/Units/UnitTypes/ExtractorBuilding.cpp, rts/Sim/Units/UnitTypes/ExtractorBuilding.h
Metal Extractors are supposed to only work if they are activated, regardless of onoffable state. If a metal extractor is activated or deactivated, propagate this state to neighbor extractors properly.
Setting extraction during FinishedBuilding is replaced with Activate, since even not ononffable Extractors still require being activated to function (fixes a bug where metal and extraction map is corrupted due to this)
=> Mex: Fix activation and propagation to neighbors

rts/Sim/Units/Unit.cpp
When reclaim method is to gradually reclaim building, and the building being reclaimed from built state is a mex: update mex neighbors so they can extract the newly liberated metal.
=> Mex: Update neighbors when reclaimed in nanoframe

docker-build/scripts/00_setup.sh, docker-build/scripts/07_pack_build_artifacts.sh, docker-build/scripts/08_copy_to_publish_dir.sh, docker-build/scripts/build.sh
This allow to verify corruption in engine files after the engine is unpacked in the target installation directory. Also add -k option to build script to be able to easily create archives from local builds and test those scripts.
cc @Damgam
=> Add md5 checksum file to published engine archives

docker-build/scripts/02_configure.sh, rts/builds/headless/CMakeLists.txt, rts/builds/legacy/CMakeLists.txt, tools/CMakeLists.txt
The pkg-config based packages resoltion simplifies the configuration and allows for better automatic resolution of indirect dependencies of libraries needed for static linking.
=> Adapt pr-downloader cmake rewrite and switch to pkg-config for linux.

doc/SelectionKeys.md, doc/changelog.txt, rts/Game/UI/SelectionKeyHandler.cpp
Add Buildoptions, Cloak, Cloaked, Resurrect and Stealth selection filters. See `doc/SelectionKeys.md` for further details.
This should help players that need to do a lot of convoluted logic to make the selection they want or can't at all
=> feat(SelectionKeyHandler): Add more filters

doc/changelog.txt, rts/Lua/LuaConstGame.cpp
Since it is not the same as regular `squareSize` and not otherwise available.
=> Add `Game.metalMapSquareSize`

rts/Map/ReadMap.cpp, rts/Map/ReadMap.h, rts/Rendering/Env/BumpWater.cpp, rts/System/Misc/RectangleOverlapHandler.cpp, rts/System/Misc/RectangleOverlapHandler.h, rts/System/Rectangle.h
1) Do not run "mapDamage->RecalcArea(0, mapDims.mapx, 0, mapDims.mapy);" twice during the load
2) mapDamage->RecalcArea() run for a full map is no longer split in sub-rectangles and run with no pacing instead. This removes lags upon loading of a savegame for first N synced frames.
Respectively CReadMap::UpdateHeightMapSynced() lost "bool initialize" parameter, which instead is recreated based on the hgtMapRect coordinates
3) CRectangleOverlapHandler got new StageDedup() which removes duplicated rectangles
4) CRectangleOverlapHandler::StageSplitTooLarge() can now be turned off with CRectangleOverlapHandler::Process(bool noSplit = true), useful if splitting makes no sense (like in case of full map-wide update)
=> Partial (non-AI) fixes for https://github.com/beyond-all-reason/spring/issues/601

doc/site/Gemfile, doc/site/Gemfile.lock, doc/site/_config.yml, doc/site/_data/glossary.yml, doc/site/_sass/custom/custom.scss, doc/site/articles/team-terminology.markdown, doc/site/guides/glossary.markdown
Inspired by @sprunk article on team terminology I incorporated a glossary plugin.
You can reference glossary terms with `{% glossary Term %}`, see [in action](https://erikw.github.io/jekyll-glossary_tooltip/) and [documentation](https://github.com/erikw/jekyll-glossary_tooltip#tag-usage).
=> chore(site): Add glossary

rts/Game/SelectedUnitsAI.cpp
MSVC 17.4.5 crashes with internal compilation error when trying to build RelWithDebInfo:
```
25>C:\Users\Marek\Workspace\spring\rts\Game\SelectedUnitsAI.cpp(590): fatal error C1001: Internal compiler error.
25>(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
25> To work around this problem, try simplifying or changing the program near the locations listed above.
25>If possible please provide a repro here: https://developercommunity.visualstudio.com
25>Please choose the Technical Support command on the Visual C++
25> Help menu, or open the Technical Support help file for more information
25>  link!RaiseException()+0x6c
25>  link!RaiseException()+0x6c
25>  link!InvokeCompilerPassW()+0x87d1b
25>  link!InvokeCompilerPassW()+0xf86f1
25>
25>C:\Program …
```
=> Noop refactor to make MSVC compiler not crash with internal error

rts/Game/InMapDrawModel.cpp, rts/Game/InMapDrawModel.h, rts/Lua/LuaUnsyncedCtrl.cpp
Add 7th parameter `alwaysErase` to allow spectators to erase players markers when `onlyLocal`
Keep in mind it's already possible to erase all marks on map regardless if player generated or not, as a spectator, via clearmapmarks. We only allow targeted erasure for games that wish that to be possible.
Fixes #639 
cc @Ruwetuin
=> feat(UCtrl): Allow erase when local and spectator

rts/Game/GlobalUnsynced.h, rts/Net/NetCommands.cpp
~~There is a certain amount of CPU% always allocated to drawing. If 2 draw frames is the minimum, only the time needed in excess of the forced draw CPU% needs to be considered for adjusting the sim speed.~~ I realize it is needed because it represents the minimum about of work to be done and as min draw time (2 frames) grows then the ability to accurately assess the simulation load is reduced. However, we can put in a change to allow catch up to work harder. It won't stop the min 2 frames, but will allow sim to use upto 100% CPU rather than stop at 85%.
=> Allow simualtion to work harder to catch up.

rts/Game/Game.cpp, rts/Game/GameHelper.cpp, rts/Game/GameHelper.h, rts/Game/GameSetup.cpp, rts/Rendering/Map/InfoTexture/Modern/Path.cpp, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h, rts/Sim/Path/Default/PathDataTypes.h, rts/Sim/Path/TKPFS/PathConstants.h, rts/Sim/Path/TKPFS/PathManager.cpp, rts/Sim/Path/TKPFS/PathManager.h, rts/Sim/Path/TKPFS/PathingState.cpp, rts/Sim/Path/TKPFS/PathingState.h, rts/Sim/Weapons/Weapon.cpp
Few vertex re-calculations are done each frame to reduce the impact on a running game. However, evening at maximum settings, the code was not able to keep up with a game with several players. This impacted the ability of the path finder to find optimal or possible routes. It double expensive if the path system fails to find a route at a lower res because 1) it has to try more blocks just in case it can reach, and 2) it fails back to other level to find a route, which is effectively another path search in cost.
Increasing the rate at which low-res pathing information is recalculated fixes these problems, but also increases CPU stress. To mitigate this: 1) I've have prevented the updater from adding blocks to the update list that really don't need an update - the original code played it …
=> Bar105 tk smooth out pathing updates

doc/changelog.txt, rts/Sim/Projectiles/ProjectileHandler.cpp
Fixes a bug introduced in https://github.com/beyond-all-reason/spring/commit/83e08eeb5f05bbf936d75804d0a531ef0052c601 (104.0.1-1182)
Non-weapon projectiles, which includes piece projectiles (explosive shards flying from dying units), have 0 flags. So before that commit they just skipped all the conditions and went to the 'true' at the end of the function. After that commit they short-circuit to 'false'. This means they only collide with features and ground (which are handled in other functions).
=> Piece projectiles collide with units again

rts/Sim/Units/Scripts/CobEngine.cpp, rts/Sim/Units/Scripts/CobEngine.h, rts/Sim/Units/Scripts/CobInstance.cpp
Cleanup Cob threads killed by signal early.
Addressing https://github.com/beyond-all-reason/spring/issues/573
In the current implementation, when sleeping thread was killed by signal, it was destructed and removed from the CobInstance thread list only after it's sleep time was reached in CobEngine::WakeSleepingThreads which caused the list of threads for cob instance to quickly grow in size when sleep time was long. This was slowing down every operation that had to iterate over the list of active threads in the CobInstance and also used a lot of memory in the CobEngine.
This change initiates destruction of the thread killed by signal to an earlier point of time, on the next engine tick. All other operations that could reference that thread by id: like list of sleeping thread, are already …
=> Cleanup Cob threads killed by signal early.

rts/Game/Camera/OverviewController.cpp
overview camera settings should not be loaded from previous maps as it depends on the current map dimensions only.
steps to reproduce: 
1. start a game on flats and forests v2.1
2. go back to menu and start a game on eight horses map.
3. press tab to go to overview camera and see that the view is not centered
in this screenshot the camera cuts a bit from the top and leaves too much space below the map
=> fix overview camera not being centered in 2nd and subsequent games

AI/Interfaces/Java/bin/native_createCallbackFunctionImpls.awk, rts/Lua/LuaConstGame.cpp
Obsolete and long deprecated.
As far as I can tell, not used by any game.
No need to pollute code and, more importantly, docs.
=> Remove `Game.allowTeamColors`

rts/Lua/LuaSyncedCtrl.cpp
This function also accepts strings, and since numbers are implicitly convertible to strings it always used that path.
=> Fix `Spring.SetProjectileCEG(number)`

rts/Game/Camera.cpp
After planes reindexing some the plane parameters where not being correctly sent to CalcFrustumLine
=> fix: Frustum lines calculation

.github/workflows/release.yml
- Don't create new release marked as pre-release, create a draft release instead that can be made a release that is neither latest nor-prelease, or just one of them. Had to switch to other github action to be able to do it.
- Rename workflow accordingly.
- Add logic to pick the latest engine build action run as default to reduce unnecesary copy pasting of the run id.
- Fix workflow on the forked repositories.
=> Improve release creation workflow

doc/changelog.txt, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
Same max depth as other callouts
=> Allow shallow recursion in `Spring.TransferUnit`

doc/changelog.txt, rts/Lua/LuaUnsyncedCtrl.cpp
Previously required passing an explicit `-1`
=> Allow `Spring.SetActiveCommand(nil)` to cancel

rts/Game/UI/Groups/GroupHandler.cpp
Decouple select and focus parts of `group n`, the full equivalent for `group n` being:
```
bind n,n group  focus n
bind   n group select n
```
Previous behavior for `group n` still applies.
=> feat: Add select and focus group subactions

rts/Lua/LuaVBOImpl.cpp, rts/Rendering/Env/Particles/ProjectileDrawer.cpp, rts/Rendering/Env/Particles/ProjectileDrawer.h, rts/Sim/Projectiles/Projectile.h
Instead of inserting inside the vector we append to it and sort after all elements are ready. This minor optimization reduces cpu cycles by 2% in 1 min demo play of `/fightertest armbull armbull 400` on spring-headless. No intended functional changes.
Measurements taken with command `sudo perf record -g -p $(pgrep spring) -F 999 -a`.
Overall cpu usage by projectile drawer is still very high but it's possible to move some heuristics to `RenderProjectileCreated()` instead (e.g. check if projectile is within camera range - in GTA style with dynamic world loading) can significantly reduce further cpu usage. Or somehow avoid copying CProjectile pointers to new vector altogether.
Before:
After:
=> Optimize CProjectileDrawer::Draw

rts/Lua/LuaUnsyncedCtrl.cpp
Unnormalized vector causes glitchy shadows.
Also some minor adjacent documentation.
=> `Spring.SetSunDirection` normalizes vector

AI/Interfaces/C/src/Interface.cpp, CMakeLists.txt, rts/ExternalAI/AIInterfaceLibrary.cpp, rts/System/ConcurrentQueue.h, rts/System/ExportDefines.h
this removes checks and code related to support for the Intel C Compiler Classic. this compiler is officially deprecated by Intel, and is almost certainly not actually supported for building this engine. the last commits related to this compiler seem to be about 15 years old.
this (somewhat ironically) comes as part of my effort to improve platform support for the engine - cleaning out cruft makes it easier to rewrite what is left into a better state.
=> remove obsolete Intel C Compiler support

rts/Game/Camera/SpringController.cpp, rts/Game/Camera/SpringController.h
Fix zooming out when option CamSpringZoomOutFromMousePos is enabled. When camera is zoomed out maximally it will no longer move to the sides when mouse scrolled out.
Problem shown here https://streamable.com/5d0f4f . Sorry cursor is not visible but the lateral movement (when camera is already on the zoom limit) is undesired and uncontrollable.
After the fix the cursor always remains in the same place on the ground so it's possible to: 
1. scroll max out 
2. scroll back in to exactly the same point (if mouse wasn't moved)
=> SpringController - zoom out fix

rts/Net/NetCommands.cpp
* do not print alliances not involving the player. Whether to reveal it is for the game to decide. Keep the player-related ones for now though.
* fix allyTeamID being printed as a char. Realistically this was always non-printables.
=> Changes for the `/ally` feedback message

rts/Game/Camera/SpringController.cpp
when camera is temporarily pointed outside of the map (because of zooming into cursor) use previous cam pos ground height as heuristic for camera distance instead of average height of the map
fixes #627
=> SpringController - fix inconsistent zooming in on map border

rts/Game/Camera/SpringController.cpp, rts/Game/Camera/SpringController.h
Fixes #708
SpringController - track airmesh height instead of ground  for smooth horizontal camera movements
* add bool option CamSpringTrackMapHeight (default=1) to disable tracking the ground height entirely. with this option disabled camera can move up if it's below the ground of the hill but will never go back down by itself
=> Spring controller add smooth mesh and static camera height tracking

doc/changelog.txt, rts/Game/UI/PlayerRosterDrawer.cpp, rts/Lua/LuaConstGame.cpp, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h
New version of #175 with a simpler approach.
=> Add a way to disable `/info`

rts/System/CRC.h, rts/System/Platform/Misc.h, rts/System/Sound/ISound.h, rts/System/SpringHash.h, rts/System/SpringHashMap.hpp, rts/System/SpringHashSet.hpp, rts/System/StringHash.h, rts/System/StringUtil.h, rts/lib/luasocket/src/restrictions.cpp
Not sure how viable it's till we consider gcc13, maybe gcc14+ will do it other way.
gcc13 throws compilation error:
```
rts/lib/luasocket/src/restrictions.cpp:32:8: error: ‘uint8_t’ does not name a type
32 | static uint8_t luaSocketRestrictionsMem[sizeof(CLuaSocketRestrictions)];
|        ^~~~~~~
rts/lib/luasocket/src/restrictions.cpp:11:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
10 | #include "System/Config/ConfigHandler.h"
+++ |+#include <cstdint>
11 | 
```
Also next submodules require `#include <cstdint>`
```
tools/pr-downloader/src/FileSystem/FileSystem.h
AI/Skirmish/CircuitAI/src/circuit/util/MaskHandler.h
AI/Skirmish/BARb/src/circuit/util/MaskHandler.h
```
=> gcc13 compatibility

rts/Game/Camera/SpringController.cpp
CamSpringZoomOutFromMousePos is an option that changes zoom-out behavior to zoom from the cursor instead current camera focus.
Before the fix the camera wouldn't zoom out from the cursor if the cursor was pointed outside the map bounds.
Another improvement is to make the camera zoom closer to maximum limit if current translation vector is too big and new camera position would be past it (zooming out with shift modifier uses bigger vector than zooming just using the scroll).
=> Spring cam zoom out when cursor points out of map bounds

rts/lib/assimp/CMakeLists.txt
DataDirLocater depeneds on specific library names and with custom postfix it failed to find libsync.so (renamed to libsyncd.so) in current directory. bug prevents spring to start/recognize correct datadir. affects Debug builds only.
https://github.com/beyond-all-reason/spring/blob/cbeb010dca48d56f9ce6d474e309992d671db7bb/rts/System/FileSystem/DataDirLocater.cpp#L61
commented out entire section as assimp shouldn't change our global project settings.
=> disable debug library postfix

rts/Sim/Misc/GroundBlockingObjectMap.cpp, rts/System/ContainerUtil.h
VectorInsertUniqueSorted does not need to swap elements. lower_bound iterator already points to the right place and the rest of the vector is already sorted.
improvement over previous implementation from 83 to 60 assembly lines for trivial types.
=> simplify container util func VectorInsertUniqueSorted

doc/StartScriptFormat.txt, rts/Game/GameSetup.cpp, rts/Game/GameSetup.h, rts/Game/PreGame.cpp, rts/Net/GameServer.cpp, rts/builds/dedicated/main.cpp
By specifying a fixed seed, this fixes variance between benchmark runs of, say, fightertest. See thread in: https://discord.com/channels/549281623154229250/1122484736913318021
Credit to @Beherith for figuring out this was a seeding issue
Feel free to nitpick, so I can get a better idea of what's important to y'all.
=> feat: add fixedSeed param to GameSetup and use it to initialize RNG

rts/Lua/LuaOpenGLUtils.cpp, rts/Rendering/Textures/NamedTextures.cpp
Fix glTextureInfo returning zero z-size for 3D textures.
GL_CLAMP is outdated and deprecated, use GL_CLAMP_TO_EDGE instead
=> glTextureInfo fix & GL_CLAMP_TO_EDGE

cont/base/springcontent/LuaGadgets/system.lua, doc/changelog.txt, doc/site/migrating-from-spring.markdown, rts/Lua/LuaREADME.txt, rts/Lua/LuaSyncedTable.cpp, rts/Lua/LuaSyncedTable.h
Obsolete for almost 10 years now (can use the regular `next`, `pairs` and `ipairs`).
This is backwards-incompatible, but as a measure of goodwill all known games have received PRs or commits such that it won't be a problem:
https://github.com/ZeroK-RTS/Zero-K/commit/363f9de61968158e44aa982668db56131a55710d
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/b12b6965883e062f166a9044196872cd3401fad6
https://github.com/SplinterFaction/SplinterFaction/pull/3
https://github.com/springraaar/metal_factions/pull/6
https://github.com/FluidPlay/TAP/pull/7
https://github.com/techannihilation/TA/pull/1659
https://github.com/spring1944/spring1944/pull/477
https://github.com/Balanced-Annihilation/Balanced-Annihilation/pull/188
https://github.com/PicassoCT/MOSAIC/pull/33 …
=> Remove snext, spairs, and sipairs

doc/changelog.txt, rts/Sim/Units/Scripts/CobInstance.cpp
Was supposed to multiply by 1000/30 but instead multiplied by 30. Happens to be close enough to the proper value, and the parameter is unimportant enough, that apparently nobody noticed.
=> Fix COB SetMaxReloadTime parameter

doc/changelog.txt, rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandle.h
User story: many games want to run something after X frames, this is a very common case.
Some games poll the frame in the GameFrame event manually, in each individual wupget that needs it:
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_puppy_handler.lua#L231
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luarules/gadgets/chicken_spawner_defense.lua#L1465
Some more advanced games have an internal API for this:
https://github.com/spring1944/spring1944/blob/master/LuaRules/Gadgets/api_delay.lua
https://github.com/FluidPlay/TAPrime/blob/master/luarules/gadgets/api_delay.lua
https://github.com/Spring-SpringBoard/SpringBoard-Core/blob/master/LuaRules/Gadgets/api_delay.lua
Such commonly desired game-agnostic building block would be an excellent addition …
=> Add `Script.DelayByFrames`

rts/Lua/LuaConstGL.cpp, rts/Lua/LuaTextures.cpp, rts/Lua/LuaVBOImpl.cpp, rts/Rendering/Textures/TextureFormat.h
You could not create integer textures before, as well as some other formats because previous code did not produce valid data formats and types for internal formats.
GL specs reference:
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml
=> Fix creation of integer textures by CreateTexture and other formats

rts/Lua/LuaVBO.cpp, rts/Lua/LuaVBOImpl.cpp, rts/Lua/LuaVBOImpl.h, rts/lib/headlessStubs/glewstub.h, rts/lib/headlessStubs/glstub.c
Add Clear function to VBO. Sets whole buffer to 0.
Cosmetic change to vbo existence check. Replace repetitive code with a function, put it into an unnamed namespace to avoid flooding header with private utils.
=> VBO Clear and code cosmetic

rts/Rendering/Textures/TextureFormat.h
Quick fix of an oversight
Need inline to avoid link errors, **_when_** this file gets used more than once obviously.
It is currently used in 1 file only, so inline itself is not a problem. I will be updating it when I learn which way is better.
=> TextureFormat.h fail fix

rts/Rendering/Textures/Bitmap.cpp
This saves some small amount of storage in output file when alpha channel doesn't contain any information anyway.
Resolves #928
=> Drop alpha channel when saving texture as opaque

rts/System/MemPoolTypes.h, test/CMakeLists.txt, test/other/benchmarkMemPoolTypes.cpp, test/other/testMemPoolTypes.cpp
I was working with allocators and experimenting with changes to free list. Freed object indices can be stored in local (unused) page memory instead separate freelist but that unexpectedly did not bring any performance benefit. So basically it was
```
struct Page {
union {
size_t next_free_page_index;
char data[100];
}
```
instead 
```
std::array<Page, x> pages;
std::array<size_t, x> free_list;
```
I'm leaving tests & benchmarks in the repo for the future benefit.
Not sure what to do about benchmark as we don't have google bench in rts/lib/ but I know vcpkg/conan is around the corner so I disabled this test explicitly for now.
=> Add mempooltypes tests

doc/changelog.txt, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h, rts/Rendering/Textures/Bitmap.cpp, rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/CommandAI/BuilderCAI.h
Constructors consider unit radius into build range even before the unit is created. They do this once the unit exists, but they haven't been doing this before the unit exists. This change fixes that. Before, there have been issues with constructors getting too close and then having to back off so that they can start building a unit.
The unit radius is declared in the unit's model data.
=> Fix Constructors to use unit radius in build range check for new units

rts/Sim/Misc/ModInfo.cpp
The default makes for bad gameplay in the cases where it makes a difference. Units randomly fall off cliffs, or get stuck on cliffs when they are already at the bottom. I can't tell whether falling off cliffs is the main feature, it brings C&C Generals GLA Bike to mind, which was very cool when it worked, but it seems fairly hard to actually do it on purpose in our implementation, plus there is no pathfinder support to use it automatically where appropriate. Here's an example of the difference (the bottom-right corner shows `false`, the top-left shows units that have the same stats but the modrule is set to `true`): https://www.youtube.com/watch?v=4e3qHOrALZU
Most known games use `false` already:
https://github.com/ZeroK-RTS/Zero-K/blob/master/gamedata/modrules.lua#L26 …
=> Modrules: `allowGroundUnitGravity` defaults to false

.github/workflows/build-docker.yml, .github/workflows/release.yml, docker-build/action.yml, docker-build/scripts/07_pack_build_artifacts.sh, docker-build/scripts/build.sh
* migrate deprecated set-output command to env variable: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* update deprecated github actions versions
* add step to cleanup filesystem by deleting docker image to free up space for post steps
=> github: update docker-build scripts

rts/Game/UI/StartPosSelecter.cpp, rts/Lua/LuaSyncedRead.cpp, rts/Sim/Misc/Team.cpp
`AllyTeam` data is first loaded in `CGameSetup` from the start script, and is later passed down to `TeamHandler` from `CGameSetup`.
Since `TeamHandler` is responsible for storing dynamic information during the game, whereas `CGameSetup` only stores the initial data as loaded from the start script, we remove all calls to `CGameSetup::GetAllyStartingData` in favor of information coming from `TeamHandler` to ensure that we consistently retrieve up-to-date data.
=> consistently use `TeamHandler` for `AllyTeam` data

doc/changelog.txt, rts/Game/UI/StartPosSelecter.cpp, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h, rts/Lua/LuaSyncedRead.cpp, rts/Sim/Misc/Team.cpp, rts/Sim/Misc/TeamHandler.h
This new control allows to change an ally team's start box from a synchronized context, thereby opening up the possibility for Lua gadgets to reposition start boxes as needed.
> [!NOTE] 
> This PR depends on #954 to be merged first: #954 fixes a behaviour discovered while adding this new control, where after repositioning boxes via `Spring.SetAllyTeamStartBox` some things were working as intended (e.g. display of the startbox is correctly relocated) and some others were not (e.g. clamping of teams start position inside of the ally team startbox), because of the fact `AllyTeam` data is coming from multiple source.
=> add `Spring.SetAllyTeamStartBox` synced control

doc/changelog.txt, rts/Game/GameSetup.cpp
Previously, we failed immediately when trying to start a game on a map with insufficient startpos defined in its configuration to support the number of teams specified in the start script. This behaviour was denying the game a chance to handle start positions itself at a later stage.
Now, we emit a warning instead when MapParser does not find startpos defined in the map config for all teamIDs present in start script, but continue to start the game normally anyway. This gives a chance to the game to remedy the situation and handle startpos itself.
In the worst case, teams without a startpos will spawn in the corner -- giving an obvious hint that something is amiss and the map is unable to support this number of players by itself without assistance from the game.
=> gamesetup: warn instead of fail when missing startpos in map configuration

rts/Sim/Units/Unit.cpp, rts/Sim/Units/Unit.h, rts/Sim/Units/UnitHandler.cpp, rts/Sim/Units/UnitTypes/Factory.cpp, rts/Sim/Units/UnitTypes/Factory.h
Previously, `KillUnit()` (and its variants) exposed an optional `showDeathSequence` parameters that defaulted to `true`, and if set to `false` then no death script was run.
In this commit, we remove the parameter as it is entirely redundant:
- The 3rd mandatory parameter `reclaimed` is used for exactly the same purpose: if `reclaimed` is `true`, then no death script is run.
- The default value of `showDeathSequence` is `true` and none of the callers actually set it to `false`, except 1, but this one also sets `reclaimed` to `true`... thereby overriding `showDeathSequence`.
=> sim: remove redundant `KillUnit()` parameter

doc/changelog.txt, rts/Game/SyncedGameCommands.cpp, rts/Game/UnsyncedGameCommands.cpp
This new command allows to remove units similar to `/destroy` except no death script is run (so no explosion nor wreckage).
It works in exactly the same way as `/destroy`:
- As unsynced, `/remove` will remove selected units.
- As synced, `/remove <unitID...>` will remove all unitIDs provided.
Due to the fact only the last call to `KillUnit` differs between `/destroy` and `/remove`, we refactor both to use the same base action executor and only differentiate them by description and a boolean flag.
=> gamecommands: add new `/remove` cheat-only command

rts/System/Platform/Threading.cpp
NOTE: affinity IS actually working on linux, but we're returning errors after a successful set for a worker thread.
This bug goes back ~9 years, from [this commit](https://github.com/beyond-all-reason/spring/commit/ef467bae5ed408fb2f142e6af4c9f9cf804c6e47#diff-492361d44f4a51548f868672b639fe964da1c7b21b59df2490fd1af23c6efedbL112) and [this refactor](https://github.com/beyond-all-reason/spring/commit/e342a2dde71daf9c475a140ed6c897b0b2d9dfb7#diff-492361d44f4a51548f868672b639fe964da1c7b21b59df2490fd1af23c6efedbR90-R118).
original commit's ticket: https://springrts.com/mantis/view.php?id=4544
Basically, the logic of this is wrong:
```
const int numCPUs = std::min(CPU_COUNT(inputCpuSetMask), 32);
for (int n = numCPUs - 1; n >= 0; --n) {
...
}
```
The code assumes CPU_COUNT(inputCpuSetMask) will …
=> fix: cpu affinity on linux now correctly prints success messages for thread affinity

rts/Menu/alphanum.hpp, rts/Rendering/Shaders/Shader.h, rts/Sim/Path/HAPFS/PathDataTypes.h, rts/Sim/Units/Scripts/CobEngine.h, rts/System/Cpp11Compat.hpp
No longer needed, containers/algorithms use concepts nowadays.
=> Get rid of `{u,bi}nary_function` functor inheritance

rts/System/Sound/OpenAL/Sound.cpp
Workaround for SDL bug with some soundcards, returning more channels than we asked for (returned 8 in test case)
closes wrong initialized SDL audio device and disallows channel changes on 2nd attempt
As a result we don't start our audio device with alternative method. And we initialized successfully with SDL "default" device, which enables us to follow switched audio devices
=> Workaround for SDL audio bug with some soundcards

doc/site/changelogs/running-changelog.markdown, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedCtrl.h
* add `Spring.DeselectUnit{Map,Array}` to complement existing Select interfaces.
* existing `Spring.SelectUnitArray` can now accept any keys in the table. Previously they had to be numbers, but the table did not actually have to be an array. This was because many tables historically used to contain an 'n' key when returned by some common APIs, but this isn't the case since 731c57d3b0e1d28bd8271b9f6aa3748d7f6e1da0. `Spring.SelectUnitMap` already accepts arbitrary values under the unitID keys.
* extract the common implementation of all four functions into a common helper, since they barely differ.
=> Lua selection API improvements

doc/site/changelogs/running-changelog.markdown, rts/Lua/LuaConstGame.cpp, rts/Lua/LuaUtils.h
So people won't need to put magic `\254` etc in their code.
=> Add named constants for color codes

doc/changelog.txt, doc/site/changelogs/running-changelog.markdown, doc/site/migrating-from-spring.markdown, rts/Lua/LuaUnsyncedCtrl.cpp
Engine should leave issuing a stop command to game side so that they can customize unit behavior when units are shared. It can be easily implemented by issuing a stop command in the UnitGiven callback, if game developers desire that behavior.
Reference implementation: 
```lua
function widget:UnitGiven(unitID, unitDefID, newTeam, oldTeam)
if newTeam ~= Spring.GetMyTeamID() then return end
Spring.GiveOrderToUnit(unitID, CMD.STOP, {}, {})
end
```
=> Allow games to customize shared unit orders

doc/site/changelogs/running-changelog.markdown, rts/Lua/LuaConstGL.cpp
For use in `gl.BlendEquation`.
=> Add blending equation constants to Lua GL API

rts/Game/GameHelper.cpp, rts/Game/GameHelper.h
In C++20, std::vector::~vector() is constrexpr, due to the way clang instantiates constrexpr functions[1], anything like
struct D { std::vector<std::pair<D, D>> t; };
struct D { inline static std::vector<D> t; };
doesn't compile becuase D is not complete at the point of vector destructor intiailisation unlike in MSVC or GCC that do it at a different point of time.
[1]: https://github.com/llvm/llvm-project/issues/59966
=> Switch from `inline static` to regular `static` to fix clang issue

rts/Lua/LuaUtils.cpp, rts/Lua/LuaUtils.h
Those functions are not referenced anywhere at the moment so it should be save to drop them.
=> Drop LuaUtils::{Backup,Restore}

rts/Sim/Units/CommandAI/MobileCAI.cpp, rts/Sim/Units/CommandAI/MobileCAI.h, rts/System/float3.cpp, rts/System/float3.h
This branch is mainly looking to solve #905, with a few other changes attempting to get better bugger off target positions. 
Currently if the next command is a movement command, the target location will be towards that command position. Here we additionally check if the next movement command is a build command, and then move perpendicular so that the next building is not blocked. 
If there are no additional commands in the queue, then we attempt to move directly out of the circle as proposed in the issue. If that location is blocked, then rotations from the nearest axis are checked, as buildings are usually on a grid. Then if after a few buggeroff attempts we still haven't gotten out of the buggeroffradius, we fall back to just picking random locations as it works currently.
I tried a …
=> Bugger off to better target locations

rts/build/cmake/FindAsciiDoc.cmake
There was a book that could result in a list of items getting found by `GLOB` which would break the call to `make_manpages.sh` because it expects a single items.
For instance, my system has
usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons/manpages/docbook.xsl usr/share/xml/docbook/xsl-stylesheets-1.79.2/manpages/docbook.xsl and it would output both.
This will instead use the pre-existing `find_file()` and remove the second mechanism.
=> Streamline finding docbook.xsl

README.markdown, doc/site/index.markdown
It's not heavily used and it's constantly being broken by Discord moderators.
=> Drop all references to Matrix room

doc/site/changelogs/running-changelog.markdown, rts/Game/GameSetup.cpp, rts/Map/Generation/BlankMapGenerator.cpp, rts/Map/Generation/BlankMapGenerator.h
The old keys can still be reused for a "proper" random mapgen in the future, but no reason to break existing projects until then.
=> Fix compatibility for old blank map gen

rts/Lua/LuaVAOImpl.cpp
Just makes the documentation match the function definition.
=> docs(LuaVAOImpl): remove extra parameter from DrawArrays doc comment

rts/Sim/Units/CommandAI/FactoryCAI.cpp
Issue: if you tell the factory to build something with CTRL and/or SHIFT modifiers it gets multiplied by x20 and/or x5 respectively. But this doesn't work if you do it via the insert command, the modifiers are then ignored (and you have to work around it by sending a bunch of x1 commands in a loop).
This patch fixes this behaviour. See https://github.com/ZeroK-RTS/Zero-K/tree/fac-insert for a test case (build a fac, queue a unit, alt+shift queue a different one)
=> Fac insert obeys mults

rts/CMakeLists.txt, rts/System/EventClient.h, rts/System/Platform/Linux/CrashHandler.cpp, rts/System/Platform/Misc.cpp, rts/System/Platform/Threading.cpp, rts/System/Platform/Threading.h, rts/System/Platform/byteorder.h, rts/System/Sound/OpenAL/SoundSource.cpp, rts/System/SpringApp.cpp, rts/builds/dedicated/CMakeLists.txt
In many places it's just accounting for OpenBSD like for FreeBSD. Also avoiding some non-existent libraries like libunwind, librt. zlib.h needs to be added in a few places on OpenBSD, and ucontext.h in one. Overall this is the more straightforward part of supporting the engine on OpenBSD.
=> add OpenBSD into branching/building in several places

rts/Game/ClientSetup.cpp, rts/Game/ClientSetup.h, rts/Game/PreGame.cpp
By specifying
ShowServerIP = 0; 
in startscript
=> Allow turning off the display of the host IP and username you are connecting with from the connecting screen on load.

rts/Rendering/Models/3DModel.cpp, rts/Rendering/Models/3DModel.h, rts/Sim/Units/UnitHandler.cpp
Try to save half a millisec per frame lategame by performing  this MT'd.
Ive temporarily added a config int SlowUpdateBoundingVolumeMT to toggle this ingame for comparison only. Otherwise toggling this ingame may lead to a desync.
=> UpdateBoundingVolume MT during Unit::SlowUpdate

rts/Sim/Units/Scripts/UnitScript.cpp, rts/Sim/Units/Scripts/UnitScript.h, rts/Sim/Units/Scripts/UnitScriptEngine.cpp, rts/Sim/Units/Scripts/UnitScriptEngine.h
The config int AnimationMT allows run-time configuration of this being on or off.
Tested for sync safety. in #1139
Clean implementation of:
https://github.com/beyond-all-reason/spring/pull/1139
=> Execute animations in a multithreaded way.

rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
Check out the patterns of use for `Spring.GetFrameTimeOffset()` across a wide array of games including multiple examples in large ones:
https://github.com/search?q=getframetimeoffset+lang%3Alua+-is%3Afork&type=code
https://github.com/spring1944/spring1944/blob/master/ModelMaterials/0_flags.lua#L71
https://github.com/SplinterFaction/SplinterFaction/blob/c15fa5edb30f28386a31fea7706dc3a8bb8a868a/LuaUI/Widgets/cmd_mex_placement.lua#L753
https://github.com/techannihilation/TA/blob/master/lups/particleclasses/nanolasersnoshader.lua#L156
https://github.com/Arch-Shaman/ZK-Futurewars-Mod/blob/Stable/LuaRules/Gadgets/unit_cloak_shield.lua#L837
https://github.com/azaremoth/cursed/blob/2944b8f08ee294d18610c5750f61b7df058f0df7/LuaUI/Widgets/minimap_events.lua#L158 …
=> Add `Spring.GetGameTimeDraw() -> number`

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Fix of #1225: Add "Spring.GetModOption(string) -> string"
This PR varies slightly from the request in #1225, as it adds a new function GetModOption() instead of overloading GetModOptions(). This choice was made to be consistent with existing LuaSyncedRead functions (same pattern as GetGameRulesParam vs. GetGameRulesParams, GetPlayerRulesParam vs. GetPlayerRulesParams, etc.).
Limited testing validated that this is working as expected, but I would appreciate additional testing because I'm relatively new to this project and may have overlooked something.
Note the discussion on the [issue page](https://github.com/beyond-all-reason/spring/issues/1225): Spring.GetModOption("foo") may not return the same value as Spring.GetModOptions().foo if a game has overridden Spring.GetModOptions().
=> Fix #1225: Add Spring.GetModOption(string) -> string

rts/Sim/Units/Unit.cpp, rts/Sim/Units/Unit.h, rts/Sim/Units/UnitHandler.cpp, rts/Sim/Weapons/Weapon.cpp, rts/Sim/Weapons/Weapon.h
This PR multithreads one of the most expensive parts of UpdateUnitWeapons, namely updating the weapon vectors. 
All units who have weapons perform this task every frame. The UpdateWeaponVectors function is self-contained, and does not call into lua or bos.
However, in order to make this optimization possible, the UpdateWeaponVectors function has to be called before fastautoretargeting and attacking existing targets. 
This is mostly due to the fact that Weapon::Update is virtual function, which would otherwise make any preMT/MT/postMT split near impossible. Also, most Weapon::Update overrides also do their own UpdateWeaponVectors, as does, for example Weapon::Attack. 
I have tested this change on the behaviour of a lot of units shooting, and found no unwanted side effects. 
Performance …
=> UpdateWeaponVectors MT

rts/Lua/LuaSyncedRead.cpp
At some point they should be unified, for now just make them use the same internal function for consistency.
=> Refactor `Spring.Get{Map,Mod}Option[s]`

rts/System/SpringMem.cpp
Passing `nullptr` to `std::memcpy` triggers UB, see https://en.cppreference.com/w/cpp/string/byte/memcpy.
On Fedora 39 it segfaults (GCC 13, `-O3` build):
```
#0  __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:265
#1  0x0000000000ccfc9f in spring::ReallocateAlignedMemory
(ptr=<optimized out>, size=size@entry=536870912, alignment=alignment@entry=64)
at /spring/rts/System/SpringMem.cpp:38
#2  0x0000000000b18ad8 in TexMemPool::Resize (this=0x488a15f0, size=536870912) at /usr/include/c++/13/span:287
#3  0x0000000000b0e461 in ITexMemPool::Init (size=size@entry=536870912) at /usr/include/c++/13/bits/unique_ptr.h:199
#4  0x0000000000b0ea70 in CBitmap::InitPool (size=536870912, size@entry=512)
at /spring/rts/Rendering/Textures/Bitmap.cpp:1040
#5 …
```
=> fix(SpringMem): UB in fallback case

rts/Sim/Misc/DefinitionTag.cpp, rts/Sim/Misc/DefinitionTag.h
During game loading, WeaponDefHandler.cpp constructs all known WeaponDefs. Each WeaponDef object is constructed by finding the [lua table key <-> WeaponDef member variable mapping] in DefType::tagMetaData. This search is done by linearly scanning DefType::tagMetaData.
The construction process' exection time grows in proportion to (number of tags) * (number of weapons).
To cut down on loading times, we ensure that DefType::Load calls uses an index to look up tags.
Additionally, this change makes GetMetaDataByInternalKey look up keys case-insensitively.
- There is no change to the DEFTAG and DUMMYTAG API macros.
- Slightly reduces static storage required.
- Slightly increases the pre-main dynamic initialization time.
- Significantly speeds up DefType::Load and DefType::ReportUnknownTags …
=> Index DefType tag keys to speed up GetMetadataBy*Key calls

rts/System/FileSystem/FileSystem.cpp
GetNormalizedPath uses a series of regular expressions to normalize a path, which can be quite slow.
This change uses C++17's <filesystem> library to normalize path names. Performance profiling the Spring load sequence shows the following:
Before:
- 1,779 GetNormalizedPath calls, total time: ~170ms.
After:
- 1,779 GetNormalizedPath call, total time: ~1.5ms.
Tested (not too thoroughly) by diffing GetNormalizedPath outputs between the original and new implementation on both Linux and Windows builds.
Below is a description of how the original behavior is replicated, see https://en.cppreference.com/w/cpp/filesystem/path for reference.
- https://github.com/beyond-all-reason/spring/blob/63a18aae7241943f77ff507983dd78325ce28514/rts/System/FileSystem/FileSystem.cpp#L221 `generic_string()` uses …
=> Use std lib lexical_normal to normalize paths.

rts/Lua/LuaFeatureDefs.cpp, rts/Lua/LuaHandle.cpp, rts/Lua/LuaInterCall.cpp, rts/Lua/LuaOpenGL.cpp, rts/Lua/LuaPathFinder.cpp, rts/Lua/LuaRules.cpp, rts/Lua/LuaShaders.cpp, rts/Lua/LuaSyncedMoveCtrl.cpp, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedTable.cpp, rts/Lua/LuaUI.cpp, rts/Lua/LuaUnitDefs.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUtils.cpp, rts/Lua/LuaUtils.h, rts/Sim/Units/Scripts/LuaUnitScript.cpp
Using lua_createtable instead of lua_newtable reduces the number of rehashes needed when populating lua tables with sizes known at table creation time.
This change is a strict improvement over using lua_newtable: tables that get larger than the initial size will get rehashed as normal. Tables that fit into the specified size will avoid the need to rehash after creation.
Additionally, in `rts/Lua/LuaOpenGL.cpp` we use `lua_rawseti` to populate the array table instead of manually specifying integer keys.
See 'Lua Gems, Chapter 2, About tables' on details on table keys are hashed.
=> Use lua_createtable when size of table is known.

rts/Rendering/Env/Decals/GroundDecalHandler.cpp, rts/Rendering/Units/UnitDrawerData.cpp, rts/Sim/Features/FeatureMemPool.h, rts/Sim/Path/HAPFS/PathMemPool.h, rts/Sim/Projectiles/ExplosionGenerator.cpp, rts/Sim/Projectiles/ProjectileMemPool.h, rts/Sim/Units/UnitMemPool.h, rts/Sim/Weapons/WeaponMemPool.h, rts/System/MemPoolTypes.h, test/CMakeLists.txt, test/other/testMemPoolTypes.cpp
Memory pools not being aligned allows compilers to generate code that depends on that alignment. This caused spurious crashes when code was compiled under clang, but could happen in any other compiler.
In addition to making the pool alignment aware
- I added helpers that automatically infer the required size and alignment straight from the set of types that can be stored in the given memory pool instance
- and compile time checks that verify that memory alignment of the pool is suitable for the allocated object
=> Make Memory Pools memory alignment aware

cont/LuaUI/widgets.lua
Previously, Initialize() was wrapped dozens of times for each widget.
---
Based on https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2643
While I have tested the BAR PR, I have not tested this PR (I don't have enough experience with the base game or non-BAR games to be confident in testing it here). That said, it is not that complicated, so it at least seems fine to me.
=> fix(widgets): only SafeWrapFunc Initialize() once

rts/Lua/LuaUnsyncedCtrl.cpp
The alpha parameter is now optional so you can just set falloff without having to pass the current alpha.
=> SetGroundDecalAlpha: allow setting just falloff

rts/Lua/LuaSyncedCtrl.cpp, rts/Sim/Units/UnitTypes/Builder.cpp, rts/Sim/Units/UnitTypes/Factory.cpp
Previously was defined per team slowupdate, which happens every second. This means there is no behaviour difference, but it now works correctly if somebody tweaks game speed or team slowupdate rate.
=> Unit def build speed now defined per second

rts/Lua/LuaSyncedCtrl.cpp
Documentation claims only 3 params (x, z, alwaysAboveSea) but there's a hidden optional y param.
=> Fix SetUnitPosition documentation

rts/Map/ReadMap.cpp, rts/Rendering/Common/ModelDrawerData.h, rts/System/Threading/ThreadPool.h
The current implementation is tricky to understand (and that's largely me to blame for that) and using negative numbers is unintuitive. The chunk sizes mostly became somewhat meaningless because the number of jobs were fixed and so the work would be done in chunks of work/threads regardless of the inputs provided (unless there was too few work to start with.)
I've adjusted it to be easier to understand and easier to configure with a min and max that works as you would expect them to. Which allows batches to be more finely controlled to allow devs find the best balance between avoid cross-cpu talk and minimising work tails (where few cores are busy finishing work while the other cores sit idle.)
=> refactor for_mt_chunk, adding max chunk size.

rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedRead.cpp
* alpha falloff now set/get per second (instead of frame)
* GetAllDecals returns an empty table instead of nil if there are no decals. Returning nil both prevents idiomatic code (cannot pass the returned value straight into interfaces that expect a table) and is a micropessimisation (adds the overhead of nil check into the case where decals exist, while the 0 decals case is the earlygame which doesn't need help).
=> Decal Lua API a bit more user-friendly

rts/Lua/LuaUtils.cpp
As discussed on Discord. Linux also has `_L` in ctype.h, but it seems this file is only pulled in on OpenBSD, probably via `#include <cctype>`. Renaming this variable fixes the collision.
=> avoid collision with macro _L in ctype.h (is pulled in on OpenBSD)

rts/Net/AutohostInterface.cpp
The current descriptions of packets were heavily lying about the actual content of the packets. The new description was heavily tested in preparation of https://github.com/p2004a/recoil-host/commit/ab2206f9e2b515f096a0687a1a61b7d7023a437c on packed dumps from live games and of course reading engine source.
=> Improve and fix documentation for AutoHost packets

rts/Lua/LuaUnsyncedRead.cpp
* fixes a `Spring.GetGroupUnitsCount` crash when passing an invalid group (e.g. 999999).
* extract the safety check so that all the relevant functions will stay consistent in the future.
=> Fix `Spring.GetGroupUnitsCount` crash + safety refactor

rts/Game/SelectedUnitsAI.cpp
* for #939, fungible resources. Previous value was M+60E.
* power defaults to M+60E and most games don't change it.
* all known games use Lua customformations anyway.
=> Engine formation fronts treat power as value

rts/Sim/Units/CommandAI/CommandQueue.h, rts/Sim/Units/UnitTypes/Builder.cpp
Issue: When mutltiple builders are tasked with building something floating on the surface of the water and get there at different frames, it can trigger mutliple versions of the same unit are started on the same location.
=> Fix build floating unit on water duplication bug

rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandle.h, rts/Sim/MoveTypes/GroundMoveType.cpp, rts/Sim/MoveTypes/GroundMoveType.h, rts/System/EventClient.h, rts/System/EventHandler.h, rts/System/Events.def
Fixes https://github.com/beyond-all-reason/spring/issues/1459
This fixes the issue where Zero-K rand the engine may not agree on exactly when a unit has reached its goal. The engine will send an UnitArrivedAtGoal event so that the game can tell that the engine believes the move is complete and so the game can take the necessary actions to ensure any further orders are carried out.
Zero-K can use the following diff file to add support for this new event.
[Use_UnitArrivedAtGoal_InRawMove.diff.zip](https://github.com/beyond-all-reason/spring/files/15223996/Use_UnitArrivedAtGoal_InRawMove.diff.zip)
*Though I didn't run into any issues with these Zero-K changes, there may be the need to add some protections around some of it. Think of it as starting point.*
Builds on the work undertaken in …
=> Add goal reached event

rts/Sim/Units/CommandAI/CommandAI.cpp, rts/Sim/Units/CommandAI/CommandAI.h, rts/Sim/Units/UnitDef.cpp, rts/Sim/Units/UnitDef.h, rts/Sim/Weapons/Weapon.cpp, rts/Sim/Weapons/Weapon.h, rts/Sim/Weapons/WeaponLoader.cpp
Burst weapons will honour these settings on the weapon (in the unitDef):
`maxAngleDif`  for units that allow weapons to fire independent of the unit's facing
`maxForwardAngleDif` for units that lock their weapons towards the front of the unit
Fixes https://github.com/beyond-all-reason/spring/issues/1451
=> prevent burst weapons firing outside their intended arc

doc/changelog.txt, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
For https://github.com/beyond-all-reason/spring/issues/1520
Can be used to determine if a unit has any of the following:
```c++
enum PhysicalState {
PSTATE_BIT_ONGROUND    = (1 << 0),
PSTATE_BIT_INWATER     = (1 << 1),
PSTATE_BIT_UNDERWATER  = (1 << 2),
PSTATE_BIT_UNDERGROUND = (1 << 3),
PSTATE_BIT_INAIR       = (1 << 4),
PSTATE_BIT_INVOID      = (1 << 5),
PSTATE_BIT_MOVING   = (1 <<  6),
PSTATE_BIT_FLYING   = (1 <<  7),
PSTATE_BIT_FALLING  = (1 <<  8),
PSTATE_BIT_SKIDDING = (1 <<  9),
PSTATE_BIT_CRASHING = (1 << 10),
PSTATE_BIT_BLOCKING = (1 << 11),
};
```
=> add GetUnitPhysicalState for lua

rts/Lua/LuaHandle.cpp
`UnitCallIn` already puts the function on the stack. Fixes #1523
=> Fix #1523, stack issue with warning spam

rts/Sim/Units/UnitTypes/Builder.cpp, rts/Sim/Units/UnitTypes/Builder.h
Map recalc is expensive. It was originally done at SlowUpdate. This change puts it back to that for terraform jobs, except that there is a forced update at the end to ensure the final state of the terrain is accounted for.
=> Terraform at original rate w/ enforced update at end.

rts/Sim/MoveTypes/GroundMoveType.cpp
An optimization that had been previously applied, but with a fix that addresses unit not alwasy animating correctly when created.
=> Don't change heading on a unit that doesn't need it.

rts/Rendering/QTPFSPathDrawer.cpp, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Path/QTPFS/Node.cpp, rts/Sim/Path/QTPFS/Node.h, rts/Sim/Path/QTPFS/NodeLayer.h, rts/Sim/Path/QTPFS/Path.h, rts/Sim/Path/QTPFS/PathCache.cpp, rts/Sim/Path/QTPFS/PathCache.h, rts/Sim/Path/QTPFS/PathDefines.h, rts/Sim/Path/QTPFS/PathManager.cpp, rts/Sim/Path/QTPFS/PathManager.h, rts/Sim/Path/QTPFS/PathSearch.cpp, rts/Sim/Path/QTPFS/PathSearch.h, rts/Sim/Path/QTPFS/PathThreads.h, rts/Sim/Path/QTPFS/Systems/RequeuePathsSystem.cpp
QTPFS Path Repair tracks damage to paths, not just whether a path was damaged, so that when it is time to repath, only the damaged portion needs to be be repathed. This repath is constrained in area to avoid creating bad paths such as forcing the reconnection if it is more appropriate to do a full repath. The pathing system will switch to using a full repath if it isn't appropriate to repair or it can't feasibly repair the path.
This change is intended to reduce the time needed to update paths in response to damage. Previously the whole remainign path had to be recalculated starting from where the owner had got to.
=> QTPFS Path Repair

rts/System/ContainerUtil.h
Provide default args instead of having a bunch of copypasted functions.
=> Container util: remove functor template copypasta

rts/System/Input/MouseInput.cpp
SDL2 does not support warping on Wayland if the Cursor is visible.
https://github.com/libsdl-org/SDL/blob/efaa58732abb3faf3900b2d93a166b955fbd8ed0/src/video/wayland/SDL_waylandmouse.c#L646
This fixes: https://github.com/ZeroK-RTS/Zero-K/issues/5005
I tested it, verified it works, please check if this breaks other platforms.
=> Fix mouse warping on wayland.

rts/Lua/LuaConstGame.cpp, rts/Sim/Misc/ModInfo.cpp, rts/Sim/Misc/ModInfo.h, rts/Sim/Weapons/Weapon.cpp
Some things that were conceptually boolean
are now kept as such instead of 0/1 int.
Behaviour (incl. Lua and AI interface) unchanged.
=> Modrule type correctness

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Last part of #1584
I need someone to review this as the lua table feature is very unintuitive to me.
=> Added GetUnitCostTable

rts/System/CMakeLists.txt, rts/System/Math/SpringDampers.cpp, rts/System/Math/SpringDampers.h, rts/System/Math/expDecay.h
@loveridge I've extracted some of your spring damper utils into a separate PR, since math seems uncontroversial. If you OK it can be merged right away. I've moved things around though (`expDecay` is extracted into its own file away from `CameraHandler.cpp`, and things live in `rts/System/Math/` instead of directly in `rts/System/`) so your full PR will need to be adjusted a bit.
=> Spring damper math utils

rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedCtrl.h
https://github.com/beyond-all-reason/spring/issues/1632
1.5 microseconds saved for an array of 30 items:
```lua
function widget:Update()
local table = Spring.AllocateTable(30) -- vs {}
for i = 1, 30, 1 do
table[i] = i
end
Spring.Echo(table[25])
end
```
=> allocate table

rts/lib/lua/src/lbaselib.cpp
I copied what I could from the changes to Lua 5.2 to backport making __pairs work as a metamethod.
This greatly improves compatibility with sollua as it assumes that __pairs actually exists and tries to use it
Also makes some of the Lua integrations for RmlUI better to use.
=> backport __pairs metamethod to our tweaked version of Lua

docker-build/scripts/04_install.sh
The libraries are added when we include deps via add_subdirectory. There isn't a simple way to ask CMake to not install them. A clean way would be to use components, but our cmake is not there at the moment.
=> Drop library directories from install

CMakeLists.txt
For a very long time, the portable install is the default build and I'm not aware of any customers that use engine in non-portable mode. This change also updates the configuration parameters to put binaries and libraries in correct locations by default when building in portable mode on Linux.
=> Make portable install default and set dirs correctly

rts/Lua/LuaConstEngine.cpp
With an example for a feature added in the latest release.
* `if Engine.FeatureSupport.hasXYZ then` is both more self-documenting and convenient than `if Script.IsEngineMinVersion(123) then`
* development is not necessarily linear so there may not even be any specific version a feature was added in. A feature can be available at commit 1 on feature branch X, on commit 234 after being merged to the common development branch Y, and on version 1.5.67 on release branch Z. Having a direct bool to rely on is better than trying to account for all of the above combinations via version checks.
* could be used for internal versioning of features as well. For example maybe the initial version of rmlUI sets `Engine.FeatureSupport.rmluiApiVersion = 1` and then when it finally gets livetested and the …
=> Add `Engine.FeatureSupport` table

rts/Game/UI/GuiHandler.cpp, rts/Game/UI/GuiHandler.h
My first PR. Just removes an unused variable I found while reading through engine code.
This field was added in b4bf567fa80b2afe87e8ce99391c230fd54a9351 but it is only ever modified, and never read. It's unclear how it was intended to be used.
=> Remove unused vector `GuiHandler::buildcolors`

rts/lib/sol2/sol.hpp
This is just a straight copy of https://github.com/ThePhD/sol2/pull/1606 from sol2 to fix compilation under clang++ 19 as it's more restrictive in veryfying code under templates.
=> Port fix to sol's optional::emplace for clang++ 19

rts/System/float3.h
All existing normalize functions seem to modify the float3 inplace.
=> Add float3::GetNormalized

rts/Lua/LuaUnsyncedCtrl.cpp
The camera controller cannot be bypassed, otherwise the camera handler will move the camera back to the camera controller's state.
=> setcameratarget must change camera controller

rts/System/Platform/Linux/Futex.cpp
This is necessary for building on OpenBSD (and currently used in the OpenBSD port of recoil). syscall entry point was removed from OpenBSD in 2023 for security reasons and the recommended way is use of the specific syscall as in this diff.
=> use futex directly instead of via syscall on OpenBSD

rts/System/FileSystem/FileHandler.h, rts/System/Sound/OpenAL/MusicStream.cpp, rts/System/Sound/OpenAL/MusicStream.h, rts/System/Sound/OpenAL/SoundSource.cpp, rts/System/Sound/OpenAL/SoundSource.h
This change allows for creating more sound streams. We currently have only one dedicated to BG music. https://github.com/beyond-all-reason/spring/blob/414df1e8bb81535792fe9e77a6dcc0ae8c44e414/rts/System/Sound/ISoundChannels.h#L11
TODO rewrite SoundSource and AudioChannel and split samples from streams?
=> Remove singletons from audio stream

rts/Sim/Misc/ModInfo.cpp
There's this assertion, but that doesn't trigger in release builds.
https://github.com/beyond-all-reason/spring/blob/0094744afa0838a0724386cb6426b6cf05a086a9/rts/Sim/Misc/QuadField.cpp#L123-L124
Besides, best to check the value right where it is read.
=> Check quadfield size modrule properly

.github/workflows/docker-images-build.yml, .github/workflows/engine-build.yml, docker-build-v2/README.md, docker-build-v2/amd64-linux/Dockerfile, docker-build-v2/amd64-linux/ccache.conf, docker-build-v2/amd64-linux/toolchain.cmake, docker-build-v2/amd64-windows/Dockerfile, docker-build-v2/amd64-windows/ccache.conf, docker-build-v2/amd64-windows/toolchain.cmake, docker-build-v2/build.sh, docker-build-v2/scripts/build.sh, docker-build-v2/scripts/compile.sh, docker-build-v2/scripts/configure.sh, docker-build-v2/scripts/package.sh, docker-build-v2/scripts/split-debug-info.sh
First PR that introduces the new docker based engine build system, following up from previous draft PR https://github.com/beyond-all-reason/spring/pull/1707
As written in previous PR, and in commit, the new system is primarily targeting efficiency:
- Smaller and quicker to build Docker build environment images
- Storage of Docker images in registry instead of cache that expires
- Leverages much more performant namespace.so GitHub actions runners
- Each step is optimized for parallelism to leverage new runners
- Heavy cross branch, persistent, caching of compilation objects
=> Add new Docker based build system

README.markdown
This PR updates the README to refer to master branch instead of the BAR105 branch as the default branch for cloning.
=> update README branch reference

rts/Game/UnsyncedGameCommands.cpp
* Fixes wrong variable name when saving config on /iconshidewithui command
* Possibly related to https://github.com/beyond-all-reason/Beyond-All-Reason/issues/969
* Check here: https://github.com/beyond-all-reason/spring/blob/master/rts/Rendering/Units/UnitDrawer.cpp#L63
=> Fix saving state after /iconshidewithui

rts/Lua/LuaUnsyncedRead.cpp
Looks like an accident in 7af79e4c5e330049bb3855b5ba734f3da1138be3
=> Restore missing `Spring.GetFeatureSelectionVolumeData`

rts/Game/GameHelper.cpp, rts/Sim/MoveTypes/GroundMoveType.cpp
Fixes https://github.com/beyond-all-reason/spring/issues/1691
This change assumes that a forced alignment of the unit's x/z size and it's ground movedef is an acceptable solution. Note, this size change does not impact other move types, only ground based.
=> fix bugger off issues

rts/Sim/Projectiles/ExpGenSpawnable.cpp, rts/Sim/Projectiles/ExpGenSpawnable.h, rts/Sim/Projectiles/WeaponProjectiles/BeamLaserProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/EmgProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/ExplosiveProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/FireBallProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/FlameProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/LargeBeamLaserProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/LargeBeamLaserProjectile.h, rts/Sim/Projectiles/WeaponProjectiles/LaserProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/LightningProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/MissileProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/StarburstProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/TorpedoProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.cpp, rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.h, rts/Sim/Weapons/WeaponDef.cpp, rts/Sim/Weapons/WeaponDef.h
Use `animParams1`, `animParams2`, `animParams3`, `animParams4` in a weaponDef to animate `texture1`, `texture2`, `texture3`, `texture4` respectively or `animParams` to animate all of them the same way.
Implements https://github.com/beyond-all-reason/spring/issues/1565
=> Implement animated flipbook style textures for weapon projectiles.

rts/Map/MetalMap.cpp, rts/Map/ReadMap.cpp
* Serialize metalMap
* Saves distributionMap and extractionMap, setting other members to ignored since they don't need to be stored the map loader will [set those](https://github.com/beyond-all-reason/spring/blob/1cc2b11f7c777bbe6634b3a53eb2241baabab5f0/rts/Map/ReadMap.cpp#L169).
* Alternative PR to #1744 (see there for more information about related issue and how to test).
* Seems this is a better way.
* Just hope setting those CR_IGNORED members has no side effects, for what I understand @sprunk [said](https://github.com/beyond-all-reason/spring/pull/1744#issuecomment-2450920710) should just make the serializer ignore those. Otherwise it's not a big deal to include them in the serialization.
* Could be done in CregLoadSaveHandler.cpp instead of ReadMap.cpp, I thought it's better to …
=> Save and restore metalMap.

rts/Game/Game.cpp
- Fixes the test for drawing two frames per minute when minimized.
See https://github.com/beyond-all-reason/spring/issues/1661 for a discussion of the underlying issue and investigation.
This is just a simple proposal, but I don't know much about the engine so please review carefully.
Also, feel free to discard this solution and do something different, it's just a good faith effort.
The change is simple, and I think using the value from globalRendering->lastFrameStart that we set in the same module is going to yield the same results as using lastDrawFrameTime to store it. It does look like a duplicate value stored in both modules.
There might be something going on I'm not aware of though.
Could be safer to just add a new variable so we can keep storing lastDrawFrameTime and just use a new …
=> Fix Game.cpp two draws per minute when minimized.

rts/Net/NetCommands.cpp
And don't accept it in non-debug (assert-disabled) builds either.
The value here comes from a network packet, which may be spoofed so its contents should not be asserted.
=> Don't assert on external data

rts/Game/UI/EndGameBox.cpp, rts/Game/UI/EndGameBox.h
Added log scale option.
Before:
After:
=> End game graph/log scale

doc/site/articles/wupget-communication.markdown, rts/Lua/LuaHandle.cpp
Unlinked is entirely fine. Engine doesn't complain when trying to call unlinked functions on its own, either.
=> Don't warn for unlinked `Script.LuaXYZ` calls

cont/base/springcontent/gamedata/unit_script_header.lua, doc/changelog.txt, rts/Sim/Units/Scripts/LuaUnitScript.cpp, rts/Sim/Units/Scripts/LuaUnitScript.h
Multi calls as described in https://github.com/beyond-all-reason/spring/issues/1068
It saves about 2-3 microseconds per unit for a unit with many Turn/other invocations. Tested with the walking animation for the dirtbag:
=> implement lua unit script multi-calls

rts/System/Matrix44f.h, rts/System/float3.h, rts/System/float4.h
for easy logging of vector values
for example `LOG_L(L_ERROR, "%s", unit->pos.str().c_str());`
=> add stringify functions to vector and matrix

docker-build-v2/amd64-linux/Dockerfile, docker-build-v2/amd64-windows/Dockerfile, docker-build/Dockerfile
Prereq for https://github.com/beyond-all-reason/spring/pull/1762
=> update dockerfile installed cmake version to 3.27

AI/Wrappers/LegacyCpp/CMakeLists.txt, CMakeLists.txt, rts/build/cmake/ConfigureVersion.cmake, rts/lib/lua/CMakeLists.txt, rts/lib/minizip/CMakeLists.txt, tools/dirchange/CMakeLists.txt
https://github.com/beyond-all-reason/spring/commit/5e604820512b9677a627210ec12537b42b2f47de caused the headless libs to link to the GLEW libraries
While we should use imported targets, for the headless stuff we just want to use the library includes. This PR bumps the cmake version to 3.27 so that we have access to the `COMPILE_ONLY` [generator expression](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#compile-context).
Finally, this PR fixes the issue of linking to GLEW libraries by using this generator expression.
=> Bump cmake version to 3.27 and fix headless linking to GLEW

rts/Rendering/GlobalRendering.cpp, rts/Rendering/GlobalRendering.h
Adds sample shading (needs MSAA to be enabled).
https://registry.khronos.org/OpenGL/extensions/ARB/ARB_sample_shading.txt
https://registry.khronos.org/OpenGL-Refpages/gl4/html/glMinSampleShading.xhtml
Add this to your springsettings.cfg
```
MSAA = 1
MSAALevel = 4
MinSampleShadingRate = 1.0
```
You should immediately notice a lot smoother AA, particularly visible on UI elements. 
Best quality observed with MSAA x4 and minSampleShadingRate to 1.0
MSAA x8 is ridiculously expensive for no perceived added value on my rig.
=> Add sample shading for MSAA (better quality)

rts/Game/Camera/DollyController.cpp, rts/Lua/LuaUnsyncedCtrl.cpp
dollycam stops tracking enemy units that go out of los, and a couple of other items from #1758
=> dollycam should respect the los when tracking units

rts/Rendering/Fonts/CFontTexture.cpp
* Fix linux fontconfig initialization and fallback mechanisms.
* Initialize config with FcConfigEnableHome(false) and FcInitLoadConfigAndFonts. This way system configuration is automatically loaded both on linux and windows and we won't write in user folders out of the spring dir.
* Don't load osFontsDir with FcConfigAppFontAddDir.
* Remove foundry from search pattern since that confuses the search.
* ~~Filter out UKWN and ukwn foundries.~~
* The way to init config I believe should be more robust on windows too, but someone will have to test it to see if it actually works.
* Loading system config can be done later on at CheckGenFontConfigFull, but that requires more changes like loading /etc/fonts/fonts.conf with FtConfigParseAndLoad and removing the CheckFontConfig there as otherwise …
=> Fix linux fontconfig

rts/Game/SelectedUnitsAI.cpp
* Take radar error into account inside SelectCircleUnits.
* Improves circle selection for attack command.
* Also implemented similar changes inside SelectRectangleUnits for consistency.
* Not saying it fixes circular selection since I believe perspective can still make it a bit awkward sometimes at the edges, but at least it won't feel totally random like now.
* Also current situation can leak information since it does use real position.
* **Review carefully** since I could be botching something related to synchronization, I hope not.
* The method is only used by GiveCommandNet[CMD_ATTACK]->SelectAttackNet as far as I can see, so I didn't maintain old functionality. Might want to make a new method instead or have some kind of argument to control radar error usage.
* I'm adding …
=> Take radar error into account inside SelectCircleUnits.

rts/Game/UI/GuiHandler.cpp, rts/Sim/Units/CommandAI/CommandAI.cpp
* Allow centering area commands out of map.
* Allow attacking out of map units.
* Allow guarding out of map units when both the actor and guardee are builders.
* https://github.com/beyond-all-reason/Beyond-All-Reason/issues/763
* I think these actions are safe and wanted, since not being easy to target out of map units with attacks incentivises out of map attack hacks. Regarding the guard issue it's in the above referenced issue.
* Could have maybe touched some more orders but for now these seem the most pressing.
* Still doesn't allow attack ground out of map (in case someone is wondering).
* Also allowing any out of map unit to issue guard orders, don't see why we shouldn't allow this.
=> Out of map orders leniency

rts/Game/TraceRay.cpp, rts/System/GlobalConfig.cpp, rts/System/GlobalConfig.h
* Pass minRayLength into GetQuadsOnRay instead of length.
Length is the length til camera far plane, but minRayLength is actually the length until the ground/water (not sure why it's called minRayLength the name seems a bit misleading).
I believe this to be an error, resulting in querying the quadField for every quad until the end of the map, even when tracing relatively perpendicular. I was testing something else and wondering why TraceRay was tracing so far.
A typical ray trace around the screen will return around 10 quads with this, 50 or more without. It also depends where you are in the map since the more map in front of you more quads will be returned. With the fix the number of quads stays constant as you move around the map since it only depends on where the mouse cursor is, and …
=> Should not GuiTraceRay for quads beyond the floor until the far plane.

rts/Game/CameraHandler.cpp
I ran all the transition modes through switching camera controllers, and the time spring dampened one had an issue
=> time spring dampened transition mode would erroneously rotate when changing camera controllers

doc/site/_data/unsynced_commands.json, rts/Game/UnsyncedGameCommands.cpp, rts/Rendering/CMakeLists.txt, rts/Rendering/DebugDrawerQuadField.cpp, rts/Rendering/DebugDrawerQuadField.h
* Remake of [#1774](https://github.com/beyond-all-reason/spring/pull/1774) that doesn't require compile time option.
* It also doesn't need to modify engine modules, and doesn't cost any perf when not in use.
* Introduces the DebugDrawerQuadField module.
* The other PR needed to check in all GuiTraceRay and selection handler, so it would require lots of checks per draw, I didn't feel good about leaving that always compiled in.
* This one does replicate a bit of GuiTraceRay code in order to draw in the same way.
* I think it's not a big problem, but if controversial, a solution can be to refactor GuiTraceRay so it exports the part we need for this (taking some parameters and return quads). That way the same code could be used by the new DebugDrawerQuadField introduced here and GuiTraceRay. …
=> Add /debugquadfield to draw quadfield related information (v2).

rts/System/ContainerUtil.h
C++23 has std::flat_set which does the same as our VectorUniqueSorted family of functions over std::vector (and there's std::flat_multiset for non-unique VectorSorted), except it guarantees to take care of invariants and is standard. Compiler/stdlib vendors don't yet implement it though so just put a notification under an ifdef that will activate at some point in the future.
=> Annotate our NIH flat_set for the future

rts/Game/PreGame.cpp, rts/Game/PreGame.h, rts/Menu/SelectMenu.cpp, rts/System/SplashScreen.cpp, rts/System/SpringApp.cpp
Apparently (and obviosly in the hindsight) [the previous attempt](https://github.com/beyond-all-reason/spring/pull/1792) worked for local skirmishes only.
The unified approach will use `CPreGame::Draw()` to display what's going on both with the network connection and archives check-summing.
The changes look quite scary, but seem to work fine
=> Another take on archive scanning splash screen

rts/Rendering/Fonts/CFontTexture.cpp, rts/Rendering/Fonts/CFontTexture.h, rts/System/SpringApp.cpp
- Remove duplicate initialization from CheckGenFontConfigFast and CheckGenFontConfigFull.
- now it's all InitFontconfig.
- Better check and report of error conditions on fontconfig initialization and destructor.
- Rework fontconfig initialization since it wasn't doing it well. See [this comment](https://github.com/beyond-all-reason/spring/pull/1793#issuecomment-2511791812) for more info.
- https://github.com/beyond-all-reason/Beyond-All-Reason/issues/3884.
- Fontconfig still loading when `UseFontConfigLib = 0` in use.
- Crashing on destructor in some situations.
The idea here is make the whole thing more robust, this might fix [crashes on linux](https://github.com/beyond-all-reason/Beyond-All-Reason/issues/3884) when fontconfig can't init properly due to environment incompatibilities, or …
=> Fontconfig: Make init and teardown more robust.

rts/Lua/CMakeLists.txt, rts/Lua/LuaHandle.cpp, rts/Lua/LuaTableExtra.cpp, rts/Lua/LuaTableExtra.h, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedCtrl.h
Some Lua extensions (notably, LuaJIT) seem to offer this feature as `table.new`, with the same args we do, and it does feel like a more natural place for it to be. Fixes #1700.
=> `Spring.AllocateTable` -> `table.new`

rts/Rendering/Fonts/CFontTexture.cpp
Better version reusing previous path but with mangled xml.
=> Fontconfig windows workaround v2

rts/Lua/LuaConstEngine.cpp, rts/Lua/LuaSyncedRead.cpp
- Allow negative index at GetUnitCurrentCommand to index from the end of the queue.
- https://github.com/beyond-all-reason/spring/issues/1725
=> Allow negative index at GetUnitCurrentCommand to index from queue end.

rts/Sim/Path/HAPFS/PathDataTypes.h, rts/Sim/Path/QTPFS/PathThreads.h
std::priority_que doesn't guarantee that the sorts it performs is stable. This could potentially lead to a desync between different platforms or build chains.
=> Stablize sorts used by path finders

rts/Rendering/Fonts/CFontTexture.cpp
- Don't preload glyphs for non-alphanumeric fonts
- Forces loading lots of fallbacks in that case so not very useful
- Have this in the `colored-fonts` branch, but doesn't really belong there.
- Fits better into the `fallback-fonts*` branches (just because with that ppl will likely be using more non-alphanumeric fonts), but anyways I think this is stand alone so maybe we can review and merge this independently.
=> Don't preload glyphs for non-alphanumeric fonts.

rts/Lua/LuaSyncedRead.cpp
- Make lua spatial queries work correctly regarding error position.
- For: GetUnitsInRectangle, GetUnitsInBox, GetUnitsInCylinder, GetUnitsInSphere, GetUnitsInPlanes
I understand this might break backwards compatibility, but it could also not be the case (probably not, please read on :)).
I think it's worth it to review and maybe also review games using this to see if they actually will break (only if they tried to workaround the broken implementation... checked a bit and didn't see any cases, but it's possible there are some).
Even when working around previous behaviour, I think their code would still work, just be doing extra work for nothing.
Also, even if working around this in a breaking way, they will be better off by removing the work around, I guess that can be signalled by …
=> Apply radar error to lua spatial queries.

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
* Add Spring.GetUnitCommandCount to get a units command queue count.
* Deprecate getting the count from GetUnitCommands/GetCommandQueue.
* https://github.com/beyond-all-reason/spring/issues/1725
=> Add Spring.GetUnitCommandCount for getting a units command queue count.

rts/Game/Camera/SpringController.cpp, rts/Rml/Backends/RmlUi_Backend.cpp, rts/Rml/Backends/RmlUi_Backend.h, rts/Rml/SolLua/bind/Global.cpp
context handling improvements
* manage contexts in the "contexts_to_remove" hashset more carefully to prevent use-after-free crash.
* Remove context from removal hashset if it is "recreated" in the same frame.
use ranges::rotate to reorder clicked context
fixes #1832
=> RmlUI Context handling improvements

rts/Lua/CMakeLists.txt, rts/Lua/LuaHandle.cpp, rts/Lua/LuaParser.cpp, rts/Lua/LuaTracyExtra.cpp, rts/Lua/LuaTracyExtra.h, rts/Lua/LuaUtils.cpp, rts/Lua/LuaUtils.h, rts/Lua/LuaVFS.cpp
#1215 but in the `tracy.` namespace, 100% free when not using tracy builds,  and no code from `rts/lib/tracy/*` was touched so there won't be any issues with updating the lib in the future.
=> Add `tracy.LuaTracyPlot` and `tracy.LuaTracyPlotConfig`

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Extracted from #1624.
Depends on #1705.
=> Add trace ray ground Lua functions

rts/Game/Camera/DollyController.cpp
The dolly camera needs to move to each position along the track instantly because when the camera smoothness is turned way up it will fail to follow the track
=> Dollycam zero transition time

rts/Game/UI/TooltipConsole.cpp, rts/Game/UI/TooltipConsole.h
Tooltip implementation (the default `/tooltip 1` one that neither BAR nor ZK use) uses resource packs.
Additionally, tweak tooltip layout:
* each resource now on its own line
* move the default location a bit upwards, partially to make room for the above and partially because games tend to put GUI in the very corner
Layout mockup with 8 resources (with 2 it leaves some room at the bottom)
Current for comparison
=> Tooltip resource packs + layout tweak

rts/Sim/Weapons/Cannon.cpp
- Make Cannon respect srcPos on HaveFreeLineOfFire.
I think all other weapons do this.
Looks safe since the only in-engine user is `HaveFreeLineOfFire(GetAimFromPos(preFire), tgtPos, trg)` at [TryTarget](https://github.com/beyond-all-reason/spring/blob/6760620ce1fcec97f846a4a2e87effd411a2b81b/rts/Sim/Weapons/Weapon.cpp#L954). And `GetAimFromPos` for cannon is hardcoded to use weaponMuzzlePos anyways. (see [Cannon.h](https://github.com/beyond-all-reason/spring/blob/6760620ce1fcec97f846a4a2e87effd411a2b81b/rts/Sim/Weapons/Cannon.h#L49)).
Could break lua api users ([GetUnitWeaponHaveFreeLineOfFire](https://github.com/beyond-all-reason/spring/blob/6760620ce1fcec97f846a4a2e87effd411a2b81b/rts/Lua/LuaSyncedRead.cpp#L5443)) but I think those seem fine too (actually the fix is for them) since …
=> Make Cannon respect srcPos on HaveFreeLineOfFire.

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h, rts/Sim/Projectiles/WeaponProjectiles/WeaponProjectile.h
- Add Spring.SetProjectileTimeToLive
- Allows declaring a future frame where the projectile will burn out at any moment, from lua.
- Getter already exists [Spring.GetProjectileTimeToLive](https://github.com/beyond-all-reason/spring/blob/0c3689c3678219f529eb965f4aae91627d1b98ee/rts/Lua/LuaSyncedRead.cpp#L7082).
=> Add Spring.SetProjectileTimeToLive.

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaUtils.cpp
- Make GiveOrder functions accept nil/none for params and options arguments.
- Affected functions:
- GiveOrderToUnit
- GiveOrderToUnitMap
- GiveOrderToUnitArray
- GiveOrderArrayToUnit
- GiveOrderArrayToUnitMap
- GiveOrderArrayToUnitArray
- fixes https://github.com/beyond-all-reason/spring/issues/1821
- This allows skipping the arguments altogether on the calls, like: Spring.GiveOrderToUnit(unitID, CMD.STOP)
- Also allows setting an empty params without passing an empty table, previously it wasn't possible.
- Spring.GiveOrderToUnit(unitID, CMD.SELFD, nil, {"shift"})
- Ppl sometimes passing 0 there to avoid a table, but it's incorrect since it adds a param with value 0.
- Get bar branch https://github.com/saurtron/Beyond-All-Reason/tree/nil-params-or-opts
- Has [some …
=> Accept nil for params and options arguments for Spring.GiveOrder family functions.

rts/Sim/Misc/ModInfo.cpp
Previously defaulted to false for HAPFS and true for QTPFS, so this change reduces interdependency and opaqueness and makes it easier to document.
HAPFS is the default so this won't affect "the" defaults. All known games set hover strafing explicitly, too.
=> `allowHoverUnitStrafing` modrule defaults to false

rts/Sim/Misc/ModInfo.cpp
No logic change (except message wording on hard check failure). The initial chunk now only reads Lua tables which prepares ground for further refactoring (in particular for flattening). Maybe it will be easier to find the constraints as well now they're all in one place.
=> Put modrule checks at the end of modrule parsing

rts/Game/InMapDraw.cpp, rts/Net/Protocol/BaseNetProtocol.cpp, rts/Net/Protocol/BaseNetProtocol.h, tools/DemoTool/DemoTool.cpp
Fixes #1868 
Tested drawing, empty point, and labelled points before and after 64x in singleplayer skirmish and watched a recorded demo of this to ensure they appear in replays.
=> Update NETMSG_MAPDRAW to uint32 on both sides of serialization

rts/Sim/Projectiles/WeaponProjectiles/MissileProjectile.cpp, rts/Sim/Weapons/MissileLauncher.cpp, rts/Sim/Weapons/WeaponDef.cpp
- Make missile weapons pass myGravity from weaponDef to projectiles when set.
- Otherwise (if unset or set to 0.0) will use the map default as usual.
- Passed into projectile in a similar fashion to Cannon.
- Gravity here work's in unison with flightTime/ttl so when time expires the missile will nosedive.
- Gravity value control gives finer extra range control from weaponDef template.
=> Make missile weapons pass myGravity from weaponDef to projectiles.

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
Addresses https://github.com/beyond-all-reason/spring/issues/1877
Copied the function to set resource modifiers, but adapted it to resource storage.
Tested by running Zero-K. Added this gadget which calls the resource set each time a command is issued:
```
function gadget:GetInfo()
return {
name    = "Test gadget for SpringRTS Engine",
desc    = "Test gadget",
author  = "xponen, GoogleFrog, seedship",
date    = "June 12 2014",
license = "GNU GPL, v2 or later",
layer   = 0,
enabled = true,
}
end
if gadgetHandler:IsSyncedCode() then
function gadget:AllowCommand(unitID, unitDefID, teamID)
local m_store = math.random(10, 500)
local e_store = math.random(10, 500)
print("Setting m_store to ")
print(m_store)
print("Setting e_store to ")
print(e_store)
Spring.SetUnitStorage(unitID, "m", m_store) …
```
=> Lua frontend to allow changing unit's storage

rts/Game/UI/KeySet.cpp, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUtils.cpp, rts/System/Log/ConsoleSink.cpp, rts/System/Log/ILog.h, rts/System/Log/Level.h, rts/System/Log/LogUtil.c
- Add new DEPRECATED logLevel
- Make them show up blue at console
- Also move WARNING up to 45 so all current levels have round numbers
- Make recent deprecations use the new level.
- See https://github.com/beyond-all-reason/Beyond-All-Reason/pull/4135 for example of how this is used to show messages at gui just for developers in single player.
Having a good system to communicate deprecated methods to developers is important, it's also important to make it easy for games to filter out such messages for players.
If not properly shown, messages can be either too spammy or too easy to ignore. I think having a specific level together with showing them in a different color at infolog and having games show them for developers only is the way to go.
This way we just "spam" the right people, and …
=> Add DEPRECATED Loglevel

cont/base/springcontent/LuaGadgets/Gadgets/unit_dead.lua, rts/Game/UI/Groups/Group.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedCtrl.h, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h, rts/Sim/Units/Unit.cpp, rts/Sim/Units/Unit.h
- Add noGroup flag for units
- Add lua Get/SetUnitNoGroup
- Implemented this so blocking units being added to groups can be controlled in the same way as to selection
- Units in a group, even if they could be unselectable due to noSelect will affect the group centroid.
=> Add unit::noGroup and Get/SetUnitNoGroup

rts/Sim/Units/Unit.cpp
- Remove the automatic group removal at ForcedKillUnit.
- Currently the unit is removed from groups but not from selection, I think it should either be removed from both, or none.
- Fixable also by allowing to be removed from selection like #1824.
- This is an alternative fix, together with #1853 and maybe adding an example gadget to the engine.
=> Don't remove unit from groups on CUnit::ForcedKillUnit.

rts/Game/GameVersion.cpp
Different commits no longer sync with each other (even if changes are cosmetic) and being a release version doesn't change that.
=> More strict sync check

rts/Sim/Units/Unit.cpp
- isDead unit reaching CUnit::FinishedBuilding makes the game crash on UpdateWind later on.
- For now just bailing out before reaching that
- this could be just a symptom of something else being broken and corrupting more game logic!
Could just skip just the generator part, but looks safe to skip from there on, other parts like calling Activate, ChangeLos or SetStorage seem a bit suspect too if the unit is dead.
Since the problem is the unit is getting killed by lua at eventHandler::UnitCreated right before calling FinishedBuilding not much more we can do than add an isDead fix there. Well, another option would be letting that run, but then making sure it gets removed from wind generators and maybe other places.
- I'll investigate a bit more but for now this may help in hotfixing or …
=> hotfix: Don't run FinishedBuilding side effects for isDead units.

rts/Game/GameVersion.cpp
Returning reference to a constexpr char * creates a null pointer in SpringVersion::GetSync
=> Fix crash in SpringVersion::GetSync

CMakeLists.txt, rts/lib/lua/include/LuaInclude.h, rts/lib/lua/src/lauxlib.cpp
NaNs and Infs are contagious.
Additionally NaNs are not clamped by std::clamp() leading to all sorts of access violations.
In short NaNs should never be accepted from Lua.
=> Error out on NaNs/Infinities coming from Lua.

.editorconfig
We use tabs instead of spaces everywhere.
This should assist developers writing code in convention.
=> chore: Configure editorconfig for lua and c++ files

rts/Sim/MoveTypes/GroundMoveType.cpp, rts/Sim/MoveTypes/GroundMoveType.h
Fixes https://github.com/beyond-all-reason/spring/issues/1878. Zero-K makes a call in repsonse to Arrived event, which changes a waypoint and I failed to account for that in the last change.
Also removed unused member variable.
=> Fix issue with waypoint updates

CMakeLists.txt, rts/CMakeLists.txt, rts/Sim/CMakeLists.txt, rts/System/Sound/CMakeLists.txt, rts/build/cmake/FindSDL2.cmake, rts/builds/dedicated/CMakeLists.txt, rts/builds/headless/CMakeLists.txt, rts/builds/legacy/CMakeLists.txt, rts/lib/headlessStubs/CMakeLists.txt, test/headercheck/CMakeLists.txt, tools/unitsync/CMakeLists.txt
Depends on https://github.com/beyond-all-reason/spring/pull/1737
This adds imported targets for SDL and OpenAL
=> Use cmake import targets part 2

rts/Lua/LuaConstPlatform.cpp, rts/System/CMakeLists.txt, rts/System/Platform/Hardware.h, rts/System/Platform/Linux/Hardware.cpp, rts/System/Platform/Misc.cpp, rts/System/Platform/Misc.h, rts/System/Platform/Win/Hardware.cpp, rts/System/Platform/Win/WinVersion.cpp, rts/builds/dedicated/CMakeLists.txt, tools/DemoTool/CMakeLists.txt, tools/unitsync/CMakeLists.txt
- Add Platform.totalRAM to get total system ram as a number in MB.
- Fixes https://github.com/beyond-all-reason/spring/issues/1640
- not the same name but imo AvailableRAM or FreeRAM should be reserved for smth else reporting actual free ram, that seems a bit trickier tho and possibly not so useful because the number could be misleading, so for now just adding TotalRAM.
- I see games having to parse the hardware string, that seems awkward and fragile.
- Not sure if I'm using the best approach here, _SC_PHYS_PAGES is not POSIX standard, but I hope it won't be a problem. It does seem to be supported in [freebsd](https://man.freebsd.org/cgi/man.cgi?query=sysconf&sektion=3&manpath=FreeBSD+9.1-RELEASE) as well as [linux](https://www.man7.org/linux/man-pages/man3/sysconf.3.html).
=> Platform: add totalRAM.

rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h, rts/System/Sound/ISound.h, rts/System/Sound/Null/NullSound.h, rts/System/Sound/OpenAL/Sound.cpp, rts/System/Sound/OpenAL/Sound.h
- Add Spring.GetSoundDevices(), returning an array of device names.
- Games having to parse infolog.txt, that seems awkward and fragile.
- Thought about naming it Spring.GetSoundDeviceNames(), in case later we want to return tables with more information about devices (number of channels...), but I thought maybe later we can just add another argument to make it return everything: Spring.GetSoundDevices(full).
- Thought about putting this at Platform, but I guess this is not static since devices can come and go.
=> Add Spring.GetSoundDevices.

rts/Sim/Path/QTPFS/Node.cpp, rts/Sim/Path/QTPFS/NodeLayer.cpp, rts/Sim/Path/QTPFS/PathDefines.h, rts/Sim/Path/QTPFS/PathManager.cpp
Reduces the memory consumed by QTPFS by removing a map-wide cache that is maintained for every move type - instead making it only relevant for the specific area being recalculated.
In BAR this change reduces the memory consummed when loading the map, Mediterraneum v1, (a 32x32 map) by about 300MB.
=> Reduce memory usage of QTPFS

rts/Game/SelectedUnitsHandler.cpp
- Don't set selectionChanged or possibleCommandsChanged when nothing actually changed.
=> Make SelectedUnitsHandler be a bit smarter about updating.

rts/Game/UI/ProfileDrawer.cpp, rts/Game/UI/ProfileDrawer.h, rts/System/TimeProfiler.cpp, rts/System/TimeProfiler.h
* Made ProfileDrawer clean up old frame records on Update() instead of Draw()
* this way it's memory usage should in no case go beyond storage of 0.5 seconds of records.
* Before the fix it's up to 30 seconds when minimized if Game.cpp doesnt botch it (see #1741), and **unlimited** otherwise.
* Made TimeProfiler cleanup its own records on Update (run every second)
* Also ProfileDrawer will clean them before drawing to make sure it has the right amount of records since it wants 0.5 sec data.
* Before the fix TimeProfiler can accept threadProfile records even with Drawer disabled when in `/debug on off` mode. In that case records **wouldn't ever be cleaned**.
See https://github.com/beyond-all-reason/spring/issues/1661 for a discussion of the underlying issue and investigation.
Feel free to …
=> Fix leaks inside ProfileDrawer and TimeProfiler.

rts/Sim/Units/UnitHandler.cpp, rts/Sim/Units/UnitMemPool.h
Extracted from @saurtron's code and modified a bit.
=> Future-proofing for CUnit-derived class sizing

rts/Sim/Units/CommandAI/MobileCAI.cpp
=> Unloading: extract transportee choice to a function

rts/Sim/Misc/NanoPieceCache.cpp, rts/Sim/Misc/NanoPieceCache.h
* changed nominal buildpower expiration duration from 1 slowupdate to half a second. This will matter if somebody changes either of these values.
* is now capped at 32 frames, so it compiles even if the nominal duration is higher.
=> Buildpower cache robustness (no logic change)

rts/System/StartScriptGen.cpp, rts/System/StartScriptGen.h
Addresses #1701 by removing two unused values, refactoring the two functions responsible for generating the initial minimal script and updating the comments/docs. The remaining values are required for PreGame-Setup as far as I can tell.
=> Remove redundant values from StartupScripts

rts/Game/UI/MiniMap.cpp
* Minor MiniMap code cleaning
* Retain minimap sharpness in case of SSAA (non-zero MinSampleShadingRate)
* Alternative to https://github.com/beyond-all-reason/spring/pull/1897
=> Crisper minimap in case of SSAA

docker-build-v2/amd64-linux/Dockerfile.20.04
- Update docker docker-build-v2/amd64-linux/Dockerfile to ubuntu 20.04
- The 18.04 dockerfile is too old and starts to have compatibility issues with recent linux distros.
- https://github.com/beyond-all-reason/Beyond-All-Reason/issues/3884
I have checked, and building with the old dockerfile leads to issues (freeze on engine start), after updating seems to work fine both running with the launcher flatpak, and directly from the host os with ./spring.
After building with the new dockerfile the above issue should be fixed, but since I'm not running zorin specifically would have to double check with op. Zorin 17 is based on 24.04 though, the same I'm testing.
- I guess this needs good **testing** and have no idea how to check if this can lead to desyncs. windows docker file seems to be at …
=> Add linux dockerfile for ubuntu 20.04.

rts/Sim/CMakeLists.txt, rts/Sim/Features/FeatureHandler.cpp, rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/CommandAI/BuilderCAI.h, rts/Sim/Units/CommandAI/BuilderCaches.cpp, rts/Sim/Units/CommandAI/BuilderCaches.h, rts/Sim/Units/Unit.cpp, rts/Sim/Units/UnitTypes/Builder.cpp
- Factor out static caches from BuilderCAI
- Just moving code around.
- Part of a bigger effort to allow builder commands to be used by other unit and ai types.
- See https://github.com/beyond-all-reason/spring/issues/1597#issuecomment-2583489746
- See  https://github.com/saurtron/spring/commit/b3acf9aa06a7f2133e2c3c6e61baefd1e6225db5#diff-f07ea03231eeb0aab27b40904941d7c552446b68667f4fca981c77768e59e4a6R421
- static functions may need to be used in other modules in the future
- even if that's not the case also cleaner this way
- This can probably be refactored even more internally to be more flexible in the future
- Will likely need to become a CEventClient to be able to address TODOs there.
=> Refactor BuilderCAI static caches into new BuilderCaches file.

rts/Lua/LuaFBOs.cpp, rts/Lua/LuaOpenGL.cpp, rts/Lua/LuaRBOs.cpp, rts/Lua/LuaShaders.cpp, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaTracyExtra.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUtils.cpp, rts/Lua/LuaVBOImpl.cpp
Restoring this convention as a rule in https://github.com/rhys-vdw/lua-doc-extractor/issues/21. Missed a few in my original doc update.
=> Use `/***` on all lua doc comments

rts/Lua/LuaConstGL.cpp, rts/Lua/LuaOpenGL.cpp, rts/Lua/LuaOpenGL.h, rts/Lua/LuaShaders.cpp, rts/Lua/LuaVBO.cpp, rts/Lua/LuaVBOImpl.cpp, rts/Lua/LuaVBOImpl.h, rts/lib/headlessStubs/gladstub.c
As well as defining GPU zones to achieve functionality very similar to Tracy, but on the GPU. V2
=> Allow adding debug annotations to OpenGL objects.

rts/Game/PreGame.cpp, rts/Game/UI/InfoConsole.cpp, rts/Rendering/Textures/Bitmap.cpp, rts/System/FileSystem/FileSystemInitializer.cpp, rts/System/FileSystem/FileSystemInitializer.h, rts/System/SpringApp.cpp
Addresses https://github.com/beyond-all-reason/spring/issues/1903
=> Enable command line argument to produce an archive checksum to the headless/normal engines

rts/Sim/MoveTypes/GroundMoveType.cpp, rts/Sim/MoveTypes/Utils/UnitTrapCheckUtils.cpp, rts/Sim/MoveTypes/Utils/UnitTrapCheckUtils.h, rts/Sim/Units/UnitDefHandler.cpp, rts/Sim/Units/UnitDefHandler.h
Currently the engine has to get a global counter for the number of push resistant move types, and then if the count is greater than one then all units that start moving have to check if they are stuck.
With the trap check system introduced when fixing the issue with wrecks, we can now use that same system for units with push resistance. This means that only when push resistence creates a situation that may lead to it trapping another unit does any checks need to be carried out, which saves on the unneccessary checking for all units whenever they execute a move command.
This also allows for the removal of the global counter for push resistant move types.
This change has the added benefit of allowing units trapped mid-move by a push resistant unit stopping (and creating a blocked zone …
=> Switch push resistant units to use trap check system

rts/Sim/MoveTypes/HoverAirMoveType.cpp, rts/Sim/Units/CommandAI/AirCAI.cpp, rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/CommandAI/Command.h, rts/Sim/Units/CommandAI/CommandAI.cpp, rts/Sim/Units/CommandAI/CommandAI.h, rts/Sim/Units/CommandAI/MobileCAI.cpp
* Fix occasional crash in CBuilderCAI::ExecuteBuildCmd() caused by a dangling other command, the reason for such commands to dangle is unknown for now
* Actually assign commands in CCommandAI::inCommand instead of specifying boolean flag, will help debug the above
* C++ pass on CMD_ and other related constants
=> Fix occasional crash in CBuilderCAI::ExecuteBuildCmd()

.github/workflows/bar-cdn-publish.yml, .github/workflows/engine-build.yml, .github/workflows/release-build.yml, docker-build-v2/scripts/package.sh
A new release workflow that uses v2 engine build to create new releases.
- Releases contain standard engine build but also Tracy enabled build
- Optionally allow to create a new annotated tag right when triggering release
- Workflow doesn't use other workflow artifacts, but builds from scratch leveraging caching: This is quite useful because now the commit in release is the commit engine was build at, and not e.g. like here: https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7Bmaster%7D105.1.1-2701-g8e52d29
There is a change in how release tags and artifacts are named. Best see example output https://github.com/p2004a/spring/releases/tag/recoil%7Bmaster%7D2025.01.2-93-g44d2480.
=> Create new engine release workflow

rts/Lua/LuaUnsyncedCtrl.cpp
Changes:
- Removed an instance of the `NO-BREAK SPACE` character.
- Tidied up the `SendMessageToSpectators` docs using proper markdown.
NOTE: I also searched the entire codebase for other instances of that character. This is the only one I found in code files.
=> Rhys vdw/fix irregular whitespace

docker-build-v2/README.md, docker-build/README.md
- Adds Disclaimer for V1 to mention being dated and pointing to V2
- Adds a Section to guide Windows users to start building the engine with V2
=> Docker Build V2 Windows Guide + V1 Disclaimer

rts/Rendering/Fonts/CFontTexture.cpp
- Pass original font to GetFontForCharacters, instead of the latest tested font
- GetFontForCharacters is supposed to get the original font we're looking for alternatives for. Here we were passing the latest tested alternative instead.
- This shouldn't be a very big issue, but it's incorrect, and also seems like some fonts take a lot longer to query through `FcFreeTypeQueryFace`, this can make `LoadWantedGlyphs` take an order of magnitude longer.
=> Pass original font to GetFontForCharacters, instead of the latest tested font

rts/Rendering/Fonts/CFontTexture.cpp
- Perform an intersection of the searched glyphs against the fontconfig pattern glyphs
- This avoids expensive computations (like actually loading the font with freetype) just to see the glyph isn't there.
- The information is already present in the fontconfig pattern returned by FcFontSetSort and FcFontSort.
=> Perform an early glyph match with the fontconfig pattern glyphs.

.github/workflows/generate-lua-library.yml, .github/workflows/publish-site.yml, doc/emmlua-doc-cli-template/lua_enum_template.tl, doc/emmlua-doc-cli-template/lua_global_template.tl, doc/emmlua-doc-cli-template/lua_global_template_simple.tl, doc/emmlua-doc-cli-template/lua_module_template.tl, doc/emmlua-doc-cli-template/lua_type_template.tl, doc/site/README.md, rts/Lua/LuaConstCMD.cpp, rts/Lua/LuaConstCMDTYPE.cpp, rts/Lua/LuaConstCOB.cpp, rts/Lua/LuaConstGL.cpp, rts/Lua/library/.luarc.json
- Document enums/fields with `/*** @field Enum.Entry */` (that I feel will be more maintainable).
- Update `@field` output to be compatible with `emmylua_doc_cli`, adding visible descriptions.
- Improve Lua API templates in general (remove excess HR elements).
- Improve Lua API enum template: Heading and markdown formatted description for each enum value.
=> Improve Lua docs for enums and fields.

rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUtils.cpp
- Fix duplicate `@alias Facing` definition:
- Create `FacingInteger` with `0|1|2|3`.
- Keep `Facing` alias which accepts various strings.
- Update Lua doc annotations to accept the correct aliases.
- Use C++ `FACING_*` enum in `ParseFacing`.
---
This one contains minor C++ cleanup so I'd prefer a review before merging.
=> Lua: Clean up use of Facing enum

rts/Game/PreGame.cpp
`std::int64_t` can be either `long` or `long long` depending on compiler etc., so cannot assume one or the other via `%ld` or `%lld`.
=> Fix a printf format warning

cont/base/springcontent/shaders/GLSL/ModelFragProg.glsl, cont/base/springcontent/shaders/GLSL/ModelVertProg.glsl, rts/Game/UnsyncedGameCommands.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Rendering/Common/ModelDrawer.cpp, rts/Rendering/Common/ModelDrawer.h, rts/Rendering/Common/ModelDrawerHelpers.cpp, rts/Rendering/Common/ModelDrawerState.cpp, rts/Rendering/Env/CubeMapHandler.cpp, rts/Rendering/Units/UnitDrawer.cpp
There is practically very little perf difference between the two states.
Fixes https://github.com/beyond-all-reason/spring/issues/2027
=> Deprecate AdvUnitShading setting and /AdvModelShading runtime switch.

rts/Rendering/Units/UnitDrawer.cpp
- Remove drawing of ghost icons when ScreenIcons is disabled.
- https://github.com/beyond-all-reason/spring/issues/2031
=> Don't draw ghost worldview icons for 'iconsAsUI 0'.

rts/Game/UnsyncedGameCommands.cpp, rts/Rendering/GL/glDebugGroup.hpp, rts/Rendering/GlobalRendering.cpp
Add some rigor into what kind of MsgID OpenGL debug push/pop groups end to the debug function, add possibility to enable/disable debug groups from the console and springsettings, and while on it hook DebugGLStacktraces to it as well
=> Minor, but important debuggl QoL improvements.

rts/Sim/Path/QTPFS/PathSearch.cpp, rts/System/float3.h
While it is hard to get an exact reading from a laptop, these changes are yielding a measurable performance improvement for long-distance QTPFS path finding requests. I'm seeing at least a 10% improvement, some measurements indicate maybe upto 25% improvement.
Note: I plan to do some separate clean up of the code. I haven't done it here because it involves clearing out other areas of the code at the same time, which would obfusicate the changes here.
=> Apply optimizations for the innermost loop of QTPFS path searching

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/library/Types.lua
=> Correct lua typing of `xyz`, `rgb` etc.

rts/Rendering/Fonts/CFontTexture.cpp, rts/Rendering/Fonts/CFontTexture.h
- Add a general list of recently used FontFace references.
- At the moment non-main fonts don't get any shared_ptr stored, so they get immediately evicted from LoadFontFace caches.
- happens to game fallback fonts, that get used to load extra glyphs.
- and also other fonts (system fallbacks) that don't get used, but get loaded while searching.
- This is very bad since some methods like SplitTextInWords call GetTextWidth, eventually loading fonts all the time when needing new glyphs (and doing so incrementally: increasing the sentence by 1 char each time, in a worst case scenario kind of usage relative to fallback searches).
- loading fonts is an expensive operation
- Caching infrastructure is already in place, but need to pin the shared_ptr somewhere, either while we expect the font to …
=> Make sure recently/often used fonts don't get evicted from cache.

rts/Lua/LuaArchive.cpp, rts/Lua/LuaVFS.cpp
Closes #1960 
NOTE: Full documentation for the VFS table has been copied, but fails to render to docs due to upstream error. Bug report: https://github.com/CppCXY/emmylua-analyzer-rust/issues/269
TODO:
_Can merge as soon as tests pass_
=> Document VFS

rts/Rendering/Fonts/CFontTexture.cpp, rts/Rendering/Fonts/CFontTexture.h, rts/System/SpringApp.cpp
- Introduce MaxPinnedFonts config variable to allow max pinned fonts to be tweaked.
- Should be configurable in case 10 is too low.
- Had to move PinFonts to CFontTexture statics.
- Maybe should move cache itself as well as other recently introduced config variables there too since they probably fit better, but I think better to do incrementally, to make easier to review and also since making this configurable is still kind of critical, while code refactor can take longer to review, see https://github.com/beyond-all-reason/spring/issues/2066 for more details of the planned steps to be taken.
=> Make maximum number of pinned fonts configurable through MaxPinnedFonts.

rts/System/FileSystem/ArchiveScanner.cpp
Only scan pool files for their existence for 5 seconds max and make sure that eventually the cache becomes consistent, also only bother scanning in case the number of cached files is >= 10000
=> Add deadline target for pool files scanning

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
=> Add Spring.GetProjectilesInSphere

.github/workflows/generate-lua-library.yml
Didn't realize it would choke on multiline.
=> Library generation: Fix bad commit message handling

rts/Rml/SolLua/bind/Context.cpp
Data models will be set dirty when assigning to nested tables. For example, `datamodel_handle.table1.table2.value = 3`
=> add deep reactivity to rmlui data models

rts/Rml/Backends/RmlUi_Backend.cpp, rts/Rml/CMakeLists.txt, rts/Rml/SVG/ElementSVG.cpp, rts/Rml/SVG/ElementSVG.h, rts/Rml/SVG/SVGPlugin.cpp, rts/Rml/SVG/SVGPlugin.h, rts/lib/CMakeLists.txt
The builtin svg plugin can only render svg from files. There is a desire to render svg that is created inside the widget for graphs. So this is a copy of the builtin plugin with a change to allow for the svg string to be changed using the src attribute:
```cpp
if (path.starts_with("<")) {
svg_data = path;
} else {
// normal file import
```
usage:
```lua
<svg id="svgi" width="700" height="700"></svg>
local image = [[<svg>
<path ...
]]
svgi = document:GetElementById("svgi")
svgi:SetAttribute("src", image)
```
=> rml svg plugin that can render dynamic svg

.github/workflows/generate-lua-library.yml, .github/workflows/publish-site.yml
The workflows can still be executed manually on forks, but they should not be automatically executed.
cc @rhys-vdw
=> Run workflows that commit and publish things only in upstream

cont/LuaUI/callins.lua
Can't find any reference to these callins. As far as I can tell no longer exist.
More discussion here:
https://github.com/beyond-all-reason/spring/pull/2118#issuecomment-2766635058
=> Remove old Draw* callins that no longer exist

rts/Rendering/Units/UnitDrawer.cpp, rts/Rendering/Units/UnitDrawer.h, rts/Rendering/Units/UnitDrawerData.cpp, rts/Rendering/Units/UnitDrawerData.h
- Fix dead ghost icons appearing for specs.
- they don't see the ghosts so shouldn't see the icons either
- Fix "dead" and "alive but not under radar" ghost icons being indistinguishable from  regular radar icons.
- achieved this by making them show more dimmed
- Make the dimming configurable through UnitGhostIconsDimming config option
- Also setting to 0 allows disabling icons for ghosts not under radar (first step to fix ([#641](https://github.com/beyond-all-reason/spring/issues/641))
- Apply some cosmetic changes for consistency between DrawUnitMiniMapIcons and DrawUnitIconsScreen code.
- https://github.com/beyond-all-reason/spring/issues/2031
- https://github.com/beyond-all-reason/spring/issues/2032
- https://github.com/beyond-all-reason/spring/issues/641
how specs see it (click to …
=> Ghost icons fixes 2

rts/CMakeLists.txt, rts/builds/headless/CMakeLists.txt, rts/builds/legacy/CMakeLists.txt
Refactor CMake files to incrementally introduce targets. The initial attempt using the blank card approach proved challenging and error-prone - #2043. This commit adopts a step-by-step strategy, starting with the extraction of targets in phases. By the end of the process, each sub-directory containing source files will have its own dedicated target. This commit focuses on refactoring one of the largest source sets - 'Game'.
=> Extract Game as a target in cmake

doc/site/README.md, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaVBO.cpp, rts/Lua/LuaVBOImpl.cpp
- Minor cleanup to `SelectUnitArray` and `DeselectUnitArray` docs.
- Add an overload to `Spring.GetTeamList()` that ensures a non-nil return value with no arguments.
- Remove my use of unions of GL values (not supported by LLS).
- Restore `&&` in the example commands to regenerate docs (so you can press up array to do it again after pasting into CLI)
=> More fixes to Lua docs

rts/Lua/LuaConstGL.cpp
These are defined twice:
https://github.com/rhys-vdw/spring/blob/c325950cb6df0b0ae70eaf2606e4f76adf857e4a/rts/Lua/LuaConstGL.cpp#L334-L339
https://github.com/rhys-vdw/spring/blob/c325950cb6df0b0ae70eaf2606e4f76adf857e4a/rts/Lua/LuaConstGL.cpp#L346-L347
This clears the last error from `lua-language-server --check` on the output library.
=> Remove duplicate GL constants

rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaShaders.cpp, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaVBOImpl.cpp
- Fix some incorrectly annotated varargs e.g. `arg1, arg2, argn`.
- Add overloads to clarify arguments on a couple of callbacks.
- Mass replace `number` -> `integer` for all parameters with name ending in "ID".
=> Many more Lua fixes

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedRead.cpp
- Link some methods currently unlinked in lua.
- LuaSyncedCtrl::SetProjectileTimeToLive
- LuaSyncedRead::GetUnitSeismicSignature
- Checked all methods at Synced/Unsynced/Read/Ctrl, and these are the only ones I found.
- One I added myself, not sure how that could have happened, sorry about that :P.
- Tested the methods since being unlinked wasn't sure if they were tested originally
=> Link SetProjectileTimeToLive and GetUnitSeismicSignature lua methods.

cont/base/springcontent/LuaGadgets/Gadgets/control_guard.lua, rts/Sim/Units/CommandAI/AirCAI.cpp, rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/CommandAI/MobileCAI.cpp, rts/Sim/Units/Unit.cpp, rts/Sim/Units/Unit.h
- Remove the max time for out of map guards.
- Add sample gadget `control_guard.lua`, games can use to keep old behaviour through lua, but letting builders guard.
- Actually a bug, since https://github.com/beyond-all-reason/spring/pull/1769 was supposed to remove such restrictions.
- completely overlooked this, sorry about that.
- Still, to keep current engine behaviour through lua, it becomes a bit more complicated for games to manage the timer:
- See [here](https://github.com/saurtron/Beyond-All-Reason/commit/8adb876482914b1aef4d4db307acb6f280569f5f) for how I adapted bar code to check that. Not too bad, but a bit overcomplicated given the difficulty in tracking units current command.
- Given there are other safeguards not sure if just removing this and ignoring in-game for now may be …
=> Remove the max time for out of map guards.

rts/Rml/Backends/RmlUi_Renderer_GL3_Recoil.cpp
This PR fixes an issue with RmlUi widget being super blurry when AA is in use. It's particularly blurry when SSAA is activated.
Before
After
=> Fix RmlUi getting blurry when using AA

rts/Sim/Units/CommandAI/FactoryCAI.cpp
DRAFT for now since just a way to show what the problem is while we discuss and find the best way to fix the problem. (the provided fix can be used to run the replay and prove the issue, and might be the best solution without changing std::deque for something different)
- Avoid endless STOP processing in CFactoryCAI::SlowUpdate
- [This replay](https://www.beyondallreason.info/replays?gameId=dec4ef6725cef4ecc38ae3a34469e952) shows a situation where the game is effectively frozen for a long time (== minutes) due to a unit processing 33k+ stop commands.
- This is the light green player queing 33k grunts at factory id 24010, and then trying to clear, that internally does dequeing.
- This happens because GiveCommandReal with RIGHT_MOUSE option does a deque of specific cmdID by replacing them …
=> Avoid freeze from endless STOP processing at FactoryCAI.

rts/lib/glad/glad.c
Intel drivers present themselves with quite low (3.0) OpenGL version on compatibility profile.
This leads to GLAD not loading any function pointers, for functions formally belonging to OpenGL versions > 3.0.
In fact many/all? such functions are exposed by the driver, so disable explicit check for supported version in `gladLoadGLLoader()` and just load what can be loaded.
This is easier than renaming all "advanced" functions to their ARB counterparts.
=> Fix Intel OpenGL crashes?

rts/Game/Game.cpp
- Return handled status from GotChatMsg at CGame::ProcessAction.
- Removes FIXME, but useless otherwise since nobody using the result from ProcessAction atm.
- Could be used at `CGame::ProcessCommandText`, but the return value seems to be more just to see if it was a command, not if the command was processed.
- I think luaUI and luaMenu can't both exist at the same time, otherwise would need to `|=` the result from both instead of `return true` on first match.
=> Return handled status from GotChatMsg at CGame::ProcessAction.

rts/Rendering/Env/Particles/ProjectileDrawer.cpp
- Skip error ProjectileDrawer error log on headless
- Could instead introduce a new log level L_HEADED_ERROR or similar, mapped to L_ERROR when not headless, and to L_INFO on headless.
- Unless this pops up in many places, don't think that would be wanted, but let me know if you prefer it.
- The situation is harmless in headless.
=> Avoid ProjectileDrawer initialization error log on headless.

rts/Sim/Units/UnitLoader.cpp
- Change definition of /give command since the error message now is misleading.
- It did work without spaces, since sscanf ignores whitespace as @sprunk noted.
- Didn't have the spaces originally, but they were added here: 381c1ddabc62b6746c9b83a4da4b1bfd13f1a71e
- Commit doesn't have a description so can't say exactly what was the intent.
- Warnings need to be fixed, sscanf format string could be kept, but I think better to change it too, to make the code more immediately understandable without being aware of sscanf quirks here.
using BAR:
- `/cheat on`
- `/give armpw @3000,100,3000`
It's how it works both before, and after this patch, `/give armpw @3000, 100, 3000` wouldn't work in either situation.
=> Fix /give command position argument.

.github/workflows/check-lua.yml
Add workflow to check that Lua library is valid.
- Checks that lua-doc-extractor succeeds.
- Does type check and static analysis via lua-doc-extractor (will report references to non-existent types and other misconfigurations).
- **Does not** check that emmylua-doc-cli succeeds (should be fine so long as the above works, I've yet to see it error ever). If it's a problem we can add it later.
Example of failure: https://github.com/rhys-vdw/spring/pull/1
Note #2124 must be merged first this since it fixes the last Lua errors.
Closes #1760
=> Add check lua workflow

rts/ExternalAI/AICallback.cpp, rts/Game/Game.cpp, rts/Game/Game.h, rts/Game/GameControllerTextInput.cpp, rts/Game/GameControllerTextInput.h, rts/Game/UnsyncedActionExecutor.h
- Remove unused `keyCode` and `scanCode` arguments from Action processing
- Removed `key` property of `UnsyncedAction` (unused)
- Cherry-picks from @MasterBel2 https://github.com/beyond-all-reason/spring/pull/893
- I think this is a harmless change, and good to have since those parameters are unused so just a cleanup.
- Also included at https://github.com/beyond-all-reason/spring/pull/2166
- the idea is divide the 4 commits there in 1-3 PRs and get them in independently, since those don't depend on my other input work.
=> Remove unused action related arguments

rts/Game/Game.cpp, rts/Game/UnsyncedActionExecutor.h, rts/Game/UnsyncedGameCommands.cpp, rts/Game/UnsyncedGameCommands.h
- Cherry pick more @MasterBel2's commits (with small tweaks, see below).
- Gives Actions the capability to process ActionRelease.
- Refactors UnsyncedGameActions::ActionRelease and put it's code into the appropriate actions.
Note, while this adds some engine capabilities, it can be considered pure refactor and not affect engine behaviour at all. It just adds the way to forward ActionReleased to UnsyncedGameActions so they can be more self contained (before this pr, ActionReleased was just a big method doing ad-hoc out-of-action code).
Adapted from @MasterBel2's: [Move ActionPressed and ActionReleased from CGame to `UnsyncedGa…](https://github.com/beyond-all-reason/spring/pull/893/commits/17f84a5cdb406aa04bc13814f49d8e5a1fc71e7d)
Here, differing a bit from MasterBel's, instead of …
=> IUnsyncedActionExecutor processing of ActionRelease events.

rts/Rendering/Fonts/CFontTexture.cpp
- Fix by using the fontconfig font family before origPattern expires and wipes data.
- Fixes: https://github.com/beyond-all-reason/spring/issues/2203
=> Fix fontconfig use after free on game start

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaUnsyncedCtrl.cpp
- Add missing pairwise param
- Fix return types
- Use better param descriptions
- Use correct Command type
- Also fix return value from `LuaUnsyncedCtrl::GiveOrder`
=> Fix GiveOrderArrayToUnitArray Lua docs

rts/Rendering/Fonts/glFont.cpp
- Change default big font outline width to 2
- Makes it render like pre 2025.03 releases.
- Fixes https://github.com/beyond-all-reason/spring/issues/2175
- Previous blur algo bug was making 3 here render like 2.
- Now it renders correctly, but 3 looks too thick, thus to make engine maintain (default) behaviour we should change this to 2.
- If possible this should go into 2025.03 release, since changing the width is affecting games, and a change in behaviour that's usually best to avoid.
=> Change default big font outline width to 2.

rts/Lua/LuaUnsyncedRead.cpp, rts/Lua/LuaUnsyncedRead.h
- Add Spring.GetMouseButtonsPressed
- No other way to get state of buttons 4+ atm from lua, afaics.
- Could instead add to Spring.GetMouseState, but that one already has too many return values.
- Still if you prefer could do this, maybe controlled through an input parameter to control how many extra buttons to return at the end.
- Could make expanding Spring.GetMouseState trickier later, like maybe we want to query for a different mouse, or some other return parameter need to be added.
- see the [comment below](https://github.com/beyond-all-reason/spring/pull/2167#issuecomment-2797060315) by @sprunk for more ideas we considered about possible API for this.
=> Add Spring.GetMouseButtonsPressed

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaUnsyncedCtrl.cpp, rts/Lua/LuaUtils.cpp
> Looks fine, btw looked at the `timeout` parameter, and it's a deadline frame number.
> 
> Seems like for MobileAI and AirCAI this makes the command be finished if it's in front of the queue and current frame number already greater. Probably related to not being able to reach the command destination logic.
> 
> Skirmish AI might also be using it but probably not relevant here.
> 
> Only seen it used in two places (other than skirmish ai), by looking for timeOut and GetTimeOut.
https://github.com/beyond-all-reason/spring/pull/2195#pullrequestreview-2771778767
**cc** @saurtron clear enough?
=> Document `timeout` parameter.

.github/workflows/check-lua.yml
Other workflows only require major version of `lua-doc-extractor`. This change syncs the check workflow with the others ([`publish-site.yml`](https://github.com/beyond-all-reason/spring/blob/604f00d290a2e3ddbc2fae9f27f10b9c8efedc0a/.github/workflows/publish-site.yml#L30), [`generate-lua-library.yml`](https://github.com/beyond-all-reason/spring/blob/604f00d290a2e3ddbc2fae9f27f10b9c8efedc0a/.github/workflows/generate-lua-library.yml#L30)).
This is safe because I control the version numbers and won't bump major version unless it actually breaks back-compat.
=> Use same version of lua-doc-extractor on all workflows

rts/Rml/SolLua/bind/Context.cpp
Since the rmlui data model handle doesnt support iteration or array indexing, we can expose the backing table.
=> expose the table that backs the rmlui data model handle

rts/Lua/LuaConstCMD.cpp
- Document STOP, ATTACK, REMOVE commands, and the CMD table.
- Set a standard for documenting Commands the project can use for the future.
The main idea here is about where to put the commands documentation, and best format to use, so please comment on that, specially if you have any objections.
We need to define:
1. Where to put the documentation
- If doing it right, it will appear both in editor tooltips, and webpage
- Seems the best place is rts/Lua/LuaConstCMD.cpp, as recommended by @rhys-vdw 
2. A standard "template" for documenting actions
- The idea is do it through documenting a few actions in this PR
- Some things will need developing of the LLS->html or LLS typing language.
- Talked with @rhys-vdw about what could be the best way to document commands, so they will appear at the …
=> Command Documentation Standard

cont/cmdcolors.txt, rts/Lua/LuaConstPlatform.cpp, rts/Rendering/GL/glExtra.cpp, rts/System/Platform/CpuID.cpp, rts/System/Platform/CpuID.h, rts/System/Platform/Threading.cpp, rts/System/Platform/Threading.h
There isn't much point in drawing them if their alpha is set to zero, right? This is relevant in BAR where attack range rings are fully widget-controlled.
=> Dont draw surface and ballistic circles if their alpha is set to 0.0

rts/ExternalAI/AICallback.cpp, rts/Lua/LuaPathFinder.cpp, rts/Sim/Ecs/Registry.cpp, rts/Sim/Ecs/Registry.h, rts/Sim/Ecs/SaveLoadUtils.h, rts/Sim/Path/HAPFS/PathManager.cpp, rts/Sim/Path/HAPFS/PathManager.h, rts/Sim/Path/IPathManager.h, rts/Sim/Path/QTPFS/Components/Path.h, rts/Sim/Path/QTPFS/Path.h, rts/Sim/Path/QTPFS/PathCache.cpp, rts/Sim/Path/QTPFS/PathCache.h, rts/Sim/Path/QTPFS/PathManager.cpp, rts/Sim/Path/QTPFS/PathManager.h, rts/Sim/Path/QTPFS/PathSearch.cpp, rts/Sim/Path/QTPFS/Registry.cpp, rts/Sim/Path/QTPFS/Registry.h, rts/Sim/Path/QTPFS/Systems/PathSpeedModInfoSystem.cpp, rts/System/Ecs/Utils/DoubleLinkedList.h, rts/System/Ecs/Utils/SystemGlobalUtils.h
This addresses the issues seen in Zero-K pertaining to desync rate increases. HAPFS and QTPFS are both fixed.
A mistake on my part, I falsely believed that widgets were not permitted to request paths, only gadgets. The HAPFS desync happened because the unsynced path requests would populate the sync path results cache, which would cause a desync after a while. HAPFS is fixed by making sure unsynced paths are correctly labelled as such so they can use the correct separate cache.
The QTPFS desync was because the unsynced paths would be added and removed, which could cause the order of the synced paths to be changed. This wouldn't normally be an issue, but we have an optimization on dirty paths where we repath a part of the list of dirty paths per frame (to balance per frame loading) and a …
=> Fix desyncs caused by unsynced pathing requests

rts/Rendering/Fonts/TextWrap.cpp, rts/Rendering/Fonts/TextWrap.h, rts/Rendering/Fonts/glFont.h
- Added a leading call to ScanForWantedGlyphs inside TextWrap::SplitTextInWords.
This avoids repeated calls into `CFontTexture::LoadWantedGlyphs` for every letter, thus potentially saving a lot of researching for glyphs/fallbacks.
=> Fonts textwrap prescan for glyphs

rts/Game/Game.cpp, rts/Game/Game.h, rts/Game/GameController.h, rts/Game/UI/KeyCodes.cpp, rts/Game/UI/KeyCodes.h, rts/Game/UI/MouseHandler.cpp, rts/Game/UI/MouseHandler.h, rts/Game/UI/ScanCodes.cpp, rts/Game/UI/ScanCodes.h
- Allow binding of mouse buttons to actions.
- Enable binding for buttons 4+.
- Fixes https://github.com/beyond-all-reason/spring/issues/2059
(see at the bottom for other issue and PR references)
- Talked to both @badosu and @MasterBel2 about this, since they're interested in the issue and particularly @MasterBel2 did some [overlapping work](https://github.com/beyond-all-reason/spring/pull/893)
- They seem to be ok with going the route this PR starts, but pls voice your ideas/complaints otherwise.
- Was specially worried about @MasterBel2's patch overlap, but I think we both agree that one needs splitting anyways, and we can incrementally add code to try to fix/support any use cases he has, possibly taking code from his PR in the future.
- PR'ing this simplistic version since I think it's …
=> Mouse button binds.

rts/Sim/Misc/Resource.cpp
The 'separate' variable was not CREG'd like the other variables in the struct. This adds it to CREG for consistency.
https://github.com/beyond-all-reason/RecoilEngine/blob/b272b93d5a4704d35642f360356385d28da033b7/rts/Sim/Misc/Resource.h#L122-L123
Note: This will conflict with PR #2271 if it gets merged.
=> Add missing creg to variable for consistency

rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.cpp, rts/Rendering/Env/Particles/Classes/BitmapMuzzleFlame.h
Addresses https://github.com/beyond-all-reason/RecoilEngine/issues/2252
Adds:
```
float particleSpeed;
float particleSpeedSpread;
float airdrag;
float3 gravity;
```
=> First draft of enabling the additional physical parameters for CBitmapMuzzleFlame.

cont/LuaUI/widgets.lua
The `GetWidgetInfo` function currently does nothing due to the insertion of an immediate `return` call before the rest of the function's body. See #1680 for my analysis of what the function would do without that early return.
Given that this function has been disabled in this way since 2008, the proposed solution is to simply delete the function.
=> Remove unused GetWidgetInfo function

rts/Lua/LuaSyncedRead.cpp
- Deprecate Spring.GetCommandQueue in favour of Spring.GetUnitCommands
- Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2272
=> Deprecate Spring.GetCommandQueue.

rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandleSynced.cpp
- Document registering the different callins requiring use of SetWatchAllowWeapon, SetWatchProjectile or SetWatchWeapon.
- The Spring.SetWatchAllowWeapon, etc methods need to be documented as well but I'll add as part of a different PR.
=> Document registering AllowWeapon and Projectile callins.

rts/Lua/LuaVFS.cpp
- Fix incorrect mention of base64 hashes for sha512, they're actually hex
- Tested it to make sure, since specially didn't find the CalcHash function in use by md5 xd.
- We might want to fix the return instead to base64, hex is quite unwieldy here, could break smth tho.
```lua
Spring.Echo(VFS.CalculateHash("teststring", 0), VFS.CalculateHash("teststring", 1))
=> 1nxcv1sByfkZMuO43vXl+A==, 6253b39071e5df8b5098f59202d414c37a17d6a38a875ef5f8c7d89b0212b028692d3d2090ce03ae1de66c862fa8a561e57ed9eb7935ce627344f742c0931d72
```
=> VFS.CalculateHash: Sha512 actually gets hex encoded.

rts/Lua/LuaHandle.cpp
Software rendered cursors are overdrawn, hardware cursors are not
Related to https://github.com/beyond-all-reason/RecoilEngine/issues/2291
=> Document DrawScreenPost gotcha

rts/Lua/LuaHandleSynced.cpp
- Allow sending tables inside SendToUnsynced.
- Apparently this is all that's needed, but I might be overlooking something, I did test it and just works.
Receiving of a recursive table:
```lua
[t=00:00:23.623310][f=0000089] testCommand, <table>
[t=00:00:23.623383][f=0000089] {
a=1,
b=2,
c={
a2=2,
a3=<recursive_reference>,
},
}
```
=> Allow tables inside SendToUnsynced.

rts/Lua/LuaOpenGL.cpp, rts/Lua/LuaOpenGL.h
- Add POINT_SMOOTH const and query capability.
- In some situations users might need to set/query/restore the POINT_SMOOTH to avoid points rendering as squares.
- Unsure if this is wanted since I guess modern opengl doesn't recommend drawing points like that, or maybe it's even deprecated, but couldn't find where it says to be deprecated so proposing this since it can be needed to easy fix widgets rendering points as squares on some gfx cards (like ping wheel).
- This isn't strictly needed, but specially the query capability is important so state can be restored and not break anything for others. I'm guessing it must be disabled generally, but can't know for sure without being able to query.
- Didn't add a setter since it can be awkwardly done through `gl.UnsafeState`, but could add it …
=> LuaOpenGL: Add POINT_SMOOTH const and query.

rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandle.h, rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaHandleSynced.h
- Allow the lua `debug` module for `/DevMode 1`
- https://github.com/beyond-all-reason/RecoilEngine/issues/867
- Loosely based on previous effort by @lhog
- Difference is I implemented a method so we export an empty `debug` table, and fill or remove the methods as DevMode is enabled and disabled.
- This is needed, since otherwise the wupgets don't get the "new" debug module linked into gadget/widget environment, probably because of how games (probably basecontent, but at least BAR) link environment into widgets/gadgets... it doesn't appear after DevMode is enabled and needs a reload.
- This solution doesn't help much with security, other than ensuring debug module itself is empty/filled, obviously ppl can link the methods when enabled and the references will still work. Still should make …
=> Lua debug module for synced when DevMode=1

.github/workflows/engine-build.yml
This is to ensuse that package index is available on the system before we try to install something.
=> Add apt update to workflow

rts/Lua/LuaFonts.cpp, rts/Lua/LuaOpenGL.cpp, rts/Rendering/Fonts/glFont.cpp, rts/Rendering/Fonts/glFont.h, rts/Rendering/Fonts/glFontRenderer.cpp, rts/Rendering/Fonts/glFontRenderer.h
- Allow rendering fonts without automatic setting of the glBlendFunc to `(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)`)
- Through new `userDefinedBlending` argument for `LuaFont:Begin`, `LuaFont:SubmitBuffered`, `gl.BeginText`.
- This is needed so advanced blending can be done with fonts.
- Required when rendering to a texture with alpha that afterwards needs to be rendered into screen.
- Sometimes also premultiplied alpha can be used, but that will need further changes, so the shader can either sometimes draw with premult alpha, or always draw with premultiplied alpha.
- I think always premult in shader can be more flexible, since it's easy to blend premultiplied image in all situations, anyways that's smth for a different PR.
- Can't make this a font property, since otherwise user would be …
=> fonts: Allow disabling automatic setting of glBlendFunc

rts/Rendering/Models/3DModel.cpp
```
In constructor 'LocalModelPiece::LocalModelPiece(const S3DModelPiece*)',
inlined from 'static void LocalModelPiece::_ConstructInstance(void*)' at /spring/rts/Rendering/Models/3DModel.cpp:21:1:
/spring/rts/Rendering/Models/3DModel.cpp:452:32: warning: 'this' pointer is null [-Wnonnull]
452 |         dir = piece->GetEmitDir(); // warning investigated, seems fake
```
`CR_BIND(LocalModelPiece, (nullptr))`
expands out to
`void LocalModelPiece::_ConstructInstance(void* d) { new(d) LocalModelPiece (nullptr); }`
Attempting to call this constructor with a nullptr would cause an attempt to dereference a null pointer. Fortunatly CREG does not currently seem to attempt to use it, instead using the default constructor LocalModelPiece() via vector initialization.
Remove the unnecessary nullptr …
=> Eliminate complier warning in 3DModel

rts/Game/Game.cpp, rts/Game/Game.h, rts/Game/GameController.h, rts/Game/GameInputReceiver.cpp, rts/Game/GameInputReceiver.h, rts/Game/UI/GuiHandler.cpp, rts/Game/UI/MouseHandler.cpp, rts/Lua/LuaHandle.cpp, rts/System/SpringApp.cpp
Part 3 of https://github.com/beyond-all-reason/spring/pull/2130 and https://github.com/beyond-all-reason/spring/pull/2164
- Refactor code from Game.cpp into GameInputReceiver.cpp
- Diff is big, but functionality shouldn't change with this, just a refactor.
- Moves code out into Game.cpp into the new GameInputReceiver.cpp.
- I think moving code out of Game.cpp is good but could keep the simple receiver otherwise
- I think maybe GameInputReceiver could be renamed to ActionInputReceiver or similar.
- Now other "activeControllers" will need to answer to GetReceiver if they want Mouse events, not sure this is a downside. An option is also make keyboard behaviour dependent on activeControllers having a receiver, have to see about this.
=> Mouse button binds. Part 3: Game to InputReceiver refactor

rts/Sim/MoveTypes/HoverAirMoveType.cpp, rts/Sim/MoveTypes/HoverAirMoveType.h, rts/Sim/MoveTypes/StrafeAirMoveType.cpp, rts/Sim/MoveTypes/StrafeAirMoveType.h
- Make StrafeAirMoveType and HoverAirMoveType die on first contact with ground when crashing.
- I think this is the intended behaviour.
- Not very clear why there was [another test](https://github.com/beyond-all-reason/RecoilEngine/blob/e288853833d48b3b1bd9f4f599782b65f9f5f434/rts/Sim/MoveTypes/StrafeAirMoveType.cpp#L525) for close to ground to be killed, instead of just using the previous ground test by UpdatePhysics, but it's not very deterministic... I suppose the bounce can take the aircraft further than the threshold.
- I did a quick test and out of 4000 crashing aircraft there were 2 with 3 bounces and another with 5.
- https://www.reddit.com/r/beyondallreason/comments/1kuz2of/let_me_just_take_out_this_mex/
with pr:
hover:
<image …
=> Make aircraft die on first contact with ground when crashing.

rts/Sim/Units/Unit.cpp
Games can set `blocking = false` in the unit def,
or call `Spring.SetUnitBlocking(unitID, nil, false)` in `gadget:UnitCreated`.
=> Remove uncollidable immobile kamikazes exception

cont/LuaUI/system.lua, cont/base/maphelper/maphelper/system.lua, cont/base/springcontent/LuaGadgets/system.lua, cont/base/springcontent/gamedata/system.lua, rts/Lua/CMakeLists.txt, rts/Lua/LuaEncoding.cpp, rts/Lua/LuaEncoding.h, rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandle.h, rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaIntro.cpp, rts/Lua/LuaMenu.cpp, rts/Lua/LuaParser.cpp, rts/Lua/LuaUI.cpp, rts/builds/dedicated/CMakeLists.txt, tools/unitsync/CMakeLists.txt
- Add `Encoding.EncodeBase64`, `Encoding.DecodeBase64` and  `Encoding.IsValidBase64`
- Add `Encoding.EncodeBase64url`, `Encoding.DecodeBase64url` and `Encoding.IsValidBase64url`
- https://github.com/beyond-all-reason/RecoilEngine/issues/877
- use https://github.com/saurtron/Beyond-All-Reason/tree/test-base64
- Also introduce a mechanism to include modules common to all lua environments.
- Didn't see anything for this, and later the common ones can be refactored into that, like `LuaConstEngine`.
- Maybe base64/encoding isn't wanted everywhere, but I don't see why not.
- Could add to `string` instead of `Encoding`, or some other namespace, but then I think the names would need to conform to the string module casing.
=> Lua base64 methods

rts/Net/NetCommands.cpp, rts/Net/Protocol/NetMessageTypes.h
- NETMSG_MAPDRAW 31 -> NETMSG_MAPDRAW 32
- Also update comment since it wasn't updated, also "new" fromLua par wasn't documented there.
- see 0a649e3bc01818fbe5684a32ab5d91c6cb6c42df
- most tools broken because of fromLua parameter here since ages.
- Mostly relevant for independent demo file parsers.
- for example https://github.com/beyond-all-reason/demo-parser/pull/23
- This was changed with https://github.com/beyond-all-reason/RecoilEngine/pull/1872
- A bit late to change it, but since this is new in rel2503 and didn't yet have a final release, I think still worth it to merge
- I think tool devs will appreciate it.
- This way tools can differently parse the old and new MAPDRAW.
- they are different size, and also point is variable size, so can't just autodetect by size... need to …
=> Change id for NETMSG_MAPDRAW and fix comments.

rts/Sim/Path/QTPFS/PathCache.cpp, rts/Sim/Path/QTPFS/PathManager.cpp, rts/Sim/Path/QTPFS/PathSearch.cpp
Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2369
Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2366 
Prevent unsynced paths using PathRequeueSearch - this issue could lead to the PathRequeueSearch component order in being changed, which can impact the order in which paths are assessed and linked for path sharing.
And account for some synced paths not having an owner.
I am currently testing, and having desync'ed yet. I'm letting the test go long to further increase confidence.
=> Address QTPFS desync

rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h
* Add `Spring.GetFactoryCommandCount` to get a factory command queue count.
* Deprecate getting the count from GetFactoryCommands.
* We deprecated the same pattern at https://github.com/beyond-all-reason/RecoilEngine/pull/1814
* But overlooked `GetFactoryCommands` is doing the same thing.
* This PR brings consistency.
* https://github.com/beyond-all-reason/spring/issues/1725
=> Add Spring.GetFactoryCommandCount for getting a factory queue count.

rts/Sim/Units/CommandAI/BuilderCAI.cpp, rts/Sim/Units/UnitTypes/Builder.cpp
The current behavior results in resurrected units within the resurrection area being chased indefinitely by the rezbot, when they are not fully repaired. This chase often leads to the rezbot reaching the front line, where it's often destroyed.
This patch modifies the behavior so that the rezbot stops repairing the resurrected unit when it exits the direct repair range of the rezbot, i.e., when the unit move. This solution is more preferred then repairing within resurrect area due to the fact that resurrection often happen near the front line. Fixes #986.
=> Prevent rezbot from chasing unrepaired units in area resurrection

cont/base/springcontent/LuaGadgets/Gadgets/mobile_ghost_transport.lua, rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h, rts/Lua/LuaSyncedRead.cpp, rts/Lua/LuaSyncedRead.h, rts/Lua/LuaUnitDefs.cpp, rts/Rendering/Units/UnitDrawer.h, rts/Rendering/Units/UnitDrawerData.cpp, rts/Rendering/Units/UnitDrawerData.h, rts/Sim/Units/Unit.cpp, rts/Sim/Units/Unit.h, rts/Sim/Units/UnitDef.cpp, rts/Sim/Units/UnitDef.h
- Add `leavesGhost` unitdef.
- defaults to true for IsBuildingUnits
- controls what units get unit attribute `leavesGhost` set to true on creation.
- Add `leavesGhost` unit attribute.
- defaults to unitDef->leavesGhost
- per unit toggle for static radar ghosts
- lua `Get/SetUnitLeavesGhost` allows changing this at any time
- controls:
- radar wobbling when under radar
- leaving static ghosts when out of radar or los (and having been in los and contradar before)
- leaves a dead ghost behind when leavesGhost gets disabled and the unit had a static ghost, this way no information is leaked about unit whereabouts (only if 3rd parameter to SetUnitRadarGhost set to true).
- this allows immobile units hopping on transports and looking like they're still there
- Add sample gadget …
=> Fix static ghost behaviours

rts/Game/GameHelper.cpp, rts/Lua/LuaHandle.cpp, rts/Lua/LuaHandle.h, rts/Lua/LuaHandleSynced.cpp, rts/Lua/LuaHandleSynced.h, rts/Lua/LuaUI.cpp, rts/Lua/LuaUI.h, rts/Sim/Projectiles/ExplosionGenerator.cpp, rts/Sim/Projectiles/ExplosionGenerator.h, rts/System/EventClient.h, rts/System/EventHandler.h
- Allow registering and sending Explosion callins to unsynced
- Use the following bar branch: https://github.com/saurtron/Beyond-All-Reason/tree/test-new-unsynced-callins
- It works, but probably still needs some refactor or even rethinking it a bit.
- Also thinking about maybe approach the unsynced callins in a different way
- at least make them asynchronous to the synced code
- maybe also make them batched? that way clients could get one callin with a table of explosions happened in current frame maybe
- Draft for now to gather feedback while I finish testing and reorganizing.
- Framework is there to allow registering other Get/SetWatch* methods for unsynced, but not sure any are needed/useful/possible.
- also note Get/SetWatch* registrations are independent for syncedGadgets, …
=> Allow registering and sending Explosion callins to unsynced.

rts/Game/UI/GuiHandler.cpp
Splits RmlGui/CLuaUI reload to correctly sequence the unload and reload or LUA and RmlUi.
Issue was caused by widget shutdown callin being called after RmlGui was shutdown
=> Fix beyond-all-reason/RecoilEngine#2374 crash when performing luaui reload. 

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
* Adds Spring.AddFeatureDamage mirroring Spring.AddUnitDamage.
* https://github.com/beyond-all-reason/Beyond-All-Reason/pull/5356/files
* https://github.com/beyond-all-reason/RecoilEngine/pull/2418
* Can be useful, and also helps in Feature getting the right behaviour when health goes < 0, as opposed to what happens when SetFeatureHealth is used, that one won't trigger some side effects as damage is expected to go through DoDamage.
* Might be wanted to make SetFeatureHealth trigger side effects too/instead, but I think that one warrants some discussion as it can be more controversial (PR for that at [#2418](https://github.com/beyond-all-reason/RecoilEngine/pull/2418)), also features dont have SlowUpdate so would need to make side effects immediate (would be a slight difference to how …
=> Add Spring.AddFeatureDamage

rts/Lua/LuaSyncedCtrl.cpp, rts/Lua/LuaSyncedCtrl.h
- Add optional feature destruction at Spring.SetFeatureHealth, when `health <= 0`.
- Related https://github.com/beyond-all-reason/RecoilEngine/issues/2401
- https://github.com/beyond-all-reason/RecoilEngine/issues/1684
- https://github.com/beyond-all-reason/RecoilEngine/pull/2417
- https://github.com/beyond-all-reason/RecoilEngine/pull/2435
- At the moment health for the feature isn't checked after SetFeatureHealth, diverging from SetUnitHealth that eventually checks it and destroys.
- This is because features aren't usually active (performing Update)
- Didn't do the destruction compulsory since it would break api behaviour backwards compatibility.
- We can later make passing nil into 3rd parameter deprecated and finally set default to true if wanted, but I think that should be done once …
=> Allow feature destruction on Spring.SetFeatureHealth.

rts/Sim/Path/QTPFS/PathManager.cpp, rts/Sim/Path/QTPFS/PathManager.h, rts/Sim/Path/QTPFS/Systems/PathSpeedModInfoSystem.cpp, rts/System/Ecs/Utils/SystemGlobalUtils.h
Fixes [2479](https://github.com/beyond-all-reason/RecoilEngine/issues/2479)
QTPFS now has a PostFinalizeRefresh() stage, which will allow units to move correctly on randomly generated maps. Prior to this it would take about a minute into the match before the pathing system would adjust correctly. The reason this happens is that the random map starts off as a flat water map and then raises the land after the pathing system has initialized.
=> BUG FIX: QTPFS Update map data before game start when terrain is changed after pathing system is loaded

rts/Rml/Backends/RmlUi_Backend.cpp
> Testing this currently requires reverting 70fe169d78098e465b2b89fc9c4f08ca95adefbc which causes a prior segfault in headless (at least in linux)
This should hopefully (I wasn't able to repro as described) fix https://github.com/beyond-all-reason/RecoilEngine/issues/2371 and https://github.com/beyond-all-reason/RecoilEngine/issues/2005
I did reproduce a similar crash which this is confirmed to fix.
This reinstates code that was marked for exclusion from headless that amongst 2 other things removes contexts marked for removal.
The 2 other things it does are:
1. Update RmlUi contexts (this includes data models & dimensions)
2. Reposition a specific context to be on top
Item 1 I believe should be left in place for headless for the updating of data models so that widgets continue to work as …
=> Remove headless exclusion for RmlGui::Update code

rts/Game/Game.cpp, rts/Rendering/Common/ModelDrawerData.h, rts/System/SpringHashMap.hpp
* Fix incorrect rendering of features / units before the sim starts
* Also switch to faster spring::unordered_map from std in `CModelDrawerDataBase`, modify `SpringHashMap` to allow for this change
* Fixes https://github.com/beyond-all-reason/RecoilEngine/issues/2523
=> Fix: feature 3d models stuck at 0,0,0 before the battle starts

rts/Rml/SolLua/plugin/SolLuaDocument.cpp
When calling ReloadStyleSheet on a document RmlUi reprocesses the head section of the document in a disconnected copy so a context isn't present. If this head section also includes scripts it will also try to re-process these causing LoadInlineScript in SolLua to be called without a context present, leading to a null pointer exception and engine crash.
=> Fix RmlUi crash when reloading stylesheets with documents containing scripts in head section

rts/Rendering/Env/ISky.cpp, rts/Rendering/Env/ISky.h, rts/Rendering/Env/IWater.cpp, rts/Rendering/Env/IWater.h, rts/Rendering/Fonts/CFontTexture.cpp, rts/Rendering/Models/3DModelVAO.cpp, rts/Rendering/Models/3DModelVAO.h, rts/Rendering/Textures/Bitmap.cpp, rts/System/QueueToMain.h
This is a small refactoring of `static inline` data members of type `std::unique_ptr<T>`, where `T` is a incomplete type. It stands in the way of enabling C++23 mode, because `std::unique_ptr` was made `constexpr` in C++23, which [for good reasons](https://github.com/llvm/llvm-project/issues/59966#issuecomment-1397716263) triggers instantiation of `std::unique_ptr` destructor  more eagerly, which fails when pointee type is incomplete.
This is a partial fix for #2021 and continuation of the effort started in #2023. The only untreated case is `SolLuaDataModel` in third-party code, for which I opened https://github.com/LoneBoco/RmlSolLua/pull/3
I tested this locally using Clang 22, but I should note that fixing this issue is not enough to compile with Clang 22 (in any language mode), because …
=> Move std::unique_ptr member definitions out-of-line

rts/Sim/Path/HAPFS/PathManager.cpp, rts/Sim/Path/QTPFS/PathManager.cpp, rts/Sim/Path/QTPFS/PathSearch.h, rts/System/Platform/Threading.cpp
This should deal with the issue of AI commands unsyncing the game. I was only able to test to make sure no issues arise from the changes. I haven't been able to get Zero-K to run networked locally with AI to verify the desyncing behaviour.
=> Separate unsynced path searches from synced path searches in QTPFS

CMakeLists.txt
This PR switches from C++20 to C++23 mode.
Impact on compile times is surprisingly low at 2-4% (tested on Debian using Clang 22 and libstdc++ 14)
Depends on #2559
Fixes #2021
=> Switch to C++23 mode
